### ISSUE TITLE
High cyclomatic complexity in sfml_game.cpp:163

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#107]
The program fails because it is "too complex", how is this fixed?

`sfml_game.cpp, line 163`
(see travis)

**Comment by richelbilderbeek** [comment]
Yup, [it states in the Travis CI build log](https://travis-ci.org/richelbilderbeek/djog_unos_2018/jobs/431710765#L1893):

```
/home/travis/build/richelbilderbeek/djog_unos_2018/sfml_game.cpp:163:1: high cyclomatic complexity [size|P2] Cyclomatic Complexity Number 12 exceeds limit of 10
```

The cyclomatic complexity is the number of ways a function can be traversed. Using only `if`s:

 * No `if`s: 1
 * One `if`: 2
 * Two `if`s: 2 * 2
 * Etcetera

One can fix it in many ways, I suggest you invent a fix yourself :+1: (go ahead and create those new functions!). 

I took the liberty to assign you, as I assume you want to fix it yourself? It helps to become a great dev!

If not not, just unassign and I will notice.
