### ISSUE TITLE
Changing things that work fine

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#112]
I saw @Rijk-van-Putten changed my camera system before it was even tested. And i see by looking at the code it didn't improve it but instead made it slightly worse. This shouldn't happen right?

**Comment by Joshua260403** [comment]
@richelbilderbeek

**Comment by Joshua260403** [comment]
Since i believe all changes in rijks commit are bad except for the wextra thing can it be undone?

**Comment by Joshua260403** [comment]
The one changing the LIBS part has to be undone, he changed the path to the sfml library

**Comment by richelbilderbeek** [comment]
@Joshua260403: I think we as a team must learn how to collaborate. I assume you noticed last Friday how I instructed you to do so. I've seen that @Rijk-van-Putten needed some more time you (more experienced) guys needed, before he was able to do his first successful commit. I already noticed three files were gone [and I put these files these back in](https://github.com/richelbilderbeek/djog_unos_2018/commit/0aca79176c45f09624c0716e9843c1b64e01584b).

I think the job of a medior (or senior) dev is to clean up the mess a junior dev makes. I am happy to see @Joshua260403 took that responsibility and I will try to instruct @Rijk-van-Putten better in his role.

**Comment by richelbilderbeek** [comment]
Close this note, as I believed it was primarily aimed at me. Yes, I read it :-)

**Comment by Joshua260403** [comment]
Maybe we can discuss things like this and "not assigned"(don't know issue
number) thursday and friday to avoid problems

Op ma 24 sep. 2018 17:46 schreef Richel Bilderbeek <notifications@github.com

**Comment by richelbilderbeek** [comment]
We will definitely do so! Thanks for your help!
