### ISSUE TITLE
Undo alot

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#113]
Everything till rijks commit called "commit test" has to be undone. He destroyed ALOT of things.

Sorry about being so harsh, i just can't get over how stupid the changes are, they may have even completely broken the code for Rafayel.

I will redo my complexity fix and i believe that is all that matters that will be undone.

**Comment by Joshua260403** [comment]
@richelbilderbeek

**Comment by Joshua260403** [comment]
There goes my entire day of working on the project

**Comment by Joshua260403** [comment]
I am undoing everything on my branch to the state i had last, made a copy of it

**Comment by Joshua260403** [comment]
i saw the commit, but can't find any traces of it in the code left. hmmmmm

**Comment by Joshua260403** [comment]
already removed at the merge conflict he had i believe. ok didn't see that

**Comment by Joshua260403** [comment]
to  stop this from happening #115

**Comment by richelbilderbeek** [comment]
Again, well done!
