### ISSUE TITLE
tile_contains not working

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#116]
My tile_contains function isn't working

Check the fix me on my branch if you want to help
Feel fry to copy it

Tell me if you are going to help to avoid merge conflicts

**Comment by RafayelGardishyan** [comment]
Which file?

**Comment by Joshua260403** [comment]
Read the issue

Op ma 24 sep. 2018 17:49 schreef Rafayel Gardishyan <
notifications@github.com>:

**Comment by Joshua260403** [comment]
Just so you know it's not the or thingy you should change that to and cus i
tested

Op ma 24 sep. 2018 17:50 schreef Joshua van Waardenberg <
joshuavwaardenberg@gmail.com>:

**Comment by RafayelGardishyan** [comment]
@Joshua260403, I personally would take the beginning and the end coordinates of the tile and look is the mouse is between them

**Comment by RafayelGardishyan** [comment]
@Joshua260403 wtf?

**Comment by Joshua260403** [comment]
Will try that tomorrow

Op ma 24 sep. 2018 17:53 schreef Rafayel Gardishyan <
notifications@github.com>:

**Comment by richelbilderbeek** [comment]
I see the bug, and added some test code to expose it. Good luck fixing it :+1:

**Comment by richelbilderbeek** [comment]
I see the problem. You can read it in [the SFML documentation](https://www.sfml-dev.org/tutorials/2.5/window-inputs.php#mouse). I think you'll find out easily :+1:

**Comment by Joshua260403** [comment]
yeah i thought it would be something to do with that, but i can't find any window object in our code

**Comment by Joshua260403** [comment]
oh wait, m_window

**Comment by Joshua260403** [comment]
x and y = 0 is different for the mouse than for the tiles

**Comment by Joshua260403** [comment]
oh i see

**Comment by Joshua260403** [comment]
the tiles get placed at their width and height values, not their x and y values

**Comment by Joshua260403** [comment]
wait thats not right https://snag.gy/T5fGKP.jpg

**Comment by Joshua260403** [comment]
got the problem, mouse x and y don't go along with camera x and y

**Comment by Joshua260403** [comment]
I DID IT

**Comment by Joshua260403** [comment]
whoops testing

**Comment by Joshua260403** [comment]
o no
