### ISSUE TITLE
add movement border

### ISSUE THREAD

**Issue by same-drenth** [richelbilderbeek/djog_unos_2018#117]
I think that there should be a border witch stops the player from wandering off into the great nothing. 
This (invisible) border will make it impossible for the player to get lost within the game.

**Comment by Joshua260403** [comment]
I'd say, good luck.

**Comment by richelbilderbeek** [comment]
Hmmm, I see the point. @same-drenth: would you volunteer to implement it (after fixing #96)?

**Comment by richelbilderbeek** [comment]
@same-drenth: I assign you to this for tonight. Looking forward to your handiwork!

**Comment by richelbilderbeek** [comment]
@same-drenth: yesterday you told this Issue has been obsoleted. Will close it. Re-open if needed.
