### ISSUE TITLE
Selected tile moves

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#125]
Now we can select a tile, someone needs to make it move.

Are going to move it with the mouse or with W, A, S & D?

**Comment by Joshua260403** [comment]
I'd like to do this since i did the select thing too.

**Comment by richelbilderbeek** [comment]
Awesome! As the dev, you can pick your favourite option :+1:

**Comment by martje127** [comment]
the tiles move good
