### ISSUE TITLE
Moving tile can collide

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#134]
Tiles shouldn't move trough other tiles

**Comment by richelbilderbeek** [comment]
Personally I am unsure about this. Pieces of cloth can be shoved over one another...

**Comment by Joshua260403** [comment]
Should we vote?

**Comment by richelbilderbeek** [comment]
Looks like you take the initiative. I suggest we take a look at what awesomeness you come up with :+1:

**Comment by martje127** [comment]
The tiles do not go through each other it works amazingly
