### ISSUE TITLE
Before October 11th 7:00: Vote team name

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#138]
Time to vote for a team name!

Just copy this thing and keep the Yes/No. You can vote as much `Yes`es as you'd like. In case of a draw, we'll vote again between the number-one competitors only.

```
Name | Vote
---|---
Apex devs | Y/N
Didiem | Y/N
Jog Studio | Y/N
Jog Games | Y/N
Jog Inc | Y/N
Octane | Y/N
The just a little bit older developers | Y/N
```

Deadline: October 11th 7:00: Vote team name

**Comment by Joshua260403** [comment]
Name | Vote
---|---
Apex devs | Y
Didiem | N
Jog Studio | Y
Jog Games | N
Jog Inc | N
Octane | Y
The just a little bit older developers | Y

**Comment by same-drenth** [comment]
Name | Vote
-- | --
Apex devs | N
Didiem | N
Jog Studio | Y
Jog Games | N
Jog Inc | N
Octane | Y
The just a little bit older developers | N

**Comment by annehinrichs22** [comment]
Name | Vote
---|---
Apex devs | N
Didiem | N
Jog Studio | Y
Jog Games | Y
Jog Inc | N
Octane | Y
The just a little bit older developers | N

**Comment by richelbilderbeek** [comment]
Hmmm, a draw between 'Jog Studio' and 'Octane'. I flip a coin to see what happens.

 * heads: 'Jog Studio'
 * tail: 'Octane'

**Comment by richelbilderbeek** [comment]
Tails.

Therefore, out name is now officially named 'Octane'!

Congratulations!
