### ISSUE TITLE
Process mouse input

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#14]
At the moment, mouse input is ignored. Make a first start in responding to mouse, e.g. move something to the location where the mouse is clicked.

**Comment by RafayelGardishyan** [comment]
For testers:
Try clicking with the right and left mouse buttons (With your computer sound on)

**Comment by martje127** [comment]
the mouse imput work if i pres the right mouse button go the sound of and if i press the left mouse button the music go on
