### ISSUE TITLE
Visualize cow

### ISSUE THREAD

**Issue by Rijk-van-Putten** [richelbilderbeek/djog_unos_2018#140]
[**edit by @richelbilderbeek: be more descriptive**]

 * Merge branch `rijk` with your topic branch
 * There is a `cow.png` somewhere loaded
 * Visualize that image

This Issue is a first step in #93 ('Visualize agent's).

Upon completion. let this Issue be tested by the testers.

**Comment by Joshua260403** [comment]
This is a duplicate issue (#93). 
Also there was no issue saying add a cow, so you should add that and assign yourself first.
Lastly, you are assigned to #37 "add menu screen", you should finish that first.

**Comment by richelbilderbeek** [comment]
Thanks @Joshua260403 for correcting me. It was me who was sloppy (and ill yesterday).

**Comment by richelbilderbeek** [comment]
Checko

**Comment by richelbilderbeek** [comment]
I assign @mohammadmatr to this Issue for tonight. Good luck!

**Comment by richelbilderbeek** [comment]
I assign @Rijk-van-Putten to (try to) finish this. Good luck!

**Comment by richelbilderbeek** [comment]
Thanks I will take over this Issue, as a resource maneger class is needed. Thanks @Rijk-van-Putten for your work :+1:

**Comment by richelbilderbeek** [comment]
Done!
