### ISSUE TITLE
Correct 'sfml_game' member variable names, visibility and case

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#144]
**Is your feature request related to a problem? Please describe.**

`sfml_game` follows the common style of prefixing a member variable with `m_`.

```c++
  sf::Music m_background_music;
  double m_camera_x{-100.0};
  double m_camera_y{-100.0};
  sfml_game_delegate m_delegate;
  game m_game;
  sf::RenderWindow m_window;
```

Some newly added variables deviate from this practice.

**Describe the solution you'd like**

 * Prefix all `sfml_game` member variables with `m_`
 * Also, put these in the private section
 * Also, use `snake_case` (instead of CamelCase) 

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
Explanation of snake_case: write_the_name_of_the_variable_in_only_lower_case_letters_and_use_an_underscore_for_spaces

**Comment by Joshua260403** [comment]
I think this is a good one for juniors

**Comment by Joshua260403** [comment]
not closed correctly

**Comment by Joshua260403** [comment]
Functions `vectortoint` and `getTileById` still CamelCase
