### ISSUE TITLE
Tile movement physics

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#145]
As of right now the tiles can't move through or over each other.
This can be changed so the tiles can overlap one another.

**Comment by richelbilderbeek** [comment]
I suggest to first get something moving on the tiles: when there is some game actions, the most fun tile physics will follow. For now, you are in charge to implement this in the way you think is best :+1:

**Comment by Joshua260403** [comment]
Suggest how the tiles will react when you try to move it onto another tile (e.g. try to go one further, or make it move as far as it has to move

**Comment by Joshua260403** [comment]
I will start on the best solution next thursday!

**Comment by richelbilderbeek** [comment]
My suggestion (nope, I am not the boss in this case):

Tiles can move over an other. The more surface they share, the slower they move, as there is more friction. The selected tile is always at the top. When a moving tile hits an animal, the animal is transferred to the moving tile. This may kill the animal, e.g. when a fish on an ocean tile gets transferred to a grassland tile.

**Comment by same-drenth** [comment]
I got a great idea. How about, if two tiles overlap, they form a new tile together only on the overlapping part. this new tile is formed from the overlapping tiles.  For example, ocean and grassland becomes a swamp; Mountains and arctic becomes arctic mountains; Grasslands and mountains becomes hills land(Netherlands); Savanna and dessert becomes ???.

**Comment by Joshua260403** [comment]
I like sames idea, so that's going to be it

**Comment by Joshua260403** [comment]
Need a function to delete a tile to continue

**Comment by richelbilderbeek** [comment]
Yup, I'll step in shortly, make things a bit clearer, then re-assign you :+1:

**Comment by richelbilderbeek** [comment]
I've let the tiles merge in [this commit](e8e0d77bf03421d5f78dcee98052dca9ea63329a).

I think you can take over again now :+1:

**Comment by richelbilderbeek** [comment]
I close this Issue, as I feel it is finished. Will add a new one if I feel the need to :rainbow:
