### ISSUE TITLE
Tiles must finish movement when selecting another

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#149]
When you deselect a tile while it's still moving it stops halfway!

**Comment by Joshua260403** [comment]
How odd, right now when activating the bug and reselecting the tile, the tile continues its movement, deselecting works as pausing now

**Comment by Joshua260403** [comment]
gg i did it, and it remembers your clicks during movements

**Comment by martje127** [comment]
its al good

**Comment by martje127** [comment]
its al good

**Comment by martje127** [comment]
sorry
