### ISSUE TITLE
Ubuntu Linux: Build Fails

### ISSUE THREAD

**Issue by RafayelGardishyan** [richelbilderbeek/djog_unos_2018#15]
When trying to build our project recieving this error:
```
/home/rafayel/SFML-DOW/include/SFML/System/FileInputStream.hpp:55: error: ‘class sf::FileInputStream’ has pointer data members [-Werror=effc++]
 class SFML_SYSTEM_API FileInputStream : public InputStream, NonCopyable
                       ^
```
but not only for this file but also:
sf:: -> Text, Sprite, RenderTexture, textureRect, bounds, Shape, Window, Cursor, Context, ThreadLocal, Thread, Mutex, MemoryInputStream and FileInputStream

**Comment by richelbilderbeek** [comment]
Pushed to `richel`. Will merge with `develop` and then `master` if and only if builds pass.
