### ISSUE TITLE
Add ellyjet to README

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#150]
**Is your feature request related to a problem? Please describe.**

README.md shows most branches and their status. `ellyjet` is missing.

**Describe the solution you'd like**

Add a line for `ellyjet`

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by richelbilderbeek** [comment]
Sorry I was unclear: I'd like to keep the branches sorted alphabetically after `master` and `develop`. Please put `ellyjet` between `anne` and `joshua`.

Sure it's easy, but it will help getting some git exercise :+1:

**Comment by EllyJet** [comment]
Done
