### ISSUE TITLE
Sync camera movement with tile movement

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#153]
As they are right now the controls are a bit all over the keyboard, this can be done better.

My suggestion:
- When no tile is selected, use WASD to move the camera normally
- When a tile is selected, make it so the camera moves with the selected tile (preferably in the center of the screen)

**Comment by richelbilderbeek** [comment]
As far as I understood, @martje127 tried to break the code, but couldn't. I guess he forgot to close this Issue? I will do so for him.
