### ISSUE TITLE
Game state: proper style and type

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#159]
**Is your feature request related to a problem? Please describe.**

At the moment, the game's state is defined an old `enum` in CamelCase:

```c++
enum GameState {TitleScreen, MenuScreen, AboutScreen, Playing};
```

**Describe the solution you'd like**

I would like this to be:

 * an `enum class`
 * with lowercase name
 * with lower case values
 * in a separate unit with filename `game_state.h` and `game_state.cpp`

The rest of the code must also be fixed, e.g. `TitleScreen` will become `game_state::title_screen` 

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by EllyJet** [comment]
Done
