### ISSUE TITLE
Absent again... But also a cool link again!!!

### ISSUE THREAD

**Issue by annehinrichs22** [richelbilderbeek/djog_unos_2018#164]
This time I'm going to the TU Eindhoven for their open day, it's going to be a very long train ride again so I won't be back in time to join you.

***Cool link:*** _http://www.informaticaolympiade.nl/_
It's a contest in which you solve programming puzzles, you can get a real certificate and you can win prizes. You can do this from home.
(If you're incredibly good you can even go to Japan for the international finals!!!)

**Comment by richelbilderbeek** [comment]
Noted! Good luck from team Octane!
