### ISSUE TITLE
agent must contain an agent's logic only

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#165]
**Is your feature request related to a problem? Please describe.**

An `agent` must contain an agent's logic only. Adding `Sprite` and `Texture` mismatches that.

**Describe the solution you'd like**

 * Remove the `Sprite` and `Texture` member variables from `agent`
 * Use `sfml_resources` to get the sprites and textures need when drawing (and only then!) the agent. [**edit: this is already done**]

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by EllyJet** [comment]
Done
