### ISSUE TITLE
Visualize cows properly

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#167]
**Is your feature request related to a problem? Please describe.**

At the moment, the agents are displayed:

![2018-10-12-123732_802x630_scrot](https://user-images.githubusercontent.com/2098230/46865347-86752e00-ce1d-11e8-97d1-9ae15aabf96f.png)

**Describe the solution you'd like**

I would like:

 * The cows to be drawn centered on their coordinats (now the top-left of the cow picture matches their coodinat)
 * The cows to be drawn smaller

**Describe alternatives you've considered**

None.

**Additional context**

It would be a good idea to only create cows on suitable tile types, like grassland.

**Comment by richelbilderbeek** [comment]
I think @Rijk-van-Putten would like to do this :+1:

**Comment by jorn600** [comment]
@Rijk-van-Putten It would be a good idea to use the origin function to set the center origins. for example: cow.setOrigin(10, 20);

Making the cows smaller could be done by using the scale function. like here: cow.scale(0.5f, 0.5f);

**Comment by martje127** [comment]
yes ther is a cow
