### ISSUE TITLE
Add and visualize grass agent

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#168]
**Is your feature request related to a problem? Please describe.**

There is already an `agent_type::grass`.

**Describe the solution you'd like**

 * the grass should be added to a tile of type `grassland` or other grassy types
 * the grass should be visualized

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by martje127** [comment]
there is a gras picture but i think it shold not move like animals
