### ISSUE TITLE
Add and visualize a fish

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#169]
**Is your feature request related to a problem? Please describe.**

There is grass and a cow.

**Describe the solution you'd like**

 * Add an `agent_type` named `fish`
 * Only tiles of type `ocean` should contain fish
 * Visualize the fish

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by martje127** [comment]
in the dark bleu can I see a fish
