### ISSUE TITLE
'int sfml_game::vectortoint(std::vector<int>)' must be a free function

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#172]
**Is your feature request related to a problem? Please describe.**

There exists a member function called `int sfml_game::vectortoint(std::vector<int>)`that does not use `sfml_game` at all. Therefore it can and should be a free function.

**Describe the solution you'd like**

Make `vectortoint` to free function. 

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by annehinrichs22** [comment]
Done.
