### ISSUE TITLE
Increase code coverage for STL/non-SFML classes

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#175]
**Is your feature request related to a problem? Please describe.**

Only code that actually has a purpose must be kept. Remove unused code.

This is an ongoing Issue.

**Describe the solution you'd like**

 * You can see the code coverage [here](https://codecov.io/github/richelbilderbeek/djog_unos_2018)
 * For STL/non-SFML classes, either remove unused code or add tests to increase code coverage. For example, class `x` is tested is `x_test.cpp` 

For SFML classes, increasing code coverage is harder. I will make a new Issue for that if the team is ready.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
Got main.cpp on 100%

**Comment by Joshua260403** [comment]
Game.cpp should be pretty easy, just need to figure out why it's not testing the load function

**Comment by Joshua260403** [comment]
Since this is an ongoing issue, can i stay assigned to this and still do other issues?

**Comment by richelbilderbeek** [comment]
Well done @Joshua260403! Getting code coverage to 100% is not only useful, but must have been a nice learning experience. 

Perhaps unexpected, axactly for that reason am I going to unassign you here, so another medior can have a shot at this. As codecov is 100%, I will close the Issue for now and re-open when needed.
