### ISSUE TITLE
tile must have a z

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#176]
**Is your feature request related to a problem? Please describe.**

There are ideas about tiles passing over one another. To do so, we'll need to store what Z-order the tiles have. The Z-order is part of the game logic: a higher Z-order denotes a tile that is higher.

**Describe the solution you'd like**

 * Add a variable `double tile::m_z`
 * Add a member function `double tile::get_z()`
 * Add a member function `tile::set_z(const double z)`: any z value is valid.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by EllyJet** [comment]
Done
