### ISSUE TITLE
agents must be members of `game`

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#179]
**Is your feature request related to a problem? Please describe.**

Currently, the agents are member variables of `tile`. This was the natural thing to do, up until tiles could overlap.

**Describe the solution you'd like**

 * Move `std::vector<agent> tile::m_agents` to be `std::vector<agent> game::m_agents`
 * The coordinats of an `agent` *were* the relative positions on the tile, this will become the relative position on the world 
 * In the constructor of `game`, put the agents at the world coordinats at the center of the tiles (so it keeps looking exactly the same)

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
Done

**Comment by Joshua260403** [comment]
https://snag.gy/bZkQHu.jpg
hmmm, that ain't right
