### ISSUE TITLE
Add and visualize crocodile

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#180]
**Is your feature request related to a problem? Please describe.**

We need an animal to eat the cow.

**Describe the solution you'd like**

 * Add a new `agent_type` called `crocodile`
 * Visualize it
 * A crocodile does not eat fish

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by richelbilderbeek** [comment]
Adding a new tile type is a separate Issue. If you think adding a swamp tile is important, go ahead and create it.

**Comment by martje127** [comment]
in the swamp is a crocodile
