### ISSUE TITLE
Make sfml_menu_screen prettier

### ISSUE THREAD

**Issue by martje127** [richelbilderbeek/djog_unos_2018#184]
I don't like the shape of the **[edit:] menu** screen. Can it become a bit prettier?

**Comment by JornPrengerFormeel** [comment]
What do you mean? What shape should the title screen become? Prettier is also pretty subjective, maybe you could elaborate a bit.

**Comment by JornPrengerFormeel** [comment]
I discussed this with Mart and he told me some of the things he meant:
-Change text from "Title Screen" to "Nature Zen".
-Change font and possibly add an image containing the words "Nature zen" and add images related to the subject of the game.

**Comment by richelbilderbeek** [comment]
Blimey, IRL communication :grin:  :+1:

**Comment by richelbilderbeek** [comment]
Note, it must be called as such:

```
sfml_menu_screen g;
g.exec();
```

Create a class called `sfml_menu_screen` and put it in `sfml_menu_screen.h` and `sfml_menu_screen.cpp`.

It must be closable by pressing space.

**Comment by richelbilderbeek** [comment]
There is a test written already:

```
  if (std::count(std::begin(args), std::end(args), "--title")) {
    //#define FIX_ISSUE_184
    #ifdef FIX_ISSUE_184
    sfml_about_screen g;
    g.exec();
    return 0;
    #endif
  }
```

Uncomment `//#define FIX_ISSUE_184` to start fixing it. 

Remove the `#define`, `#ifdef`, `#endif` after fixing it.

**Comment by Joshua260403** [comment]
Someone removed my beautiful menu screen, starting over...

**Comment by richelbilderbeek** [comment]
The merge conflicts apparently took over. Tip: it *is* in the history of `develop` and your branch! You can just copy-paste from there :1st_place_medal:

**Comment by Joshua260403** [comment]
It happened herehttps://github.com/richelbilderbeek/djog_unos_2018/commit/989e08f0808bf6aa2da5d61c6a7d9291790b5eb2
Be careful what to keep, good thing this wasn't too much work to redo.

**Comment by richelbilderbeek** [comment]
Can you see who did it? If yes, I/you should attend him/her :grin:

**Comment by martje127** [comment]
its beautiful
