### ISSUE TITLE
Create first world part

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#19]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

I want the game to display an all black background and one dark-green rectangle (say, grassland).

![nature_zen](https://user-images.githubusercontent.com/2098230/45468260-01b2c980-b724-11e8-95b4-42756b7af960.png)

In a future Issue, I will 

 * request mouse input 
 * request keyboard input
 * improve the looks, will assign to @same-drenth 
 * add music and sound effects
 * etcetera

**Describe alternatives you've considered**

None.

**Additional context**

Will assign @RafayelGardishyan. At @RafayelGardishyan: feel free to assign this task to someone else.

**Comment by richelbilderbeek** [comment]
This will be the Issue to be solved tomorrow/Friday. Will assign someone/somepeople then.

**Comment by RafayelGardishyan** [comment]
I will solve that today in the afternoon

**Comment by RafayelGardishyan** [comment]
I can't work this evening. Tomorrow I will do this

**Comment by richelbilderbeek** [comment]
Agree. I will unassign you for now and look for an assignee tonight. If none, you can assign yourself for this job tomorrow. Great plan :+1:

**Comment by Joshua260403** [comment]
It's doing this so shouldn't this one be closed?

**Comment by richelbilderbeek** [comment]
Nope. I quote:

> RafayelGardishyan moved this from In progress to To be checked by testing

This means this Issue will be closed by testing on Thursdays, else by me on Friday.

**Comment by martje127** [comment]
the first world part show up
