### ISSUE TITLE
Add isis to Team

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#190]
**Is your feature request related to a problem? Please describe.**

Isis is part of our team. She is absent at [team.md](https://github.com/richelbilderbeek/djog_unos_2018/blob/master/doc/team.md) however.

**Describe the solution you'd like**

Add Isis to [team.md](https://github.com/richelbilderbeek/djog_unos_2018/blob/master/doc/team.md).

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by martje127** [comment]
i can see isis in team.md
