### ISSUE TITLE
Add Game Over screen

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#192]
**Is your feature request related to a problem? Please describe.**

Goal of the game is to accumulate Zen (whatever that is) up until a Game Over. Currently, there is no Game Over screen.

**Describe the solution you'd like**

 * Create a class `sfml_game_over_screen`
 * It can be called with:

```c++
sfml_game_over_screen g;
g.exec();
```
 
 * It can be closed by pressing space

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
The way screens work has changed, you can ask me (@Joshua260403) for help with the new screen manager

**Comment by richelbilderbeek** [comment]
@Tomstuivenga: I am going to liberate you from this Issue, due to the new windows manager by @Joshua260403.

@Joshua260403: could you make a stub of the Game Over screen? I will assign you :innocent:

**Comment by Joshua260403** [comment]
Q: Does it have to be a stub?

A: I don't care imma hook it up to the rest anyways 🌱
