### ISSUE TITLE
Add swamp tile

### ISSUE THREAD

**Issue by JornPrengerFormeel** [richelbilderbeek/djog_unos_2018#193]
**Is your feature request related to a problem? Please describe.**
The problem is there not being a tile for the crocodile agent to stay on.

**Describe the solution you'd like**
Adding a swamp tile.

**Describe alternatives you've considered**
Visualizing the crocodile on other tiles, but these are not the animals normal habitats.

**Comment by martje127** [comment]
yes there is a swamp tile
