### ISSUE TITLE
Bug: tile collision makes too many tiles disappear

### ISSUE THREAD

**Issue by martje127** [richelbilderbeek/djog_unos_2018#195]
*Problem*
When merging tiles it creates none tiles.
*Reproduce bug*
If you set the tiles like this
![2018-11-08-204928_802x630_scrot](https://user-images.githubusercontent.com/29956775/48223935-aa824b80-e398-11e8-8809-7ff06a145a26.png)
and collide the middle grassland with the left grassland, then get you this
![2018-11-08-205024_802x630_scrot](https://user-images.githubusercontent.com/29956775/48223937-aa824b80-e398-11e8-94b2-79a80751483d.png)

**Comment by richelbilderbeek** [comment]
Excellent report! Will ask someone of the Friday team to fix it :+1:

**Comment by richelbilderbeek** [comment]
After a refactoring by @Joshua260403 (tiles are now 1x2 distance units), I see the current error is due to the selected tile being deleted. Then its tile ID is absent. @Joshua260403: want to fix this?

**Comment by Joshua260403** [comment]
Should be easy

Op do 8 nov. 2018 22:57 schreef Richel Bilderbeek <notifications@github.com:

**Comment by Joshua260403** [comment]
this is more difficult than i expected it to be, when outputting the id from getTileById, it returns 51 52 51 52 51 52 and so on

**Comment by Joshua260403** [comment]
I just don't know anymore

**Comment by richelbilderbeek** [comment]
I'll have another stab at it :+1:

**Comment by richelbilderbeek** [comment]
Agreed?

**Comment by Joshua260403** [comment]
Yep

Op zo 11 nov. 2018 16:03 schreef Richel Bilderbeek <notifications@github.com
:
