### ISSUE TITLE
Make the screen maximized

### ISSUE THREAD

**Issue by same-drenth** [richelbilderbeek/djog_unos_2018#196]
Make the game start in fullscreen and make sure that the proportions stay the same as well as keep the hitboxes on the tiles normal. 
MAY NEED ASSISTANCE.

**Comment by JornPrengerFormeel** [comment]
The window doesn't open in the middle of the screen and you can't easily close it so I would suggest to move this to In progress

**Comment by richelbilderbeek** [comment]
Well spotted! But the Issue has been solved. Go ahead and make another Issue: 'Escape must close the game'

**Comment by Joshua260403** [comment]
The window shouldn't be fullscreen, that will make it so we have to use alt+f4 to close the program. Also, the current progression triggers an assert at the start of the program (at least im pretty sure this caused it). Also also the current version doesn't make it fullscreen, it just fills the rest of the screen with blackness. So if you ask me this isn't done.

**Comment by richelbilderbeek** [comment]
As both @JornPrengerFormeel  and @Joshua260403 suggest to remove the full-screenness **for now**, I suggest to remove the full-screenness for now. Close this Issue, will make a new one to remove the full-screennesss for now.
