### ISSUE TITLE
Test conversion from tile_type to std::string and back

### ISSUE THREAD

**Issue by JornPrengerFormeel** [richelbilderbeek/djog_unos_2018#197]
Thanks @richelbilderbeek for writing this :+1: 

**Is your feature request related to a problem? Please describe.**

Currently, `tile_type` can get converted to `std::string` wiith `to_str`, and there is a function that goes the other way around. It is not yet tested if this works

**Describe the solution you'd like**

Using `get_all_tile_types`, iterate over all `tile_type`s. For each `tile_type`, convert it to `std::string`. Each `std::string` must then be converted to `tile_type`. The initial and final `tile_type` must be the same. Put it in `test_tile_type`.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by JornPrengerFormeel** [comment]
Fixed dude

![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by richelbilderbeek** [comment]
Closing it then :+1:
