### ISSUE TITLE
Add music

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#20]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

A good game has music. There is [an MP3](https://github.com/richelbilderbeek/djog_unos_2018/blob/richel/EddiesTwister.mp3) I want played during the game.

I will ask to change the music in the future. This Issue is just about getting it working. 

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by RafayelGardishyan** [comment]
I think @Joshua260403 will like doing this

**Comment by Joshua260403** [comment]
I'll see about that, have to learn to work with sfml and stuff first.

**Comment by same-drenth** [comment]
I'm interested in the music part since I'm already lead graphics

**Comment by same-drenth** [comment]
I think that graphics and music go together

**Comment by richelbilderbeek** [comment]
@same-drenth: I agree they graphics and music go together. 

It appears that @Joshua260403 assigned himself, and I suggest he gets the (crappy for now) music working in SFML.

Same gets to decide which music after it has been put in. If there are conflicts about the music choice, we'll vote. Same's vote count double however. If it's a draw, I'll pick the winner.

**Comment by same-drenth** [comment]
Nice, sounds good to me

**Comment by Joshua260403** [comment]
I certainly did not assign myself as i don't even know how to do this and i also don't know how to unassign myself now.

**Comment by richelbilderbeek** [comment]
I suggest either @Rijk-van-Putten of @same-drenth does this. First one to assign to this gets the job :rainbow:

**Comment by RafayelGardishyan** [comment]
Sorry Richel but mp3 is not supported
I'will do this issue but I'll choose an other track

**Comment by RafayelGardishyan** [comment]
Richel, do you know how to add resource folder to the build in qt creator?

**Comment by richelbilderbeek** [comment]
Just did so on your branch :+1:

**Comment by Joshua260403** [comment]
like the current music, shouldn't this issue be closed?

**Comment by richelbilderbeek** [comment]
Will be closed by a tester on Thursday, else one can close it this Friday.

**Comment by Joshua260403** [comment]
are they really going to see if they can break the music?

**Comment by richelbilderbeek** [comment]
1) Yes
2) It is mostly to get them into the flow of testing. It's same the same warming-up process all of us have :-)
