### ISSUE TITLE
Create tile_id class

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#200]
**Is your feature request related to a problem? Please describe.**

Currently, a tile ID is coded by an integer.But not all ints are IDs and vice version. It would be better -and a good exercise- to make a `tile_id` class

**Describe the solution you'd like**

 * Create a class called `tile_id`. It stores the ID as an int called `m_id`. `m_id` can be read by `tile_id::get`
 * Change `int get_new_id()` to `tile_id get_new_tile_id()`
 * Write a function called `test_tile_id` and call it from `test` 

Tests:

```c++
//Tile IDs must be unique
const tile_id a;
const tile_id b;
assert(a != b);
```

```c++
//Tile IDs can be copied
const tile_id a;
const tile_id b;
a = b;
assert(a == b);
```

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
Theres something going wrong here i believe, there is currently two id classes: tile_id and id

**Comment by Joshua260403** [comment]
Hmmm, its gone after another merge.

**Comment by Joshua260403** [comment]
The header was added to the .pri but it didn't exist

**Comment by Joshua260403** [comment]
Not so fast

**Comment by Joshua260403** [comment]
nah-ah

**Comment by Joshua260403** [comment]
wrong column

**Comment by richelbilderbeek** [comment]
I saw Rijk's work yesterday, it passed all tests. I was reasonably sure we put it at 'To be merged with develop', but that appears to have been an illusion :rainbow:. Put it there now :1st_place_medal:

**Comment by Joshua260403** [comment]
Github said rijk and develop are identical
