### ISSUE TITLE
A fish must move

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#201]
**Is your feature request related to a problem? Please describe.**

Fishes are mobile creates. Currently, however, they do not move.

**Describe the solution you'd like**

I want the fish to move randomly.

There is a test for this:

```c++
  //#define FIX_ISSUE_201
  #ifdef FIX_ISSUE_201
  // A fish moves
  {
    const double x{12.34};
    const double y{56.78};
    agent a(agent_type::fish, x, y);
    a.move();
    assert(a.get_x() != x || a.get_y() != y);
  }
```

Uncomment `//#define FIX_ISSUE_201` to start fixing it. 

Remove the `#define`, `#ifdef`, `#endif` after fixing it.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by richelbilderbeek** [comment]
Thanks to some merge conflict mishap, the code that solves this Issue is lost somewhere Let's try again :+1:

**Comment by Joshua260403** [comment]
High priority since this seems to break develop
