### ISSUE TITLE
Crocodiles must move

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#202]
**Is your feature request related to a problem? Please describe.**

Crocodiles are mobile creates. Currently, however, they do not move.

**Describe the solution you'd like**

I want the crocodiles to move randomly.

There is a test for this:

```c++
  //#define FIX_ISSUE_202
  #ifdef FIX_ISSUE_202
  // A crocodile moves
  {
    const double x{12.34};
    const double y{56.78};
    agent a(agent_type::crocodile, x, y);
    a.move();
    assert(a.get_x() != x || a.get_y() != y);
  }
  #endif // FIX_ISSUE_202
```

Uncomment `//#define FIX_ISSUE_202` to start fixing it. 

Remove the `#define`, `#ifdef`, `#endif` after fixing it.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by martje127** [comment]
crocodiles are alredy moving

**Comment by richelbilderbeek** [comment]
Crocodiles are standing still again, so I re-open this Issue.

**Comment by same-drenth** [comment]
done

**Comment by richelbilderbeek** [comment]
Thanks to some merge conflict mishap, the code that solves this Issue is lost somewhere Let's try again :+1:

**Comment by Joshua260403** [comment]
High priority since this seems to break develop
