### ISSUE TITLE
No full-screen for now

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#205]
**Is your feature request related to a problem? Please describe.**

In #196 the screen was set to full-screen, which *is* desired in the end. But some team members argue that this is too much of a drag for now.

**Describe the solution you'd like**

Find the line in which full-screen is set. 

```c++
[the line that sets full-screen]
```

Add `#ifdef`s like this:

```c++
#ifdef FIX_ISSUE_196
//Make the game full-screen later
[the line that sets full-screen]
#endif // FIX_ISSUE_196
```

**Describe alternatives you've considered**

We could make it a flag, like `--full-screen`, but I feel this is not worth it. If you would enjoy to do so, go ahead! Then, by default, the screen must not be full-screen (for now).

**Additional context**

None.

**Comment by richelbilderbeek** [comment]
I think @same-drenth knows best how to do this :+1:

**Comment by martje127** [comment]
if I start de game there is no full screen
