### ISSUE TITLE
Add title screen

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#206]
**Is your feature request related to a problem? Please describe.**

When the game starts, we need a title screen. Something like:

![title](https://user-images.githubusercontent.com/2098230/48638188-2ea78500-e9d0-11e8-8cd4-462a753794bc.png)

**Describe the solution you'd like**

Create a new class `sfml_title_screen`, similar to the `sfml_about_screen`. This test should work:

```c++
  //#define FIX_ISSUE_206
  #ifdef FIX_ISSUE_206
  if (std::count(std::begin(args), std::end(args), "--title")) {
    sfml_title_screen g;
    g.exec();
    return 0;
  }
  #endif
```

Screen must be closeable by space or escape.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by richelbilderbeek** [comment]
Additionally, remove the member variables from `sfml_game` that were used to show the title screen :grin:

**Comment by martje127** [comment]
its beautiful
