### ISSUE TITLE
Architectural: seperate game logic from game display

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#21]
**Is your feature request related to a problem? Please describe.**

No,

**Describe the solution you'd like**

Currently, the `game` class maintains both the game logic and game displayal. I suggest to split this up in two: `sfml_game` and `game`, in which `sfml_game` has a `game`.

```c++
class sfml_game
{

private:
  game m_game;
};
```

 * `game` should contain the game logic, e.g. score, tiles, etcetera. `game` will not handle input directly.
 * `game_sfml` should contain the `game` and everything to display it, e.g. music, fonts, etcetera. `game_sfml` will handle user input directly, and convert it to input suitable for `game`

Future Issues will be:

 * test `game` to process Commands (the Command design pattern, that is)
 * test `sfml_game` to process mouse and keyboard input

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by RafayelGardishyan** [comment]
Starting with this Saturday 15 September

**Comment by richelbilderbeek** [comment]
@RafayelGardishyan: sure I will help. It need not be perfect at once, just as long as well go forward :rainbow:

**Comment by RafayelGardishyan** [comment]
I dont't completely understand what sfml_game should do and what game should do.
Also I'm afraid I have to use lists

**Comment by RafayelGardishyan** [comment]
Correction:
I've created a game class which contains a sfml_game class but the game class does at this moment nothing but execute sfml_game.exec()

In the future we'll be adding logic to game and not sfml_game


(P.S. sfml_game has now a vector which contains all the shapes which need to be drawn and you can add shapes by sfml_game.add_shape())

**Comment by RafayelGardishyan** [comment]
Moving to "To be checked by Testing"

**Comment by richelbilderbeek** [comment]
These are some guidelines:

 * the `game` class contains the game logic. Data types are built-in (int, double, etc.) or STL (std::string, std::vector)
 * the `sfml_game` class is about displaying that game logic. It has a `game` member variable, it uses for the game state. Its member variables can be SFML data types.

**Comment by richelbilderbeek** [comment]
I will modify the architecture in the even better direction tomorrow/Friday before 17:00.
