### ISSUE TITLE
Rename sfml_game member variable to m_tile_speed

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#212]
**Is your feature request related to a problem? Please describe.**

Currently, `sfml_game` has member variable:

```c++
class sfml_game
{
  //...
  double tile_speed = 1; // 115/tile_speed must be a whole number!

  //...
};
```

Member variables should start with `m_`.

**Describe the solution you'd like**

Rename the variable to `m_tile_speed`.

Trick: click it with the right mouse button, click `Refactor | Rename Symbol Under Cursor`. 
This renames the member variable name throughout the project.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
Is this done?

**Comment by richelbilderbeek** [comment]
@robkruger: Instead of moving an Issue to Done in the Project screen, please close the Issue!

Now @Joshua260403 (and now me) are checking an Issue that has already been done. I will close it now :rainbow:
