### ISSUE TITLE
Rename sfml_game member variable to m_outline

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#213]
**Is your feature request related to a problem? Please describe.**

Currently, `sfml_game` has member variable:

```c++
class sfml_game
{
  //...
  sf::Color outline;

  //...
};
```

Member variables should start with `m_`.

**Describe the solution you'd like**

Rename the variable to `m_outline`.

Trick: click it with the right mouse button, click `Refactor | Rename Symbol Under Cursor`. 
This renames the member variable name throughout the project.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by martje127** [comment]
i replace de word

**Comment by richelbilderbeek** [comment]
You forgot to change all its uses. I've fixed it, as it was on develop. :+1:
