### ISSUE TITLE
Remove sfml_game::test_agent_tex

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#214]
**Is your feature request related to a problem? Please describe.**

Currently, `sfml_game` has member variable:

```c++
class sfml_game
{
  //...
  Texture test_agent_tex;

  //...
};
```

It is not used.

**Describe the solution you'd like**

Delete it.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by martje127** [comment]
its deletet
