### ISSUE TITLE
Prefix sfml_camera member variables by m_

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#216]
**Is your feature request related to a problem? Please describe.**

Currently, `sfml_camera` has member variables:

```c++
class sfml_camera
{
  //...
  bool movecam_r = false;
  bool movecam_l = false;
  bool movecam_u = false;
  bool movecam_d = false;

  //...
};
```

Member variables should start with `m_`.

**Describe the solution you'd like**

Put `m_` in front of each member variable.

Trick: click it with the right mouse button, click `Refactor | Rename Symbol Under Cursor`. 
This renames the member variable name throughout the project.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by richelbilderbeek** [comment]
@Rijk-van-Putten: indeed, that was all there is! Well done :+1:

**Comment by richelbilderbeek** [comment]
This Issue originally was about these member variables in the `sfml_game` class. As these were moved to the `sfml_camera` class (before the work of @Rijk-van-Putten), this needs to be done again.

**Comment by Fsetrodinomo** [comment]
done
