### ISSUE TITLE
Rename to sfml_menu_screen::m_main_text

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#226]
**Is your feature request related to a problem? Please describe.**

Nature Zen uses snake_case. All variables should be written as such. Also redundant naming should be avoided.

**Describe the solution you'd like**

Rename `sfml_menu_screen::mainMenuScreenText` to `sfml_menu_screen::m_main_text`

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
Verified
