### ISSUE TITLE
Rename and make member variables private in sfml_about_screen

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#227]
**Is your feature request related to a problem? Please describe.**

`sfml_about_screen` has two member variables that are needlessly public and do not follow the `m_snake_case` convention.

**Describe the solution you'd like**

Make the member variables private and write them as `m_snake_case`.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Fsetrodinomo** [comment]
Donee
