### ISSUE TITLE
Create camera class

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#229]
**Is your feature request related to a problem? Please describe.**

`sfml_game` has at least 6 member variables dealing with a camera. This dilutes `sfml_game` needlessly: that camera functionality should be bundled in a class.

**Describe the solution you'd like**

Create a new class called `sfml_camera`. Move all member variables from `sfml_game` that have to do with camera movement in that class. Test that class! Code coverage should be 100%

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
Shouldn't the camera work?

**Comment by richelbilderbeek** [comment]
Hmmm, apparently this broke a couple of merges later. Thanks for re-opening this :+1:

**Comment by richelbilderbeek** [comment]
I see nothing wrong :confused: 

I assume it is thus fixed :rainbow: 

Else I expect a more detailed bug report :+1:

**Comment by Joshua260403** [comment]
Doesn't work for me

**Comment by Joshua260403** [comment]
I believe another merge conflict has gone wrong

**Comment by Joshua260403** [comment]
Ill try and find it

**Comment by Joshua260403** [comment]
The class should have functions to move the camera right?

**Comment by Joshua260403** [comment]
It doesn't have that.
Also this was done by an unknown person who isn't in team.md, thats why it wasn't closed i think.

**Comment by richelbilderbeek** [comment]
I guess that was done on a laptop set up for [Modanung](https://gitlab.com/Modanung) :rainbow:

**Comment by Joshua260403** [comment]
I decided it was time the camera worked, removed one `!` (that i already marked like a month and a half ago with a TODO) and now it works -_-
There may be some improvements that could be made but you'll have to look into that.
