### ISSUE TITLE
Remove unused sfml_game member variables

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#230]
**Is your feature request related to a problem? Please describe.**

In `sfml_game` I find already three unused member variables:

```c++
  Text titleScreenText;
  Text aboutScreenText;
  Font m_font;
```

Unused member variables are only diluting what the code is trying to express.

**Describe the solution you'd like**

Delete these. If you find more, delete those too.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by JolienGay** [comment]
Deleted: Text titleScreenText; Text aboutScreenText but not Font m_font; because it had dependencies.

**Comment by Joshua260403** [comment]
I believe this can be closed since mart can't test this.

**Comment by richelbilderbeek** [comment]
Agree, will close!

**Comment by Joshua260403** [comment]
Wrong decision though

**Comment by richelbilderbeek** [comment]
I think that Jolien somehow used an older version?

Trick I just learned: just let your branch be overwritten by develop:

```
git checkout jolien
git merge -X theirs develop
```

Perhaps she'd like this :+1:
