### ISSUE TITLE
Show actual branch name in README

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#235]
**Is your feature request related to a problem? Please describe.**

Currently, at the README shows `giorgio` as a branch name. The branch is named `azereuz`.

**Describe the solution you'd like**

Either rename the branch to `giorgio` or mention `azereuz` in the README.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by azereuz** [comment]
Wasn't sure if I had to use my branch name or nickname there, how can I rename the branch name to giorgio?

**Comment by richelbilderbeek** [comment]
Definitely! Also would make it easier for the others to use your branch. At the top, above the code, there is a 'Branches' tab, where you can rename the branch. Good luck :+1:

**Comment by richelbilderbeek** [comment]
@azereuz: well done, will close the Issue :+1:
