### ISSUE TITLE
Something went wrong in create_default_tiles

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#238]
It is a giant mess right now, so i suggest to remake it.

**Comment by Joshua260403** [comment]
Interesting, this fixed the white tiles. Something going wrong in the merge process i assume...

**Comment by richelbilderbeek** [comment]
I predict multiple tiles were put in the same place, thus merging at the first frame :rainbow: 

Hey, that means the merging works :tada: !
