### ISSUE TITLE
Program still crashes when merging two tiles

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#239]
**To Reproduce**
1. Run the code (from a version that has the new tile layout)
2. Click on the grass tile on the right
3. Press 'a'
4. See it crash

**Expected behavior**
I have no idea, but it was caused by 'follow_tile()' before

**Additional context**
The program still crashes when merging certain tiles.

**Comment by richelbilderbeek** [comment]
I think @RafayelGardishyan would like a stab at this :+1:

**Comment by Joshua260403** [comment]
Is this done?

**Comment by RafayelGardishyan** [comment]
This is done, but not merged because of OCLINT

**Comment by RafayelGardishyan** [comment]
Richel, can you fix OCLINT error (See travis build on my branch) on my branch?
I really don't understand that error

**Comment by RafayelGardishyan** [comment]
Richel, !OCLINT doesn't work
