### ISSUE TITLE
Create button

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#242]
**Goal**
Currently, all of the screen just have text, and you have to get to the next screen by pressing space.
There need to be buttons that the user can click on to go to another screen.

**Steps**
1. Create a button class.
2. Give the button some style.
3. Give the button a 'clicked' or 'onclick' function.
4. Add a button to the title screen.

**Alternatives**
Create buttons inside of the screen classes.

**Extra info**
May need to wait on a screen manager to do step 3 & 4.

**Comment by Joshua260403** [comment]
@richelbilderbeek would you agree to a button class?

**Comment by richelbilderbeek** [comment]
Yes, I agree! It will be a good exercise in class design as well! Go ahead and build it. I suggest to name it `sfml_button`.

Tip: look at std::function to let the button do any )member) function when clicked :+1:

**Comment by Joshua260403** [comment]
@martje127 tested this, but didn't close it.
