### ISSUE TITLE
About screen crashes

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#243]
**Describe the bug**

When running Nature Zen with `--about` the program crashes

**To Reproduce**

1. Go to the Project Tab (CTRL+5), `Run`  and use `--about` as the command line argument

![2018-11-30-175356_1920x1056_scrot](https://user-images.githubusercontent.com/2098230/49303034-f5d7d780-f4c8-11e8-8dbb-60d0df0870ae.png)

2. Run. Error is show at the bottom of the screen

![2018-11-30-175428_1920x1056_scrot](https://user-images.githubusercontent.com/2098230/49303060-038d5d00-f4c9-11e8-8719-d04e3491a0c2.png)

**Expected behavior**

It should show an About screen

**Screenshots**

See above.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: Lubuntu 17.10
 - SFML version: 2.5

**Additional context**

Apparently, the resource cannot be found.

**Comment by robkruger** [comment]
There were 2 fonts, font.ttf and zen_font.ttf. I used font.ttf because it was more readible.
