### ISSUE TITLE
Add more merge types

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#244]
**Is your feature request related to a problem? Please describe.**

The function `get_merge_type` returns the values of two types merging.

This is also tested:

```
    // merging of types
    assert(get_merge_type(tile_type::grassland, tile_type::grassland) == tile_type::mountains);
    assert(get_merge_type(tile_type::grassland, tile_type::desert) == tile_type::savannah);
    assert(get_merge_type(tile_type::desert, tile_type::grassland) == tile_type::savannah);
```

**Describe the solution you'd like**

 * Add tests for extra merged types.
 * Also add these as tests

**Describe alternatives you've considered**

None.

**Additional context**

Just get it to work. We'll make it smarter later, by re-opening #187.

**Comment by same-drenth** [comment]
Tile types:
grassland
mountains = grass + grass > hills + hills
ocean
savannah = gass + desert
arctic
desert
swamp; ocean + grass > lake + grass
woods

*Lake
*mangrove: 
beavers and alligatorrrrs 
and snapping turdle, = lake + woods
?landscape
*beach = dessert + lake/ ocean
*hills 
*dunes = hills + beach
*

**Comment by same-drenth** [comment]
Tile type update

**Core tiles**
- grassland
- desert
- water
- woods

hills = grass + grass
mountains = hills + hills
savannah = gass + desert
arctic =  water + mountains
swamp = water + grass; mangrove + grass 
mangrove = water + woods
beach = dessert + water; dunes + water
dunes = hills + beach
rain_forrest = woods + woods
tundra = savannah + arctic

**Comment by same-drenth** [comment]
![image](https://user-images.githubusercontent.com/12864136/51059467-9a7f2600-15ec-11e9-85e5-216ea38b9e88.png)

**Comment by richelbilderbeek** [comment]
When Issues #353 and #354 are closed, uncomment the tests in 

```c++
void test_tile_type()
{
  {
    // merging of types
    assert(get_merge_type(tile_type::nonetile, tile_type::grassland) == tile_type::nonetile);
    // here
  }
}
```

**Comment by richelbilderbeek** [comment]
This Issue has gotten stale, closing it.
