### ISSUE TITLE
Make 'tile_contains' a free function

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#246]
Depends on:

 * [ ] #522 

**Is your feature request related to a problem? Please describe.**

Currenty, `tile_contains` is a member function of `tile`:

```
class tile
{
  //...

  bool tile_contains(double x, double y) const noexcept;

  //...
};
```

Because a tile already has a `get_x/y/width/height`, we can get all information we need to make this a free function. Do so.

The tests are now:

```c++
#define FIX_ISSUE_116_TILE_CONTAINS
#ifdef FIX_ISSUE_116_TILE_CONTAINS
  //
  //
  //   (0,0)------(100,0)
  //     |           |
  //     |     A     |     B
  //     |           |
  //   (0,100)-----(100,100)
  //
  //           C           D
  {
    const tile t(0.0, 0.0, 0.0, 1, 1, tile_type::grassland, 0);
    assert(t.tile_contains(50, 50));   // A
    assert(!t.tile_contains(165, 50));  // B
    assert(!t.tile_contains(50, 165)); // C
    assert(!t.tile_contains(165, 165)); // D
  }
#endif // FIX_ISSUE_116_TILE_CONTAINS

  //#define FIX_ISSUE_246
  #ifdef FIX_ISSUE_246
  //
  //
  //   (0,0)------(100,0)
  //     |           |
  //     |     A     |     B
  //     |           |
  //   (0,100)-----(100,100)
  //
  //           C           D
  {
    const tile t(0.0, 0.0, 0.0, 1, 1, tile_type::grassland, 0);
    assert(contains(t, 50, 50));   // A
    assert(!contains(165, 50));  // B
    assert(!contains(50, 165)); // C
    assert(!contains(165, 165)); // D
  }
  #endif // FIX_ISSUE_246
```

You can remove the older tests of Issue 116.

Remove the preprocessor statements when done.

**Describe the solution you'd like**

None.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
OCLINT, our good friend, is complaining again:
/home/travis/build/richelbilderbeek/djog_unos_2018/agent_type.cpp:77:3: constant conditional operator [basic|P2] 
/home/travis/build/richelbilderbeek/djog_unos_2018/agent_type.cpp:89:3: constant conditional operator [basic|P2] 
/home/travis/build/richelbilderbeek/djog_unos_2018/agent_type.cpp:108:10: unnecessary else statement [redundant|P3] 
/home/travis/build/richelbilderbeek/djog_unos_2018/agent_type.cpp:107:5: redundant if statement [redundant|P3] 
/home/travis/build/richelbilderbeek/djog_unos_2018/sfml_game.cpp:140:3: too few branches in switch statement [convention|P3] 
/home/travis/build/richelbilderbeek/djog_unos_2018/tile_type.cpp:159:10: unnecessary else statement [redundant|P3] 
/home/travis/build/richelbilderbeek/djog_unos_2018/tile_type.cpp:158:5: redundant if statement [redundant|P3]

**Comment by Joshua260403** [comment]
Let's free @EllyJet of this issue, time to move on!

**Comment by richelbilderbeek** [comment]
You did it @martje127! It's even already merged to develop!

Closing this Issue...

**Comment by richelbilderbeek** [comment]
It worked, as long as a `tile` constructor worked as expected (#522).

Re-opening the Issues.
