### ISSUE TITLE
Visualize zen

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#247]
**Is your feature request related to a problem? Please describe.**

The current score is dull. 

**Describe the solution you'd like**

As @same-drenth how he wants to have it visualized instead. Then do so.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by same-drenth** [comment]
I was thinking about a bar on the top of the screen that has chaos on one side and 'pure zen' on the other side, so the objective is to hold the level in the middle of the bar.

**Comment by martje127** [comment]
there is a zen logo
