### ISSUE TITLE
Vote on water tile type

### ISSUE THREAD

**Issue by same-drenth** [richelbilderbeek/djog_unos_2018#250]
I have an idea about the water tile type but I want your opinion on the matter. 
Do you want to keep it to only ocean? 
Or do you want to change it to (what I think could be handy) Ocean and lake? 
Or do you want to make it simpler and change it to water?

**Comment by Joshua260403** [comment]
I think the water tile should have a tile specific property indicating how deep the water is. Certain agents can only move to waters with certain depths, for example:
Agent | Minimum depth | Maximum depth
---|---|---
Crocodile | 0 | 10
Cow | 0 | 5
Shark | 10 | 35
Whale | 15 | 35
Fish | 5 | 35

**Comment by richelbilderbeek** [comment]
Made high priority, as other Issues depend on it and I want the voting to be done this year.

**Comment by robkruger** [comment]
> I would have a system consisting of:
> Shallow Fresh Water
> Deep Fresh Water
> Shallow Brackish Water
> Deep Brackish Water
> Shallow Sea Water
> Deep Sea Water
> 2 depth modes and 3 salinity modes.
> Not all fish and other marine life can survive in all the salinities and furthermore, some land animals never wander into any water tile.

I think this is the best idea.

**Comment by EllyJet** [comment]
> I think the water tile should have a tile specific property indicating how deep the water is. Certain agents can only move to waters with certain depths, for example:
> 
> Agent	Minimum depth	Maximum depth
> Crocodile	0	10
> Cow	0	5
> Shark	10	35
> Whale	15	35
> Fish	5	35
> The deeper the water the darker the color of the tile

I agree, this way there is a visual cue to the player as to what kind of water it is

**Comment by Fsetrodinomo** [comment]
Is it possible to combine the suggestion from richel and Joshua ?

**Comment by annehinrichs22** [comment]
> I would have a system consisting of:
> Shallow Fresh Water
> Deep Fresh Water
> Shallow Brackish Water
> Deep Brackish Water
> Shallow Sea Water
> Deep Sea Water
> 2 depth modes and 3 salinity modes.
> Not all fish and other marine life can survive in all the salinities and furthermore, some land animals never wander into any water tile.

I agree. I think the most complicated option is always the best because this adds interestedness to the game and makes it more like a simulator.

**Comment by same-drenth** [comment]
I think that Jan's suggestion is a bit too complicated for now but the other ideas combined gave me an idea for how to represent it visually. The lines seen on maps to represent depth.
![image](https://user-images.githubusercontent.com/12864136/49671364-e11ab700-fa67-11e8-957a-585796b1082d.png)
With these blue gradients. 
![image](https://user-images.githubusercontent.com/12864136/49671178-4c17be00-fa67-11e8-804a-6324a4a02571.png)

**Comment by Joshua260403** [comment]
What's the deadline on this?

**Comment by Rijk-van-Putten** [comment]
Idea|Proposed by|Vote
---|---|---
Types (simple)|Richel|Y
Types (complex)|Jan|N
Tile depth variable|Joshua|N
Depth lines|Same|N

**Comment by annehinrichs22** [comment]
Idea | Proposed by | Vote
-- | -- | --
Types (simple) | Richel | N
Types (complex) | Jan | Y
Tile depth variable | Joshua | Y
Depth lines | Same | Y

**Comment by Tomstuivenga** [comment]
Idea | Proposed by | Vote
-- | -- | --
Types (simple) | Richel | N
Types (complex) | Jan | N
Tile depth variable | Joshua | Y
Depth lines | Same | N

**Comment by JolienGay** [comment]
Idea|Proposed by|Vote
---|---|---
Types (simple)|Richel|N
Types (complex)|Jan|N
Tile depth variable|Joshua|Y
Depth lines|Same|Y

**Comment by robkruger** [comment]
Idea | Proposed by | Vote
-- | -- | --
Types (simple) | Richel | N
Types (complex) | Jan | Y
Tile depth variable | Joshua | N
Depth lines | Same | N
