### ISSUE TITLE
Doubles end with .0

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#251]
**Is your feature request related to a problem? Please describe.**

The agent class has this constructor:

```
  agent(const agent_type type, const double x = 0, const double y = 0);
```

As a double is a floating point value, it should be

```
  agent(const agent_type type, const double x = 0.0, const double y = 0.0);
```

**Describe the solution you'd like**

Replace the zeroes by `0.0`.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Fsetrodinomo** [comment]
Done
