### ISSUE TITLE
Delete game::add_agent member function

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#255]
**Is your feature request related to a problem? Please describe.**

`game` has a member function called `add_agent`. It is never used.

**Describe the solution you'd like**

Remove its declaration (in the header) and its definition (in the implementation file).

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
I think it should stay. It is not used _yet_, but i think it will be in the future.

**Comment by richelbilderbeek** [comment]
Thanks for your ideas!

>  It is not used yet, but i think it will be in the future

There is an acronym for this: YAGNI, see [the Wikipedia page about YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it) for references. Following these principles, we will delete this function for now. 

We will see in which shape this function will reincarnate :rainbow:
