### ISSUE TITLE
Votes and Suggests

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#259]
@richelbilderbeek we'll have to make sure everybody knows this exists, but it seems like the misc column was removed, and there's to many people to assign everyone. I suggest we address the suggest and vote issues at the start of an evening.

**Comment by richelbilderbeek** [comment]
Good idea: I will write the 'Vote and Suggests' on the whiteboard both these days and explicitly mention it to all Team Octane members.

I indeed removed the 'Misc' column as it was empty.

**Comment by richelbilderbeek** [comment]
Close this Issue, as I just put this in my lesson plan. I hope the others help me remind if I forget to tell the team about suggestions in the future.
