### ISSUE TITLE
Tiles not merging

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#268]
**The bug**

When merging two tiles that are not both grassland the tile moves but it doesn't get merged.

**How to reproduce**
1. select the desert tile
2. press w

**Hypothesis**
The merge_tiles function in game.cpp is incorrect.

**Extra info**
- First run: N
- Tried cleaning: N
- Tried deleting build: N
- Tried to fix: N
- Added asserts: N
- Used breakpoints: N

**Comment by Joshua260403** [comment]
I believe i found the problem. It doesn't have anything to do with floating point precision or stuff like that, rather with the merge_tiles exiting early.

**Comment by richelbilderbeek** [comment]
Well done!

**Comment by Joshua260403** [comment]
So OClint was right about the early return!

**Comment by richelbilderbeek** [comment]
@janderkkotlarski: can this Issue be closed?

**Comment by richelbilderbeek** [comment]
I've seen tiles merging!

Closing this Issue :1st_place_medal:
