### ISSUE TITLE
Add bird agent

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#274]
**Is your feature request related to a problem? Please describe.**

We need a bird agent.

**Describe the solution you'd like**

Create a bird agent and visualize it.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by richelbilderbeek** [comment]
Bird sprite is added in `resources`, someone else can take over if he/she wants to :+1:

**Comment by martje127** [comment]
there is a bird
