### ISSUE TITLE
Rename tile_type::ocean to tile_type::water

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#275]
**Is your feature request related to a problem? Please describe.**

We voted for a variable-depth water tile (#250).  

**Describe the solution you'd like**

Rename the only water-type tile to `water`.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
Not done, good thing i set up appveyor cus travis had an error
