### ISSUE TITLE
An agent is removed if health is below zero

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#285]
**Is your feature request related to a problem? Please describe.**

Currently, agents have health, but nothing is done with it.

**Describe the solution you'd like**

Remove agents that have health below zero.

There is a test that checks if a starved cow is indeed removed:

```c++
  //#define FIX_ISSUE_285
  #ifdef FIX_ISSUE_285
  //An agent must be removed if health is below zero
  {
    game g(create_default_tiles(), { agent(agent_type::cow) } );
    assert(!g.get_agents().empty());
    // Wait until cow starves
    while (!g.get_agents().empty())
    {
      g.process_events();
    }
  }
  #endif
```

Note that the tests will freeze the program if the cow does not starve, which is #287!

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by martje127** [comment]
the agents are removed if there health is below zero
