### ISSUE TITLE
A cow must starve if the only agent

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#287]
**Is your feature request related to a problem? Please describe.**

Currently, cows have health, but they do not starve yet.

**Describe the solution you'd like**

Cows must starve if they are alone in the world.

This test must pass:

```c++
  //#define FIX_ISSUE_287
  #ifdef FIX_ISSUE_287
  //A cow must starve if alone
  {
    game g(create_default_tiles(), { agent(agent_type::cow) } );
    assert(!g.get_agents().empty());
    const auto health_before = g.get_agents()[0].get_health();
    // Starve one turn
    g.process_events();
    const auto health_after = g.get_agents()[0].get_health();
    assert(health_after < health_before);
  }
  #endif
```

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
That must mean you broke it, because this works for me

**Comment by Joshua260403** [comment]
Go ahead then

**Comment by Joshua260403** [comment]
wait no, im actually working in the same function

**Comment by Joshua260403** [comment]
this works for me. @richelbilderbeek could it be that rob has less ram qt creator is allowed to use

**Comment by Joshua260403** [comment]
@richelbilderbeek does this have to do with the memory thing rob has?

Btw, windows automaticly sets the max ram a program can use for most programs, ill look for a max memory setting

**Comment by Joshua260403** [comment]
no setting in qt, but on the internet i found out that by default windows gives 2 GB available

**Comment by robkruger** [comment]
It works perfectly now without changing anything, weird...

**Comment by Joshua260403** [comment]
I fixed it

Op za 26 jan. 2019 16:40 schreef robkruger <notifications@github.com:

**Comment by robkruger** [comment]
O

**Comment by robkruger** [comment]
Ah

**Comment by richelbilderbeek** [comment]
Re-open the Issue, as it broke again.
