### ISSUE TITLE
grass grows

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#288]
**Is your feature request related to a problem? Please describe.**

Currently, grass has a stable health. It should increase each turn (as the sun is always shining).

There is a test for this:

```
  //#define FIX_ISSUE_288
  #ifdef FIX_ISSUE_288
  //Grass grows
  {
    game g(create_default_tiles(), { agent(agent_type::grass) } );
    assert(!g.get_agents().empty());
    const auto health_before = g.get_agents()[0].get_health();
    // Grow one turn
    g.process_events();
    const auto health_after = g.get_agents()[0].get_health();
    assert(health_after > health_before);
  }
  #endif
```

**Describe the solution you'd like**

Grass should increase in health when nothing happens.

**Describe alternatives you've considered**

None.

**Additional context**

 * We do assume the sun is always shining 
 * Grass will duplicate in the future

**Comment by Joshua260403** [comment]
Actually, im going to have to reopen this. You made the first agent in the list of agents grow in health, not every grass agent... Also using `get_agents()[0]` will probably give errors at some point in time when theres no agents at all on the screen.
