### ISSUE TITLE
Agent can pass out of exhaustion

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#289]
When an agent doesn't have anymore stamina, he/she should pass out.

Make it so when an agent's stamina is 0, the agent stops moving.

**Comment by richelbilderbeek** [comment]
@Joshua260403: Yes, you are right, when it's about :rainbow: health :rainbow:. This issue, however is about stamina. Well, we all get confused once in a while, keep up the good job :+1:.
