### ISSUE TITLE
Implement screen manager

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#294]
I also think this speaks for itself

**Comment by richelbilderbeek** [comment]
I agree that we need one, yet am unsure about the timing: we do not have options, so we don't need an options screen yet.

On the other hand, if a medior wants to do this, I will approve this.

**Comment by Joshua260403** [comment]
@richelbilderbeek could you help with something, travis has problems with the video mode

**Comment by richelbilderbeek** [comment]
@Joshua260403: indeed, Travis CI does only emulate a screen. I've observed that using full-screen crashes on Travis. A fixed screen resolution like we have now works fine.

Does that help?

**Comment by Joshua260403** [comment]
So it could be getDesktopMode causing the issues

Op wo 16 jan. 2019 17:44 schreef Richel Bilderbeek <notifications@github.com
:

**Comment by richelbilderbeek** [comment]
Sounds like perfectly valid hypothesis!

**Comment by Joshua260403** [comment]
Bonus: the screen is resize-able ⭐⭐⭐

**Comment by Joshua260403** [comment]
@richelbilderbeek ![screenshot](https://snag.gy/rfWTdp.jpg)

**Comment by Joshua260403** [comment]
That's october till now

**Comment by richelbilderbeek** [comment]
I hope you'll show this in the end presentation to the parents. It will compliment the both of us!
