### ISSUE TITLE
Remove useless #defines

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#299]
**Is your feature request related to a problem? Please describe.**

Tests are typically switched on and of using preprocessor directives:

```c++
//#define FIX_ISSUE_X
#ifdef FIX_ISSUE_X
// tests here
#endif //FIX_ISSUE_X
```

If the `FIX_ISSUE_X` is defined and the test pass, the preprocessor directives can be removed, leaving only:

```c++
// tests here
```

**Describe the solution you'd like**

Please do so, just search for `  #define` (with two spaces in front of it)

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
Is @JolienGay doing this one? If so, please assign yourself.

**Comment by Joshua260403** [comment]
I will assign @JolienGay to prevent this issue from being done twice

**Comment by JolienGay** [comment]
I've done some of the redundant #defines but could not finish all in time. Please reinstate this issue next week friday for JolienGay. Thanks!

**Comment by richelbilderbeek** [comment]
Will move Issue back :rainbow: so I hope you'll continue this good work.

Note that the defines for #300 must be put back, as the tests appear to fail :+1:

**Comment by JolienGay** [comment]
Shall I use develop or your repository this time to pull? Also, is it
normal that the game currently does not start?

**Comment by richelbilderbeek** [comment]
As a general rule, use `develop`.

Indeed, the game crashes now (#322) and I am working on it now. I'll email when things work fine again :+1:

**Comment by JolienGay** [comment]
Oh ok, ignore the question about qt in my mail then. Thanks for the reply!

**Comment by richelbilderbeek** [comment]
It's fixed (p = 99%)!

**Comment by JolienGay** [comment]
The useless defines of #204 and #303 have been removed. Sorry for not finishing putting #300 back earlier, I had to do a school task first.

Quick question though: I had to search for '  #defines' (with 2 spaces before #). Why exactly? Only 2 issues showed up there, but without the spaces many more. Does this mean I don't have to check tests of other issues?

**Comment by richelbilderbeek** [comment]
> Quick question though: I had to search for ' #defines' (with 2 spaces before #). 
> Why exactly? Only 2 issues showed up there, but without the spaces many more.

@JolienGay: 

Because the following is a test that is working:

```
  #define SOMETHING
  //...
  #endif
```

and because the following is a test that is not yet working:

```
  //#define SOMETHING
  //...
  #endif
```

Thanks for the help, closing this Issue :+1:

**Comment by richelbilderbeek** [comment]
Opening up this one, we need another junior to clean up the mess we made :smirk:
