### ISSUE TITLE
Vote which game we'll make on Wednesday september 12th

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#3]
At Tuesday September 11th night, I will place all suggestions that I think are realistic from #2 here. 
On Wednesday september 12th, put your votes here. We'll pick the game with most votes. Upon equal votes, I pick.

**Comment by richelbilderbeek** [comment]
Time to vote:

 1. [FlatWorld](https://github.com/richelbilderbeek/djog_unos_2018/issues/2#issuecomment-419531628)
 2. [Nature Zen](https://github.com/richelbilderbeek/djog_unos_2018/issues/2#issuecomment-420010313)
 3. [Mini Metro](https://github.com/richelbilderbeek/djog_unos_2018/issues/2#issuecomment-420165036)
 4. [This War Of Mine](https://github.com/richelbilderbeek/djog_unos_2018/issues/2#issuecomment-420275468)

Please cast your votes for each game. You can cast zero to and including four votes. Game we will make will be the one with the most 'Yes'ses.

Vote for example like this:

Name|1|2|3|4
---|---|---|---|---
`example`|Y|N|Y|N

Deadline Wednesday September 12th 23:59.

**Comment by richelbilderbeek** [comment]
Name|1|2|3|4
---|---|---|---|---
`richelbilderbeek`|N|Y|N|Y

**Comment by Joshua260403** [comment]
Name | 1 | 2 | 3 | 4
-------|---|---|---|--
`Joshua260403` | Y | Y | N | N

**Comment by RafayelGardishyan** [comment]
Name|1|2|3|4
---|---|---|---|---
`RafayelGardishyan`|N|Y|N|N

**Comment by annehinrichs22** [comment]
Name | 1 | 2 | 3 | 4
-- | -- | -- | -- | --
`annehinrichs22` | N | Y | Y | N

**Comment by Rijk-van-Putten** [comment]
Rijk-van-Putten
1 2 3 4
N N Y Y

**Comment by same-drenth** [comment]
Name | 1 | 2 | 3 | 4
-- | -- | -- | -- | --
same-drenth | Y | N | N | Y

**Comment by richelbilderbeek** [comment]
Name | 1 | 2 | 3 | 4
-- | -- | -- | -- | --
Mart | N | N | N | Y

**Comment by richelbilderbeek** [comment]
Voting is done!

Name | 1 | 2 | 3 | 4
-- | -- | -- | -- | --
Total | 2 | 4 | 2 | 4

Draw!

My voting counting double results in: Nature Zen!

**Comment by richelbilderbeek** [comment]
# [Nature Zen](https://github.com/richelbilderbeek/djog_unos_2018/issues/2#issuecomment-420010313)!

**Comment by richelbilderbeek** [comment]
![Image of the prototype](https://github.com/richelbilderbeek/djog_unos_2018/raw/master/pics/IMG_20180907_215839.jpg)

# Nature Zen

A game which consists of tiles that look like coth. (See picture.)
In this game, the different patterns on the cloth represent different types of worlds, such as forests, cities, oceans, rivers, mountains.

### Main Features (Not everything)
- The player can move these tiles to alter the world and the creatures who live on it.
- The player can interact with the creatures, for example, kill them, send them to a different location etc.
- On the bottom of the world, there is a 'dark side' and the player can turn each tile over to reveal the dark side and maybe harm the creatures on top in some way.
- The world's amount of tiles is finite but gradually increasing, the empty places consist of an endless pit the creatures can fall in. (A finite amount of tiles is handy to make it less complicated for the player to move the tiles.)

### Extra Features
- The player can zoom in on a tile and see more tiles on that tile
- Create enemies: People (Because the game is about the "Nature Zen")
- More detailed worlds with planets etc.
- Draw graphics

### Credits
Idea by:
- Rafayel Gardishyan
- Anne Hinrichs
- A little bit by Joshua van Waardenberg and Richel Bilderbeek

###### More ideas are welcome in the comments
