### ISSUE TITLE
Suggest what moves on the tiles

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#30]
**Is your feature request related to a problem? Please describe.**

A game with only land tiles is boring. We need something to walk on it.

**Describe the solution you'd like**

I would like some suggestions what can walk on the tiles.

**Describe alternatives you've considered**

None.

**Additional context**

 * After closing #19 'Create first world part', an Issue will be created to add a first creature. This may just be a circle for starters. As long as it is something that moves.
 * After that, we'll pick the best idea from this Issue

**Comment by RafayelGardishyan** [comment]
Little animals, clouds, cars, lights in the city, sun?

**Comment by Joshua260403** [comment]
Little people (when a tile turned) and (wild) animals

**Comment by richelbilderbeek** [comment]
I think it would be fun to add:

 * plants and underwater plants that grow as food for herbivores
 * herbivores like cows, fishes and herbivorous birds to eat the plants
 * carnivores like sharks, tigers, bears and carnivorous birds to eat the herbivores

Of course, fishes can only stay within a water tile (or fall off, into the abyss). This means that bears (that can also eat fish) can only eat those fish if their land tile is adjacent to a water tile. Birds can fly around freely, but if tired, will fall in the abyss.

I do not think we should actually model the species after real-word animals, but I do suggest a food web.

**Comment by Joshua260403** [comment]
And of course other custom species

Op wo 26 sep. 2018 21:48 schreef Joshua van Waardenberg <
joshuavwaardenberg@gmail.com>:

**Comment by Joshua260403** [comment]
Do you mean we create our own apex predator?

Op wo 26 sep. 2018 21:06 schreef Richel Bilderbeek <notifications@github.com

**Comment by richelbilderbeek** [comment]
> Do you mean we create our own apex predator?

That is part of my suggestion, yes :eagle:

**Comment by richelbilderbeek** [comment]
I feel this Issue is getting old. I just close it.
