### ISSUE TITLE
Grass creates new grass

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#300]
**Is your feature request related to a problem? Please describe.**

Currently, grass just grows, but does not create new grasses.

**Describe the solution you'd like**

After a while, a grass agent should create a new grass agent.

Or, this test should pass:

```c++
  //#define FIX_ISSUE_300
  #ifdef FIX_ISSUE_300
  //Grass creates new grasses
  {
    game g(create_default_tiles(), { agent(agent_type::grass) } );
    assert(g.get_agents().size() == 1);
    while (g.get_agents().size() == 1) //Wait until grass procreates
    {
      g.process_events();
    }
    assert(g.get_agents()[0].get_type() == agent_type::grass);
    assert(g.get_agents()[1].get_type() == agent_type::grass);
  }
  #endif //FIX_ISSUE_300
```

**Describe alternatives you've considered**

None.

**Additional context**

Running the test now will freeze the game.

**Comment by richelbilderbeek** [comment]
@janderkkotlarski: you did it! It is fixed, well done :+1:

**Comment by richelbilderbeek** [comment]
Hmmm, the test does not pass. Please make it so :+1:

**Comment by Joshua260403** [comment]
So do i merge rob into develop? Please don't unassign after doing an issue.

**Comment by Joshua260403** [comment]
@robkruger @richelbilderbeek Rob's branch is the same as develop! What went wrong?

**Comment by robkruger** [comment]
I didn't change anything, that's why I unassigned

**Comment by Joshua260403** [comment]
Ok so this is on jan's branch
