### ISSUE TITLE
Cows eat grass

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#301]
**Is your feature request related to a problem? Please describe.**

Current, cow and grass agents ignore each other.

**Describe the solution you'd like**

When cow and grass are at the same position,

 * the grass should decrease in health, as it is eaten
 * a cow should increase in health, as it is eating

Or, fix this test:

```c++
  //#define FIX_ISSUE_301
  #ifdef FIX_ISSUE_301
  //Cows eat grass
  {
    const double cow_health{10.0};
    const double grass_health{5.0};
    game g(
      create_default_tiles(),
      {
        agent(agent_type::grass, 0.0, 0.0, grass_health),
        agent(agent_type::cow  , 0.0, 0.0, cow_health)
      }
    );
    assert(g.get_agents()[0].get_health() == grass_health);
    assert(g.get_agents()[1].get_health() == cow_health);
    g.process_events();
    //Grass is eaten ...
    assert(g.get_agents()[0].get_health() < grass_health);
    //Cow is fed ...
    assert(g.get_agents()[1].get_health() > cow_health);
  }
  #endif //FIX_ISSUE_301
```

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
This was already added with agent can starve, better luck next issue 🍀 🍀 🍀

**Comment by richelbilderbeek** [comment]
Test fails now. I've renamed it to `FIX_ISSUE_301` again.
