### ISSUE TITLE
Score decreases when an agent dies

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#302]
**Is your feature request related to a problem? Please describe.**

Currently, the score is not changed.

**Describe the solution you'd like*

When an agent dies, score should decrease.

Or, this test must pass:

```c++
  //#define FIX_ISSUE_302
  #ifdef FIX_ISSUE_302
  //When an agent dies, score must decrease
  //Depends on #285
  {
    game g(create_default_tiles(), { agent(agent_type::cow) } );
    assert(!g.get_agents().empty());
    double prev_score = g.get_score();
    // Wait until cow starves
    while (!g.get_agents().empty())
    {
      g.process_events();
      prev_score = g.get_score();
    }
    const double new_score = g.get_score();
    assert(new_score < prev_score);
  }
  #endif //FIX_ISSUE_302
```

**Describe alternatives you've considered**

None.

**Additional context**

Depends on #285, will freeze if that Issue is not fixed.

**Comment by robkruger** [comment]
I changed the test, because prev_score was given the decreased value because the line was after the call to process_events() and thus kill_agents().

**Comment by richelbilderbeek** [comment]
@robkruger: good thinking to change that test!

**Comment by martje127** [comment]
the 302 test is away and the code seem to works becasue de picture on the top is going left
