### ISSUE TITLE
Agents must follow the movement of the tile they are on

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#304]
**Is your feature request related to a problem? Please describe.**

Currently, the agents move indendent of the tiles. 

**Describe the solution you'd like**

When a tile moves with an agent on it, the agent should be dragged along with it.

Or, this test must pass:

```c++
  //#define FIX_ISSUE_304
  #ifdef FIX_ISSUE_304
  //Agents must follow the movement of the tile they are on
  {
    //Put a cow on a grass tile, then move tile down and rightwards
    const double start_cow_x = 1.0;
    const double start_cow_y = 1.0;
    game g(
      { tile(0.0, 0.0, 0.0, 10.0, 10.0) },
      { agent(agent_type::cow, start_cow_x, start_cow_y) }
    );
    tile& tile = g.get_tiles()[0];
    tile.set_dx(1.0);
    tile.set_dy(1.0);
    g.process_events();
    assert(g.get_agents()[0].get_x() > start_cow_x);
    assert(g.get_agents()[0].get_y() > start_cow_y);
  }
  #endif //FIX_ISSUE_304
```

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by robkruger** [comment]
programs has to be progress obviously

**Comment by Joshua260403** [comment]
Oh wow this is great!

**Comment by Joshua260403** [comment]
:+1: 🍀

**Comment by Joshua260403** [comment]
Remember to reopen this if you are going to improve it!

**Comment by martje127** [comment]
the agents folow the tile wehn the are on the tile
