### ISSUE TITLE
Trees grow

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#305]
**Is your feature request related to a problem? Please describe.**

Currently, trees have a stable health. It should increase each turn (as the sun is always shining).

**Describe the solution you'd like**

Trees should increase in health when nothing happens.

There is a test for this:

```c++
  //#define FIX_ISSUE_305
  #ifdef FIX_ISSUE_305
  //Trees grow
  {
    game g(create_default_tiles(), { agent(agent_type::tree) } );
    assert(!g.get_agents().empty());
    const auto health_before = g.get_agents()[0].get_health();
    // Grow one turn
    g.process_events();
    const auto health_after = g.get_agents()[0].get_health();
    assert(health_after > health_before);
  }
  #endif // FIX_ISSUE_305

```

**Describe alternatives you've considered**

None.

**Additional context**

 * We do assume the sun is always shining 
 * Trees will duplicate in the future

**Comment by Joshua260403** [comment]
this is done......
