### ISSUE TITLE
Tile movement physics

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#31]
**Is your feature request related to a problem? Please describe.**

Moving a tile by mouse cursor or keyboard inputs should follow the laws of physics: smaller tiles should respond swifter than big tiles.

**Describe the solution you'd like**

When moving a tile by mouse cursor or keyboard inputs smaller tiles should respond swifter than big tiles.

**Describe alternatives you've considered**

None.

**Additional context**

Must be done after #19 ('Create first world part')

**Comment by richelbilderbeek** [comment]
I suggest to let @annehinrichs22 or @Joshua260403 do this. Sure I will help. The one who assigns himself first gets the job :+1:

**Comment by richelbilderbeek** [comment]
You got the job :+1: (after #19 ('Create first world tile') has been finished)!

**Comment by richelbilderbeek** [comment]
We share the same idea hear. As implementer of this, you have some freedom to do it any way you like it. Of course, there is a risk someone disagrees, but I predict that chance is slim.

**Comment by Joshua260403** [comment]
First i will need to get either some onclick function into the object or the object into the onclick section, both dont seem easy

**Comment by richelbilderbeek** [comment]
@Joshua260403 I've improved the architecture. 

This Issue is/was about two things:

 * #86 : select a tile by clicking left mouse button
 * #87 : set tile speed

Because an Issue must have one specific goal, I will close this one.
