### ISSUE TITLE
Document: don't use `fix #XXX` in commit name

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#312]
**[edit by @richelbilderbeek]**

To quote @Joshua260403:

> Stop using `fix #XXX` in commit names so they don't get closed before testing.

This should be documented at the `git` pages, instead using `progress #XXX` should be preferred. Mentioning the Issue is useful in finding back the commits that worked on the Issue.

**Comment by richelbilderbeek** [comment]
Valid point! The `fix #xxx` is a nice idiom, but we merge builds that pass with `master` too easy. I will use `progress #xxx` myself now instead.

**Comment by JolienGay** [comment]
Added documentation in git.md, I hope I understood this correctly and it is what was intended.

**Comment by richelbilderbeek** [comment]
Well done, exactly what I hoped for :+1:

Closing the Issue :rainbow:
