### ISSUE TITLE
Must not be able to deselect a tile while it is moving

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#314]
And also tile movement has to move to game instead of sfml_game.

For the people who don't know: the bug is that you can deselect a tile while it's moving to stop it mid movement and misplace it.

**Comment by Joshua260403** [comment]
@richelbilderbeek i was working on a project of my own when i found this:
https://github.com/codecov/example-cpp11
https://docs.codecov.io/docs/supported-languages (C++11)

**Comment by richelbilderbeek** [comment]
I will free up this Issue for the devs of tonight :rainbow:
