### ISSUE TITLE
Agents must not be pushed off tile

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#317]
**Is your feature request related to a problem? Please describe.**

Currently, agents are pushed off a tile when two tiles merge:

![1](https://user-images.githubusercontent.com/2098230/51624296-c8446300-1f3a-11e9-94d1-b52a54956e7d.png)

The ones being pushed off are the agents on the non-moving tile.

**Describe the solution you'd like**

I would like the agents on the non-moving tile to not be pushed off.

**Describe alternatives you've considered**

None.

**Additional context**

There is a test in `game.cpp:

```c++
void test_game()
{
  //...

  //Agents must not be pushed off their tile, #317
  {
    //Put a grass agent on a grass tile,
    //then move another tile on it
    const double start_grass_x = 1.0;
    const double start_grass_y = 1.0;
    game g(
      {
        tile(-10.0, -10.0, 0.0, 10.0, 10.0), // Left tile that will move to right
        tile(  0.0,   0.0, 0.0, 10.0, 10.0)  // Right tile with cow
      },
      { agent(agent_type::grass, start_grass_x, start_grass_y) }
    );
    tile& tile = g.get_tiles()[0];
    tile.set_dx(1.0);
    tile.set_dy(1.0);
    for (int i=0; i != 10; ++i)
    {
      g.process_events();
    }
    assert(g.get_agents()[0].get_x() == start_grass_x);
    assert(g.get_agents()[0].get_y() == start_grass_y);
  }
}
```

This test works. Apparently, the agents get pushed off by `sfml_game::process_events()`. Move that logic to `game::process_events`.

**Comment by robkruger** [comment]
@richelbilderbeek how do I fix the oclint issue in `game.cpp:152` ?

**Comment by Joshua260403** [comment]
Travis build failing

**Comment by Joshua260403** [comment]
@robkruger use a `return;` in the function to reduce indentation. 
Or simpler: change
```cpp
if (something == idk) {
  code
  code
  code
  code
}
```
to
```cpp
if (something != idk) return;
code
code
code
code
```

**Comment by Joshua260403** [comment]
You'll have to google this one as i have no idea what avoid branching statement as last in loop means

**Comment by robkruger** [comment]
I found and hopefully fixed it

**Comment by Joshua260403** [comment]
@robkruger can i merge this?

**Comment by robkruger** [comment]
Yes

**Comment by Joshua260403** [comment]
And that children, is why you update your own branch before updating 🌱

**Comment by Joshua260403** [comment]
(it broke)

**Comment by robkruger** [comment]
Ah, sorry. I did that now, but everything still works.

**Comment by martje127** [comment]
the code doesn't crash and it works in the game
