### ISSUE TITLE
Arrange default tiles that all merge types are possible

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#318]
**Is your feature request related to a problem? Please describe.**

Currently, we can merge two grasslands. That is the only merge we encounter in practice. In the back, there are four possible merges, as can be seen in `get_merge_type`.

**Describe the solution you'd like**

Arrange the default tiles in such a way we can see all four merged type in the game.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by richelbilderbeek** [comment]
Moved to here, as the Travis build fails. A medior will know what to do here :+1:

**Comment by Joshua260403** [comment]
The tiles at the top are very nice, but i would like the original tiles to 1. not overlap and 2. have the agents on them (the cows are on the top tiles)

Saying this, why don't you reorder all of the tiles (and the agents too).

**Comment by Joshua260403** [comment]
close for now, will get back to this once all merges can be done
