### ISSUE TITLE
Vote on the goal of the game

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#32]
**Is your feature request related to a problem? Please describe.**

Games are more fun if they have a goal.

**Describe the solution you'd like**

Suggest your idea of the goal of the game. During development of it, we may be influenced by this. Or not. In our case, it is an iterative development :rainbow: 

**Describe alternatives you've considered**

None.

**Additional context**

 * There will be a vote one week later. 
 * The goal of the game will not be set in stone: a future vote may overthrow that vote

**Comment by richelbilderbeek** [comment]
@Joshua260403 : I like that idea! I hope you will elaborate, for example, do you suggest that a 'Game Over' is inevitable (like in Dwarf Fortess)? And balance between what?

**Comment by Joshua260403** [comment]
There can be different modes, one without gameover (endless) and for example campaign where you have to keep the zen at a certain level for a certain amount of time

**Comment by RafayelGardishyan** [comment]
And our game has to be saveable

**Comment by richelbilderbeek** [comment]
@RafayelGardishyan: thanks for this suggestion:

> And our game has to be saveable

I created #39 to vote if or in which way the game must be savable.

**Comment by Joshua260403** [comment]
Goal | Vote
---|---
Keep the zen (without game over) | N
Keep the zen (with game over) | Y
Multiple modes | Y
Richel's idea | N

**Comment by richelbilderbeek** [comment]
Not much effect, but ...

Goal | Vote
---|---
Keep the zen (without game over) | Y
Keep the zen (with game over) | Y
Multiple modes (levels and endless) | Y
Richel's idea | Y

**Comment by richelbilderbeek** [comment]
Voting's over! I use my power to pick the simplest, thus most realistic, one:

```
Keep the zen (with game over)
```

So, goal of the game, is to keep the Zen, with Game Over.
