### ISSUE TITLE
Master broke!!!

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#322]
Oh no, it seems like @RafayelGardishyan broke master.

Someone has to fix this asap!

**Comment by richelbilderbeek** [comment]
It appears the game is flooded with agents :grin: 
![2019-01-25-165044_1920x1056_scrot](https://user-images.githubusercontent.com/2098230/51756495-724df780-20c1-11e9-9414-8a5a145caae6.png)

**Comment by richelbilderbeek** [comment]
Well done @richelbilderbeek :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by Joshua260403** [comment]
? :confused:

Op vr 25 jan. 2019 17:12 schreef Richel Bilderbeek <notifications@github.com
:
