### ISSUE TITLE
Grass must grow at a realistic speed

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#324]
**Is your feature request related to a problem? Please describe.**

Currently, the grass grows overly slow (fast growth caused the crash of #322)

**Describe the solution you'd like**

Choose a growth speed as such that grass duplicates approx every 10 seconds.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
STOP, WAIT, NO, HOLD ON
DO NOT make the grass grow faster than 0.005, the speed is currecntly 0.001 and that is very fast in game. Also increasing the speed too much will break the issue i just did (cow eats grass)
Also i just made changes to this
@richelbilderbeek 
@Tomstuivenga

**Comment by Joshua260403** [comment]
I advice to wait for my push to develop, and again, to not increase it too much

**Comment by richelbilderbeek** [comment]
We'll await your work of mastery :angel:

**Comment by Joshua260403** [comment]
Comming right up

**Comment by Joshua260403** [comment]
Done 🍀

**Comment by Tomstuivenga** [comment]
I'll get busy with it! Thanks for the advice on the speed, saved some unnecessary crashes.

**Comment by richelbilderbeek** [comment]
Hmmm, the speed currently on develop is great. 

@Tomstuivenga, I'll close the Issue OK?

**Comment by Tomstuivenga** [comment]
Sure!
