### ISSUE TITLE
Cows walk towards grass iff grass is close

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#326]
**Is your feature request related to a problem? Please describe.**

Currently, agents move around randomly. In reality, cows commonly walk towards grass if it sees grass.

**Describe the solution you'd like**

Make cows walk towards grass iff grass is close.

Follow these steps:

 1. Create a test in `game` that fails. Surround it by preprocessor statements, so other team member can still run their code. Push with commit message `Expose #326` 
  2. Fix the problem. Remove the preprocessor statements. Push with commit message 'Cows walk towards grass iff grass is close, progress #326'
  3. Let it be merged to develop by moving this Issue in the Project page

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by robkruger** [comment]
The test passes local on my laptop, but fails on Travis. Why?

**Comment by richelbilderbeek** [comment]
Merged :shipit:

**Comment by robkruger** [comment]
It's only this test, but again, the test works on my laptop

**Comment by Joshua260403** [comment]
REDO:
Make agents move towards their food iff the food is close.
You should remove the old code for this (located in agent::move) and replace it with new code that uses the can_eat function and uses a limited range

**Comment by Enzo9** [comment]
I think its done, they move towards grass now.

**Comment by martje127** [comment]
cows are walking to gras even if its far away. i hope its posible to set a range the cows can see.

**Comment by martje127** [comment]
I don't see them walking towards grass, maybe the range is too short now. Joshua says you should try a range of around 15 to 20 calculated with the pythagoras theorem.

**Comment by richelbilderbeek** [comment]
Moved to Done, so closing this Issue.
