### ISSUE TITLE
Improve menu screen

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#327]
**Is your feature request related to a problem? Please describe.**

Currently, the menu screen (run with `--menu` looks like this:

![2019-01-25-174507_1722x910_scrot](https://user-images.githubusercontent.com/2098230/51759664-0e2f3180-20c9-11e9-99e1-f80ac883f3e6.png)

**Describe the solution you'd like**

I would like the menu screen:

 * display 'Nature Zen' at the top
 * have a 'Start' button
 * have an 'About' button
 * have a 'Quit' button
 * have even prettier colors

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
thats not what it should look like, would you like me to do the repositioning together with the game over screen

**Comment by Joshua260403** [comment]
For the person who does this, all that has to be done is change positions and maybe change the colors. This is all done in display. Also if there is a set origin somewhere in the menu screen class, remove it.

**Comment by Joshua260403** [comment]
@richelbilderbeek a menu screen actually does not have a big title at the top, that would make it a second title screen which it is not.
