### ISSUE TITLE
Make about screen work

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#328]
**Is your feature request related to a problem? Please describe.**

Currently, when running Nature Zen with `--about`, the program crashes.

**Describe the solution you'd like**

When running Nature Zen with `--about`, the program should show an about screen.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
Doesn't crash on windows i don't think

**Comment by Joshua260403** [comment]
Nop, works just fine, meaning this is probably either a linux thing, you didn't test it, or it works for me because my pc is filled to the brim with messy libraries everywhere

**Comment by richelbilderbeek** [comment]
Works on my computer :rainbow:
