### ISSUE TITLE
A game event should move tiles

### ISSUE THREAD

**Issue by robkruger** [richelbilderbeek/djog_unos_2018#331]
`g.process_events()` should move a tile

The test is:

```c++
//A game event should move tiles
  {
    const std::vector<agent> no_agents;
    game g( { tile(0.0, 0.0, 0.0, 10.0, 10.0) }, no_agents);
    tile& tile = g.get_tiles()[0];
    const auto x_before = tile.get_x();
    const auto y_before = tile.get_y();
    tile.set_dx(5.0);
    tile.set_dy(5.0);
    g.process_events();
    const auto x_after = tile.get_x();
    const auto y_after = tile.get_y();
    assert(x_before != x_after);
    assert(y_before != y_after);
  }
```

**Comment by Joshua260403** [comment]
Not sure if this can be tested

**Comment by Joshua260403** [comment]
Also if this works the test for agent follows tile should work too

**Comment by robkruger** [comment]
It does

**Comment by Joshua260403** [comment]
Which one, the test for agent follows tile or it has to be tested

**Comment by Joshua260403** [comment]
I see, it has to be tested. Because it doesn't work correctly

**Comment by Joshua260403** [comment]
Changing this to high priority because we want to check out the result of issue #244.

**Comment by Joshua260403** [comment]
Is that a valid reason?

**Comment by robkruger** [comment]
> I see, it has to be tested. Because it doesn't work correctly

Why doesn't it work correctly?

**Comment by Joshua260403** [comment]
The tiles move too far

Op za 26 jan. 2019 19:30 schreef robkruger <notifications@github.com:

**Comment by richelbilderbeek** [comment]
OK, I've merged your work with develop and will open up this Issue for a Team Octane member of tonight. :+1:
