### ISSUE TITLE
Birds can fly over the void

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#340]
@richelbilderbeek thought this was true already, little did he know his test was wrong. He used a.move(), which doesn't contain the killing part.

Uncomment the define for this test:
>```cpp
>  //#define FIX_FLYING
>  #ifdef FIX_FLYING
>  //Flying agent can fly over nothing without problems
>  {
>    const std::vector<tile> no_tiles;
>    game g(no_tiles, { agent(agent_type::bird, -100, -100, 100)});
>    assert(g.get_agents()[0].get_health() > 0.0); //!OCLINT accepted idiom
>    g.get_agents()[0].process_events(g);
>    assert(g.get_agents()[0].get_health() > 0.0); //!OCLINT accepted idiom
>  }
>  #endif
>```
and get to fixing.
You should only have to add 1 line to the code!

**Comment by richelbilderbeek** [comment]
Thanks @Joshua260403, for lifting the veil from my eyes :godmode: !

**Comment by martje127** [comment]
the birds doen't move. so the can't fly over the void.

**Comment by Joshua260403** [comment]
there's a test for this, check if the test works and close it if so.

**Comment by martje127** [comment]
sorry its working
