### ISSUE TITLE
Birds move (or actually: fly)

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#343]
**Is your feature request related to a problem? Please describe.**

Currently, birds stand still. In reality, they move by flying.

**Describe the solution you'd like**

Fix this test:

```c++
  //#define FIX_ISSUE_343
  #ifdef FIX_ISSUE_343
  // A bird moves
  {
    game g;
    std::srand(314);
    const double x{12.34};
    const double y{56.78};
    agent a(agent_type::bird, x, y);
    assert(is_on_tile(g, a));
    a.move();
    assert(a.get_x() != x || a.get_y() != y);
  }
  #endif
```

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by martje127** [comment]
did it

**Comment by richelbilderbeek** [comment]
Build does not pass, due to OCLint. Will assign a Friday team member to fix that and get this merged :+1:
