### ISSUE TITLE
Agents can drown

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#344]
**Is your feature request related to a problem? Please describe.**

It does not matter to cows on which tile they are. In reality, cows need to swim in water. This takes them more effort. 

**Describe the solution you'd like**

I would like the stamina of cows to go down faster on water. If the stamina reaches zero, I want the health to go down also faster.

 1. Create a test in `game` that fails. Surround it by preprocessor statements, so other team member can still run their code. Push with commit message `Expose #344` 
  2. Fix the problem. Remove the preprocessor statements. Push with commit message 'A cow loses stamina and health on water faster, progress #344'
  3. Let it be merged to develop by moving this Issue in the Project page

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by Joshua260403** [comment]
What do you think about: agents drown.
