### ISSUE TITLE
Trees grow

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#345]
**Is your feature request related to a problem? Please describe.**

Currently, trees do nothing. In reality, they multiply in time iff undisturbed and abiotic factors are cooperative.

**Describe the solution you'd like**

Make trees multiply, by creating new trees after a while. Watch out: they should not multiply too fast!

Follow these steps:

 1. Create a test in `game` that fails. Surround it by preprocessor statements, so other team member can still run their code. Push with commit message `Expose #345` 
  2. Fix the problem. Remove the preprocessor statements. Push with commit message 'Trees grow, progress #345'
  3. Let it be merged to develop by moving this Issue in the Project page

**Describe alternatives you've considered**

None.

**Additional context**

This is similar to #288

**Comment by Joshua260403** [comment]
Duplicate of #305
