### ISSUE TITLE
Add whale agent

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#348]
Add a whale to live in the water

**Comment by richelbilderbeek** [comment]
Sure, there is a whale picture, but I cannot see it anywhere. I will open up this Issue for the devs of tonight.

**Comment by Joshua260403** [comment]
I don't really see a reason to unassign @Tomstuivenga, he was almost done.

**Comment by Joshua260403** [comment]
@richelbilderbeek please redo rijks commit as it contains both mistakes and content that wasn't assigned to him, reassign @Tomstuivenga afterwards for he was almost done and knows what to do here

**Comment by richelbilderbeek** [comment]
Will do. Note to self:

```
git cherry-pick a08f9654204e0a8e515a2524bfd49f29d5e98039
```

**Comment by richelbilderbeek** [comment]
Did so. Whale is there!

![2019-02-08-180724_1722x910_scrot](https://user-images.githubusercontent.com/2098230/52493688-68052080-2bcc-11e9-9997-7fb4c1c96add.png)

**Comment by richelbilderbeek** [comment]
It's on the `richel` branch, must yet be merged to `develop`.

**Comment by richelbilderbeek** [comment]
All tests pass, except OCLint, as can be seen in [the OCLint build log](https://travis-ci.org/richelbilderbeek/djog_unos_2018/builds/490645624#L1887).

@Tomstuivenga: even though it may not have been you who causes the OCLint mistakes, I think it would be cool if you'd fix them, so you can finish the Issue in full glory :+1:
