### ISSUE TITLE
Vote on the new Team Octane logo (for the absent)

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#351]
It is time, the highest time, to create a new Team Octane logo! May the best logo win!

### Rules:
* Copyright free
* Made by yourself
* No inappropriate content
* Relevant to the team in any way
* File format: PNG (transparent) or JPEG (i'll make it transparent if it gets chosen)

To participate either attach the file to your comment or upload it to a hosting site and embed the image like this: `![logo](https://image.hosting.site/your/image)`

**[edit by @richelbilderbeek] below:**
 * Deadline submissions: June 1st 17:59, after which voting opens up
 * Deadline votes: June 1st 23:59

**Comment by RafayelGardishyan** [comment]
Here's my logo, the best logo of all:
[![Team-Octane.png](https://i.postimg.cc/26J5CrDh/Team-Octane.png)](https://postimg.cc/34XhBMWx)

**Comment by Joshua260403** [comment]
![logo](https://snag.gy/Z6Bf3C.jpg)

**Comment by Joshua260403** [comment]
I don't really see how @RafayelGardishyan's logo relates to our team

**Comment by Rijk-van-Putten** [comment]
What about this?

I was thinking about an octopus. It has 8 arms.
![logo](https://i.postimg.cc/BQk5NWFj/team-octance-3-edit.png)
Made with Blender 2.8

**Comment by Joshua260403** [comment]
Only the team name will still be team octane :laughing:

Op ma 11 feb. 2019 19:17 schreef Rijk van Putten <notifications@github.com:

**Comment by RafayelGardishyan** [comment]
> I don't really see how @RafayelGardishyan's logo relates to our team

Octane is fuel -> Fire
 8 -> Octagone
TItle -> Team Octane

**Comment by richelbilderbeek** [comment]
I suggest to set the deadline to June 1st 17:59, which is one minute before the Team Octane Hackathon, and we'll open up voting to 23:59. Will discuss this with the team this Thursday and Friday.

**Comment by richelbilderbeek** [comment]
I've edited the OP. I did not discuss this with the Friday team, however, but I predict they think it is fine. I hope I will remember to discuss this next Friday.

**Comment by Rijk-van-Putten** [comment]
I made more designs!
2 hours before the deadline 👍 

First one:
![](https://i.imgur.com/IZshkFW.png)
![](https://i.imgur.com/8OCJIzN.png)



Other font:
![](https://i.imgur.com/YtOsxEL.png)
With color: 
![](https://i.imgur.com/dOK9LC3.png)

**Comment by Joshua260403** [comment]
If you are not at the hackaton but still wanna vote, you can do here (before 19:45)

**Comment by Joshua260403** [comment]
You can still vote if you aren't here today:
Current results:
Logo | Votes | Winner
---|---|---
Team octance text with cuts in grey | 4 | O
Team octance text with flame in grey | 5 | X
Team octane flame logo orange | 4 | O
Team octanne squid with eyes | 3 | O
Team octanne squid without eyes | 4 | O
Pixelart octane molecule | 1 | O

**Comment by Joshua260403** [comment]
OK we are closing the votes, we are tired of waiting :seedling:
