### ISSUE TITLE
Rename 'dessert' to 'desert'

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#355]
**Is your feature request related to a problem? Please describe.**

The barren land type the Sahara consists of is called a desert. Some commented-out tests, however, use the word 'dessert', which is a part of a meal.

**Describe the solution you'd like**

Rename all uses of the tile type 'dessert' to 'desert'.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
Redundant
