### ISSUE TITLE
Add title screen

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#36]
[**edit: fixed ambiguities**]

**Is your feature request related to a problem? Please describe.**

Our users should be see a title screen when the game is starting

**Describe the solution you'd like**

I would like to have a title screen. It should display the title of the game. 

It should show up if the game is run with:

```
./nature-zen --title
```

The title screen should close in some way, e.g. pressing ESC.

**Describe alternatives you've considered**

None.

**Additional context**

We'll integrate the multiple screens into the game later.

**Comment by Joshua260403** [comment]
now all we need is a button starting the game

**Comment by Joshua260403** [comment]
check out my branch to see the progress, wont push to develop because you can't acces the game except for with a command line argument

**Comment by Joshua260403** [comment]
nope complete disaster, undid all changes i made. did it completely the wrong way

**Comment by Joshua260403** [comment]
on the bright side, learned alot about how everything works

**Comment by richelbilderbeek** [comment]
Great to read you dared to undo all your work (`git checkout .` removes all changes as well, use with care!) and observing that it insightful. You could have added a commit like 'Added title screen (breaks build)' so someone else would have been able to fix it and keep your -probably brilliant- artwork :+1: 

For example, this needs to be added to `main`:

```
int main()
{
  //...
  if (std::count(std::begin(args), std::end(args), "--title"))
  {
    sfml_title_screen s;
    s.exec();
    return 0;
  }
}
```

Will you try again?

**Comment by richelbilderbeek** [comment]
@Joshua260403: I assigned you to finish this. Unassign if you disagree, else I look forward to an awesome title screen :factory:

**Comment by richelbilderbeek** [comment]
@Joshua260403: I will unassign you -sorry for the confusion!- as I want you to help malin10 and annabelliard and Rijk-van-Putten to do this Issue and #35 ('About screen') and #37 ('Menu screen').

Will you be there on Thursday?

**Comment by Joshua260403** [comment]
I'll try to be there.

**Comment by Joshua260403** [comment]
Are you sure you want to do it with a different window, two multiple windows made alot of problems for me. I think it's better to work with states, so the game itself only reacts when the state is game and the other screens are just overlays or something.

**Comment by RafayelGardishyan** [comment]
@Joshua260403 I think richel means that you should have different screens but you can run them apart

**Comment by Joshua260403** [comment]
I know, that is excectly what i said. Unless you mean something different.

The code in richels message makes it so it opens two windows

**Comment by richelbilderbeek** [comment]
I am sorry for the ambiguiity: 

If the game is run with:

```
./nature-zen --title
```

I want it to display the title and then close.

This to help the junior devs to get into the project.

In the future I will ask the team to connect these screens from within the same program.

**Comment by richelbilderbeek** [comment]
I will assign @malin10 to do this on Thursdays. @Joshua260403 will be there to help you and the other junior devs.

**Comment by malin10** [comment]
Hello Richel,

I’m sorry but I have decided to not come anymore.
I’m really busy on school, a little more busy than I thought and with work
I can’t miss another night to non school related stuff.
I had a really good time tho last Thursday.

Greetings,
Malin.


Op maandag 24 september 2018 heeft Richel Bilderbeek <
notifications@github.com> het volgende geschreven:

**Comment by richelbilderbeek** [comment]
@malin10: No problemo, school goes first. I will send a PM later today.

**Comment by martje127** [comment]
there is a title screen
