### ISSUE TITLE
Tiles move too far.

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#360]
When moving a tile next to another one, you will see that it is misplaced. Fix this. I believe tiles should move 115 pixels.

This is a high priority Issue, as the merging of tiles depends on this.

**Comment by richelbilderbeek** [comment]
I predict this is due to, for tiles to merge, they needs to be at *exactly* the same location, i.e. `x1 == x2`. 

I predict this can be fixed that, for tiles to merge, distance needs to be less than 0.5.

**Comment by Joshua260403** [comment]
No they visibly move to far.

Op za 2 feb. 2019 17:43 schreef Richel Bilderbeek <notifications@github.com:

**Comment by Joshua260403** [comment]
Not sure if it is fixed, the solution seems a bit odd. Will have to check it out tonight.
