### ISSUE TITLE
Game crashes when deleting a selected tile

### ISSUE THREAD

**Issue by robkruger** [richelbilderbeek/djog_unos_2018#361]
### Issue Description
Describe here what the issue is

Currently, the tiles can get removed by right-clicking them. It works, but if the tile is selected and you right-click the tile, the game crashes. The error is:  `terminate called after throwing an instance of 'std::runtime_error'
  what():  ID not found`

Fix that.

**Comment by Joshua260403** [comment]
@richelbilderbeek @robkruger Rob's branch i equal to Develop! What happend, is his work on develop already?

**Comment by robkruger** [comment]
I think so, because @richelbilderbeek merged #326 with develop and I did that issue after this one.

**Comment by Joshua260403** [comment]
Ah, so Richel did it?

Op vr 8 feb. 2019 14:31 schreef Rob Krüger <notifications@github.com:

**Comment by robkruger** [comment]
Yes

**Comment by richelbilderbeek** [comment]
Yes, I definitely did that. @robkruger fixed #326, so it should be merged. I do not think that Issue had anything to do with this Issue. I think @robkruger simply detected it after fixing this unrelated Issue.

**Comment by richelbilderbeek** [comment]
I have caused a crash in 1 out of 50 attempts. Perhaps @martje127 would enjoy toying around with this error :+1:

**Comment by martje127** [comment]
the game always crashes when pusching on the right mouse button

**Comment by robkruger** [comment]
It works fine if I run it...
