### ISSUE TITLE
Grass is damaged when is grass is nearby

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#363]
**Is your feature request related to a problem? Please describe.**

Grass grows. And we let that be. But it should grow slower when there is too much grass.

Instead of letting grass grow conditionally, we let grass damage each other. Later, you'll see why :+1: 

**Describe the solution you'd like**

Grass should grow normally as usual. But adjacent grass should hurt one another. 

Write a test as usual.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by richelbilderbeek** [comment]
I will free up this Issue for tonight :rainbow:

**Comment by janderkkotlarski** [comment]
Done.
:sunflower:
