### ISSUE TITLE
Agents do not have a dx and dy

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#364]
**Is your feature request related to a problem? Please describe.**

Currently, agents have a `dx` and `dy`, which code for velocities in an X-Y 2D plane. I think these are used for the agents to move along with tiles, but this is a bit of a hack: if a tile is moving, it should simply take its agents with it.

**Describe the solution you'd like**

Remove the member variables `agent::m_dx` and `agent::m_dy`. All tests should keep working.

**Describe alternatives you've considered**

None.

**Additional context**

Agents will have a direction, coded as `m_direction`, see #325

**Comment by robkruger** [comment]
What's wrong?

**Comment by janderkkotlarski** [comment]
Removing `agent::m_dx` and `agent::m_dy` and all associated functions.
