### ISSUE TITLE
Use spider in default agents

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#365]
**Is your feature request related to a problem? Please describe.**

Currently, the spider is not shown when the game starts.

**Describe the solution you'd like**

Get the spider te be shown in the game again. The easiest way, is to add it to the `get_default_agents` function.

Move to 'To be tested by humans` to make the tester close this Issue. 

If the spider is already added, create a new Issue: 'Spider dies immediately'.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
@richelbilderbeek I think create default tiles and agents got messed up by the arrange tiles issu, we could just redo them completely

**Comment by Enzo9** [comment]
Spider is already there but dies immidiantly
