### ISSUE TITLE
Crododiles eat cows

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#366]
**Is your feature request related to a problem? Please describe.**

Crocodiles eat cows. This damages the cow, but increases the health of the crocodile.

**Describe the solution you'd like**

Write a test to do so.
Then make that test come true.

**Describe alternatives you've considered**

None.

**Additional context**

You can use the test to see that grass is eaten by a cow.

**Comment by robkruger** [comment]
A crocodile already does that?

**Comment by Joshua260403** [comment]
That commit needs to be reverted as this was already the case.

**Comment by Joshua260403** [comment]
Now it's duplicate

**Comment by Joshua260403** [comment]
Like @robkruger said :+1:, in the future people should look at the comments on the issue they are doing

**Comment by richelbilderbeek** [comment]
Dumb me! Thanks team :1st_place_medal:
