### ISSUE TITLE
Birds eat spiders

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#367]
**Is your feature request related to a problem? Please describe.**

Birds eat spiders. This damages the spider, but increases the health of the bird.

**Describe the solution you'd like**

Write a test to do so.
Then make that test come true.

**Describe alternatives you've considered**

None.

**Additional context**

You can use the test to see that grass is eaten by a cow.

**Comment by Joshua260403** [comment]
Pretty sure this is done already, will check it out tonight

**Comment by Joshua260403** [comment]
Duplicate of #289, it was already added there, just like #366
