### ISSUE TITLE
Add menu screen

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#37]
**Is your feature request related to a problem? Please describe.**

Our users should be see a menu screen when the game started.

**Describe the solution you'd like**

I would like to have a menu screen. It should show 'Start Game', 'About' and 'Quit'.

**Describe alternatives you've considered**

None.

**Additional context**

 * Initially, it should only show up if the game is run with

```
./nature-zen --menu
```

we will integrate it into the game later.

**Comment by richelbilderbeek** [comment]
I will assign @Rijk-van-Putten to do this on Thursdays. @Joshua260403 will be there to help you and the other junior devs to do this properly.

**Comment by richelbilderbeek** [comment]
Note, it must be called as such:

```
sfml_title_screen g;
g.exec();
```

Create a class called `sfml_title_screen` and put it in `sfml_title_screen.h` and `sfml_title_screen.cpp`.

It must be closable by pressing space.

**Comment by Joshua260403** [comment]
Why does it, when it's called like that it opens a completely new window.

Op do 8 nov. 2018 16:40 schreef Richel Bilderbeek <notifications@github.com:

**Comment by richelbilderbeek** [comment]
Yup, that is the idea.

  1) seperate the classes
  2) display them in a smooth way

**Comment by richelbilderbeek** [comment]
Added a test:

```c++
  if (std::count(std::begin(args), std::end(args), "--menu")) {
    //#define FIX_ISSUE_37
    #ifdef FIX_ISSUE_37
    sfml_menu_screen g;
    g.exec();
    return 0;
    #else
    g.show_title();
    #endif
  }
```

Uncomment `//#define FIX_ISSUE_37` to start fixing it. 

Remove the `#define`, `#ifdef`, `#else` and `#endif` after fixing it. Remove the old code between the `#else` and `#endif`.
