### ISSUE TITLE
octopus dies instantly

### ISSUE THREAD

**Issue by martje127** [richelbilderbeek/djog_unos_2018#371]
Depends on

 * [x] #349

After that, the octopus dies instantly

**Comment by richelbilderbeek** [comment]
Tip: with how much health it is created?

**Comment by Joshua260403** [comment]
Tip: where is it created

**Comment by Joshua260403** [comment]
The octopus isn't even on develop yet....
How would you have closed #349 if it isn't there on your own branch....
