### ISSUE TITLE
Vote: should tiles be connected? Before Thursday 14th 18:00

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#372]
**Is your feature request related to a problem? Please describe.**

Currently, animals fall off the tiles when they attempt to cross from one tile to the other. Should the tiles be connected, or should this be part of a feature (e.g. the player must lift the animals)?

**Describe the solution you'd like**

Vote for: should the tiles be connected? That is, should agents be able to move from one tile to the other. Vote once: Yes, No, or don't vote.

Deadline is Thursday 14th 18:00

**Comment by martje127** [comment]
yes

**Comment by robkruger** [comment]
Yes

**Comment by Rijk-van-Putten** [comment]
Yes

**Comment by Joshua260403** [comment]
I'd say there should be a gap of 1 or 2 pixels that still counts as on the tile.

**Comment by Joshua260403** [comment]
That means yes but not visibly

**Comment by robkruger** [comment]
@josh

> That means yes but not visibly

Yeah, I meant that aswell

**Comment by same-drenth** [comment]
Same same

**Comment by janderkkotlarski** [comment]
Yes

**Comment by janderkkotlarski** [comment]
Yes

**Comment by Joshua260403** [comment]
Deadline struck, There is going to be a visible gap, we just need the gaps to not count
