### ISSUE TITLE
Add function to count agents of a specific type 

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#373]
**Is your feature request related to a problem? Please describe.**

For #368 we need to count the number of cows and grasses. There is no function to easily count these.

**Describe the solution you'd like**

Add a function to count the number of agents of a specific type:

```c++
int count(const game& g, const agent_type t);
```

Write a test to assure it works.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Rijk-van-Putten** [comment]
its already done
