### ISSUE TITLE
Trees should produce trees, instead of grass

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#374]
**Is your feature request related to a problem? Please describe.**

Currently, trees produce grasses. In reality, trees produce trees. 

**Describe the solution you'd like**

If trees reproduce, make it so that there is a new tree (instead of a grass) created.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by robkruger** [comment]
This is not fixed
