### ISSUE TITLE
Codecov isn't working

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#376]
I think it might be because we run with --version first on travis, but it could be anything. We need to know asap because oclint might also not be working.

**Comment by richelbilderbeek** [comment]
I see at [the Travis CI log of my latest build](https://travis-ci.org/richelbilderbeek/djog_unos_2018/builds/490591138#L1888), that everything works fine.

I decrease priority to medium, as perhaps I misunderstand something. Lemme know if, else close the Issue :+1:

**Comment by Joshua260403** [comment]
It says 0% everywhere.
Also, check my profile :)
