### ISSUE TITLE
Random tile movement

### ISSUE THREAD

**Issue by RafayelGardishyan** [richelbilderbeek/djog_unos_2018#38]
There have to be a random movement of tile causing higher difficulty level for our game

**Comment by richelbilderbeek** [comment]
Good suggestion :+1:! 

I am unsure that -when we get to that point- that we will think this is the best option. I suggest that -when we get to that point- I will request a vote. Good idea?

From that, I suggest you close this Issue if you agree, else let me know your thoughts here.

**Comment by RafayelGardishyan** [comment]
Ok, closing
