### ISSUE TITLE
Add snake agent

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#384]
Add a snake agent:

* Add the red cobra logo (from djog nanos) as sprite for the snek
* Add `snake` agent type
* Add snake to can eat so it eats a bird

**Comment by richelbilderbeek** [comment]
Here it is:

![red_cobra](https://user-images.githubusercontent.com/2098230/52817341-d7cf4b80-30a3-11e9-8efa-6b354ed87f22.png)
