### ISSUE TITLE
Vote before Thursday 7:00: must the game be savable? 

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#39]
**Is your feature request related to a problem? Please describe.**

At #32 ('Suggest the goal of the game') it has been suggested that the game must be savable. I think this is a nice entry point on voting if we think this really is important for our idea of the game.

**Describe the solution you'd like**

I suggest to vote:

 * No saving
 * Progress stored by a password
 * Saving at certain in-game locations
 * Saving always possible

You can vote for or against each option (the votes are an example):

Option|Vote
---|---
No saving|Y
Progress stored by a password|N
Saving at certain in-game locations|Y
Saving always possible|N

Type of save will be picked by most votes. If it's a draw, I decide.

![mega-man-2-password](https://user-images.githubusercontent.com/2098230/45539586-7829f700-b80a-11e8-966a-2df4dd007f3a.png)

**Describe alternatives you've considered**

I considered just having it my way :crown: 

**Additional context**

This will influence the game a lot:

 * No saving is the most scary/exciting, as game over really is game over
 * No saving is easiest to program (it is already done!)
 * Password storing is fun to program
 * Saving at in-game locations is immersive

**Comment by richelbilderbeek** [comment]
My vote:

Option|Vote
---|---
No saving|Y
Progress stored by a password|Y
Saving at certain in-game locations|N
Saving always possible|N

**Comment by Joshua260403** [comment]
1|2|3|4
--|--|--|--
N|N|N|Y

**Comment by RafayelGardishyan** [comment]
1|2|3|4
--|--|--|--
N|N|N|Y

**Comment by Joshua260403** [comment]
> @Joshua260403: thanks for your vote! For what kind of game mode you have the suggested vote in mind? And how would you vote for a campaign-mode game (and how do you define such a game)?
> 
> If I see the need, I will request a vote for the type of game...

This is explained in #32

**Comment by richelbilderbeek** [comment]
Vote closed: saving is always possible.
