### ISSUE TITLE
Plants grow on a tile

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#392]
When grass duplicates, it mostly falls in the void. This decreases the score.

Make it so grass can only spawn on a tile (so not even on the edges)

Same goes for trees.

**Comment by robkruger** [comment]
What about spawning on a water tile?

**Comment by Joshua260403** [comment]
You should make it so plants only spawn on land tiles, which means not in
the void and not on water

Op zo 17 feb. 2019 16:23 schreef Rob Krüger <notifications@github.com:
