### ISSUE TITLE
Volunteer at DJO Open Dag, March 9th, somewhere 10:00-16:00

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#394]
Saturday, March 9th, from 10:00-16:00 DJO has an Open Day. With Team Octane (and probably Team Red Cobra), we will teach how to work with git by writing a fairytale together. For that, we need volunteers! If it's just for one hour :+1:, for longer: :+1::+1::+1:. Also, we'll probably present our work every ?hour. 

Let me know if and when you'll be there :rainbow:, @richelbilderbeek

**Comment by robkruger** [comment]
I'll come around 12:00.👍

**Comment by RafayelGardishyan** [comment]
I will be there the whooooooooole day

**Comment by Joshua260403** [comment]
i think i might be there

not sure though

**Comment by richelbilderbeek** [comment]
Cool, we'll be there!
