### ISSUE TITLE
There are at least two whale agent types

### ISSUE THREAD

**Issue by janderkkotlarski** [richelbilderbeek/djog_unos_2018#396]
Problem

An assert statement throws an exception and the compiler warning complains about there being multiple agent types of the whale type.

Solution

Make it so that there is only one whale agent type left.
The other agent types must be left alone and all the tests need to stay functioning.

**Comment by richelbilderbeek** [comment]
This is fixed by me and put on `develop`. Merge it into your branch and you're good to go :+1:

**Comment by Joshua260403** [comment]
So I'm assuming this has to be closed?
