### ISSUE TITLE
Join Studium Generale lecture on Wednesday 6th 20:00-?21:00

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#397]
**Is your feature request related to a problem? Please describe.**

Instead of the expert lectures, Richel chose to got to Studium Generale lectures instead. But which one?

[Here](http://sggroningen.nl/en/programma) is the program, here is my favorite selection:

Title|Topic|Date and time
---|---|---
Normalisering van drugs in het uitgaansleven|The normalcy of drugs when going out (pun not intended)|Tuesday 5 March 2019 - 8:00 pm
Behandel haar met respect|Using more women as scientific test subjects|Wednesday 6 March 2019 - 8:00 pm
Wat we van het weer verwachten|How good are weather predictions|Tuesday 12 March 2019 - 8:00 pm

**Describe the solution you'd like**

If you want go to a lecture, let me know. 3 or more students means we'll go there. Richel pays the entrance fees. Use this table:

Topic|Interested yes/no
---|---
Normalisering van drugs in het uitgaansleven|.
Behandel haar met respect|.
Wat we van het weer verwachten|.

**Describe alternatives you've considered**

None.

**Additional context**

There will be more options in the future.

**Comment by JolienGay** [comment]
Topic|Interested yes/no
---|---
Normalisering van drugs in het uitgaansleven| N (can't attend that day)
Behandel haar met respect| Y
Wat we van het weer verwachten| Y

**Describe alternatives you've considered**
End of Daylight Saving Time and Then? 
This might sound boring and insignificant (1h, what is the big deal?) but, as Arjen Lubach has pointed out is one of his sunday shows, many people do not know how bad the wrong choice can be for the Netherlands specifically. On top of that, 'summer time' is associated with everything good and comfortable (warmth, sun, holiday, ...) despite it being the more unnatural choice. For more information I recommend watching Lubach's excellent episode on this topic [here](https://www.youtube.com/watch?v=PCA_VyXCPok). 

**Extra**
If people are interested in Studium lectures and it is descided to attend one, Richel does not need to pay entrance fee for me as I have a student card that will let me enter for free.

**Comment by RafayelGardishyan** [comment]
Topic|Interested yes/no
---|---
Normalisering van drugs in het uitgaansleven| N (can't attend that day)
Behandel haar met respect| Y
Wat we van het weer verwachten| N (can't attend that day)

**Comment by Joshua260403** [comment]
Topic|Interested yes/no
---|---
Normalisering van drugs in het uitgaansleven| N
Behandel haar met respect| Y
Wat we van het weer verwachten| N

**Comment by richelbilderbeek** [comment]
Cool @JolienGay, @Joshua260403, @RafayelGardishyan!

We'll go to 'Behandel haar met respect' on Wednesday 6 March 2019 at 8:00 pm at Academiegebouw, Broerstraat 5!

**Comment by richelbilderbeek** [comment]
Bough tickets, closing this Issue.
