### ISSUE TITLE
Join for Pi Day?

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#398]
**Is your feature request related to a problem? Please describe.**

![Pi Day](http://richelbilderbeek.nl/RC_PiDay2015.htm) needs to be celebrated every year.

We do so each year, my meeting at March 13th 23:57 (pi minutes before Pi Day) at bus stop P at the Central Station Groningen. We leave at 0:03 (pi minutes past midnight) at March 14th by foot. Then we use street chalk to paint pi symbols on the pavements.

**Describe the solution you'd like**

Want to join? Let me know below.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by RafayelGardishyan** [comment]
I want to attend to Pi day celebration

**Comment by JolienGay** [comment]
Fun idea! Unfortunately I can't attend.

**Comment by richelbilderbeek** [comment]
Done!

[We made into the newspaper](https://www.dvhn.nl/groningen/Het-is-Pi-dag-Rich%C3%A8l-Bilderbeek-trekt-spoor-van-pis-door-Groninger-binnenstad-24265650.html)!

**Comment by richelbilderbeek** [comment]
[Radio fragment](https://www.rtvnoord.nl/radio/programma/20700/Karel-op-Noord/aflevering/22471) at 20:00-24:10

**Comment by Joshua260403** [comment]
At exactly 21:00, after the wierd german song

Op do 14 mrt. 2019 13:58 schreef Richel Bilderbeek <notifications@github.com

**Comment by richelbilderbeek** [comment]
[more news](https://www.rtvnoord.nl/nieuws/206075/Sinterklaas-vieren-we-alleen-op-aarde-pi-dag-kan-in-het-hele-universum)
