### ISSUE TITLE
Add chameleon agent

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#405]
Add a chameleon agent

and do all that stuff that needs to be done when adding an agent

**Comment by Joshua260403** [comment]
Reassigned to Anton so he can get familiar with the code, you can check out branch "isis" and pull that to yourself or you may start over.

**Comment by antonhensen81** [comment]
Should eat worms, spiders, birds

**Comment by richelbilderbeek** [comment]
It's in Done, so it can probably be closed :+1:
