### ISSUE TITLE
Add roles in About screen

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#409]
**Is your feature request related to a problem? Please describe.**

Currently, the about screen only shows the names. I also want the roles there.

**Describe the solution you'd like**

Something like, in this order, add last names yourself:

```
project manager
Richel

senior developer
Richel

medior developers
Joshua
Rafaye
Rob

junior developers
[all others currently in team]
[all others that have already left the team]

lead game designer
Joshua

lead testing
Mart

lead graphics
Same

lead sound
Same
```

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
I thought @Rijk-van-Putten did this saterday

**Comment by richelbilderbeek** [comment]
I close this for now, #514 is its successor.
