### ISSUE TITLE
Remove mouse speed 

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#414]
**Is your feature request related to a problem? Please describe.**

Now, the mouse speed is displayed:

![2019-02-28-203345_1722x910_scrot](https://user-images.githubusercontent.com/2098230/53593154-3f06f880-3b98-11e9-8f28-9930b86b6ba5.png)

The lead game designer wants it removed.

**Describe the solution you'd like**

Remove the mouse speed display.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by martje127** [comment]
its removed
