### ISSUE TITLE
Agents can move between tiles

### ISSUE THREAD

**Issue by JolienGay** [richelbilderbeek/djog_unos_2018#415]
**Is your feature request related to a problem? Please describe.**

In #387 we wanted agents to move between tiles. The Issue has been closed -probably for good reasons-, but the problem has popped up (?again).

**Describe the solution you'd like**

Agents should be able to move between adjacent tiles.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by richelbilderbeek** [comment]
Jolien and Tom have temporarily left the team. I will unassign them and move this Issue to 'To be checked by medior', as I am unsure about the status.
