### ISSUE TITLE
Zen must go up if fewer agents than tiles

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#416]
**Is your feature request related to a problem? Please describe.**

Currently Zen does not respond to the number of agents in the game. In reality, the less agents, the more Zen.

**Describe the solution you'd like**

If there are less agents than tiles, the Zen should increase.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
Will rephrase and integrate this in another issue
