### ISSUE TITLE
Test to check if cows move towards grass fail due to venus_fly_trap

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#423]
**Is your feature request related to a problem? Please describe.**

When adding the `venus_fly_trap` agent to `create_default_agents`, e.g. like:

```c++
  //#define FIX_ISSUE_423
  #ifdef FIX_ISSUE_423
  {
    agent a5(agent_type::venus_fly_trap, 270, 240, 50 + std::rand() / (RAND_MAX / (100 - 50 + 1) + 1));
    move_agent_to_tile(a5, 0, 2);
    agents.push_back(a5);
  }
  #endif // FIX_ISSUE_423
```

the error is given:

```
djog_unos_2018: ../djog_unos_2018/agent.cpp:867: void test_agent(): Assertion `distanceX > distance_afterX' failed.
```

**Describe the solution you'd like**

The old test should keep working. Put the Venus fly trap elsewhere or so...

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by robkruger** [comment]
I fixed this in #326, will merge to develop if my build succeeds.
