### ISSUE TITLE
Still sick & tired (also richel cheated)

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#425]
How does @richelbilderbeek suddenly have 660k additions

**Comment by Joshua260403** [comment]
How am i supposed to surpass you now?

**Comment by Joshua260403** [comment]
I give @richelbilderbeek the task to create issues for tonight when theres nothing left

**Comment by richelbilderbeek** [comment]
I accidentally added the code coverage notes :frowning_face:

**Comment by richelbilderbeek** [comment]
Sure, I'll take over. Get well soon :apple: :green_apple:
