### ISSUE TITLE
Venus fly trap must not move

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#426]
**Is your feature request related to a problem? Please describe.**

Currently, the venus fly trap -a plant species- moves. In reality a plant does not move.

**Describe the solution you'd like**

Write a test that checks if the Venus fly trap does not move. This is already tested for `agent_type::grass`, so copy that one. The test should fail.

Then fix the problem: make the venus fly trap stand still.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
I do not approve of the changes made in that commit

**Comment by richelbilderbeek** [comment]
Well spotted @Joshua260403 !

I also see that the commit is -indeed- partially correct and partially incorrect.

 * correct: a Venus fly trap does indeed not move
 * incorrect: a Venus fly trap does eat plants

Rule is: if all tests pass, the code is accepted.

I suggest to accepted the code, then add tests to expose the incorrect parts of the commit, then add an Issue to assign this to the others.

Could you agree on that?

**Comment by Joshua260403** [comment]
Thats exactly what i had in mind

Op vr 8 mrt. 2019 16:45 schreef Richel Bilderbeek <notifications@github.com

**Comment by richelbilderbeek** [comment]
Cool! Let's get this beautiful plant species what it deserves :+1:
