### ISSUE TITLE
Title screen should take user to menu without a button

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#429]
**Is your feature request related to a problem? Please describe.**

Most games start with a title or loading screen. Normally, any key press or mouse click would take the user to the menu screen. 

**Describe the solution you'd like**

 * [x] Make the title screen direct the user to the menu screen
 * [x] Make the title screen do so from a key press
 * [x] Make the title screen do so from a mouse press
 * [x] Remove the start button from the title screen

**Describe alternatives you've considered**

None.

**Additional context**

Tip: run the game is run with `--title` in the Project options

**Comment by Joshua260403** [comment]
I think it should have a button, thats the entire purpose of a title screen

**Comment by Joshua260403** [comment]
Hmmm, will have to think about this one

**Comment by richelbilderbeek** [comment]
Taking a look at [ducking for 'Title Screen'](https://duckduckgo.com/?q=title+screen&t=canonical&iax=images&ia=images) we see that usually there is no button. OTOH, having a button there does not hurt.

I suggest to keep the button, but to go to the menu screen wherever the user clicked or whatever key the user pressed.

Like this idea better?

**Comment by martje127** [comment]
its completely fine
