### ISSUE TITLE
Agents should follow tile

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#432]
**Is your feature request related to a problem? Please describe.**

When a tile with agents on it is moved, the agents are not dragged along.

**Describe the solution you'd like**

Make the agents be dragged along with the tile.

Do not use `m_dx` or `m_dy`.

**Describe alternatives you've considered**

None.

**Additional context**

It would be cool if this would be tested again :+1:

**Comment by RafayelGardishyan** [comment]
I'll try
