### ISSUE TITLE
vote (medior-only): polymorphism yes or no

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#435]
**Is your feature request related to a problem? Please describe.**

Currently, we do not use polymorphism a lot (there are cases we do!), because of the difficulty of getting this right. Richel knows how often the complexity of polymorphism is underestimated and that's why he decided against this: he predicts the poor mediors will make the code overly complex, after which the mediors will have to remove their hard work. Also, we may miss the project's deadline.

On the other hand, we have some mediors that want to try out this hip feature. Shouldn't they be allowed to get this (probably bad) experience in this aspect? And maybe, because the codebase is already rather mature, it may result in code with a right architecture.

**Describe the solution you'd like**

Vote: do we allow to use polymorphism or not? Only the mediors get to vote, as those are the ones that will wrestle with this feature, which are currently Joshua, Rafayel and Rob. 

**Describe alternatives you've considered**

I (Richel) have considered to forbid this feature up until the deadline.

**Additional context**

None.

**Comment by Joshua260403** [comment]
Could you explain polymorphism

Op do 7 mrt. 2019 21:20 schreef Richel Bilderbeek <notifications@github.com

**Comment by RafayelGardishyan** [comment]
I am voting to use it!

**Comment by richelbilderbeek** [comment]
Polymorphism allows to make a (base) class behave differently according to its (derived) type.

For example, our `agent`s have a maximum depth at which they survive (zero for land-only animals), which we determine using a switch statement on `agent_type`. Here a simplified piece of code:

```c++
double get_maximum_depth(const agent& a)
{
  switch (a.get_type()) 
  {
    case agent_type::fish: return 50.0;
    case agent_type::whale: return 100.0;
  }
}
```

would become:

```c++
class agent
{
  virtual double get_maximum_depth() const = 0; 
  virtual ~agent() {}
};

class fish : public agent
{
  double get_maximum_depth() const { return 50.0; }
};

class whale : public agent
{
  double get_maximum_depth() const { return 100.0; }
};
```

Drawback is that this example is so simple, one would think polymorphism is simple. It is not. Compiling an linking and running will become harder.

Good luck with the votes :+1:

**Comment by Joshua260403** [comment]
I vote no

Op do 7 mrt. 2019 21:39 schreef Richel Bilderbeek <notifications@github.com

**Comment by robkruger** [comment]
I'm also voting no

**Comment by richelbilderbeek** [comment]
OK, there has been voted against polymorphism.

Let's see if we'll use it in the next project :rainbow:
