### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by RafayelGardishyan** [richelbilderbeek/djog_unos_2018#44]
**Is your feature request related to a problem? Please describe.**
Testing takes too much time

**Describe the solution you'd like**
Write a test which will test every part of our game

**Describe alternatives you've considered**
None

**Additional context**
Maybe something for @richelbilderbeek or @RafayelGardishyan

**Comment by richelbilderbeek** [comment]
Good suggestion!

Actually, this is already taking shape:

 * Testing game logic (`game`): Travis
 * Testing graphical game (`sfml_game`): Travis (but not yet implemented)
 * Acceptance testing: human testing team led by @martje127 

Of course, developers will verify if a graphical feature works, but only briefly. It is the idea they verify, then push to GitHub to let Travis do the testing.

I will close this Issue, as this is already a work in progress.
