### ISSUE TITLE
Merging woods and woods should result in rain forest

### ISSUE THREAD

**Issue by antonhensen81** [richelbilderbeek/djog_unos_2018#457]
**Is your feature request related to a problem? Please describe.**
Currently, wood and wood cannot be merged.

**Describe the solution you'd like**
Merging wood and wood should result in forest

**Describe alternatives you've considered**
None

**Additional context**
There is a test in test_tile_type that test exactly this, uncomment the following line to make the test run and make it pass:

    //assert(get_merge_type(tile_type::woods, tile_type::woods) == tile_type::rain_forrest);

**Comment by Joshua260403** [comment]
Wait wot

**Comment by Joshua260403** [comment]
Also rename it to forest instead of forrest. Forrest is "run forrest run", forest is a biome with trees.
