### ISSUE TITLE
Create text_input class

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#460]
Just a text input box, in a class called sfml_text_input.

Might aswell copy the button and change some things up.

**Comment by Joshua260403** [comment]
Note to self: check if m_selected actually does something

**Comment by Joshua260403** [comment]
Note to self: remove std::cout

**Comment by antonhensen81** [comment]
@Joshua260403 I fail to see how this is 'maybe done'?

**Comment by Joshua260403** [comment]
To be tested

Op vr 29 mrt. 2019 20:53 schreef antonhensen81 <notifications@github.com>:
