### ISSUE TITLE
Please don't do all issues

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#465]
@robkruger does alot of issues, i'm having a hard time creating enough new ones, and when i do, they are all done by next week.

I suggest rob does a little less issues, especially because we are nearing the completion of the game and there soon will be nothing left for others (including mediors).

**Comment by Joshua260403** [comment]
Also i create issues in the weekend mostly, when rob does them at home, they are gone by Thursday and especially by Friday. That way it is useless to create issues in the weekend and i am unable to create enough issues.

**Comment by Joshua260403** [comment]
Ooh i know something, how about a debug role for Rob. He is usually really good at finding issues in the code.

**Comment by robkruger** [comment]
That's fine by me!

**Comment by richelbilderbeek** [comment]
Cool that this has been solved as such! Personally, I enjoy @robkruger doing so much work :+1: 

Keep up the good work, the both of you :1st_place_medal:

**Comment by robkruger** [comment]
And if I find something, do I need to create a new issue or resolve it by myself?

**Comment by Joshua260403** [comment]
You should create a new issue and you may assign yourself (if you want)

Op ma 11 mrt. 2019 19:02 schreef Rob Krüger <notifications@github.com>:

**Comment by richelbilderbeek** [comment]
May I suggest closing this Issue?
