### ISSUE TITLE
Suggest: team name before 2018-10-04 7:00

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#47]
**Is your feature request related to a problem? Please describe.**

A team has a name.

**Describe the solution you'd like**

I suggest to collect team names here before October 4th 7:00.

**Describe alternatives you've considered**

None.

**Additional context**

 * I will collect all suggestions at Thursday October 4th 7:00 (in the morning). 
  * I will Issue a vote before 8:00 (that same day). 
  * The votes will be counted at October 11th 7:00

**Comment by RafayelGardishyan** [comment]
Team R (Richel, Rafayel, Rijk = 3*R)

**Comment by richelbilderbeek** [comment]
That's an early suggestion!

Too bad, I will veto (vote against and overrule other votes) 'Team R' as our team currently has six members. Picking a name with only half of the team's names would be inappropriate. 

Looking forward to a more appropriate name :+1:

**Comment by richelbilderbeek** [comment]
I suggest 'Didiem` as we work on two (`di`) different days (`diem`).

**Comment by Joshua260403** [comment]
Apex devs :)

**Comment by Joshua260403** [comment]
`The just a little bit older developers`

**Comment by same-drenth** [comment]
(DJOG ->) Jog Studio or Jog Games or Jog Inc. or something along those lines

[Wiki](https://en.wikipedia.org/wiki/List_of_video_game_developers) for reference

**Comment by richelbilderbeek** [comment]
Collected the suggestions, opened a vote at #138. Closing this one.
