### ISSUE TITLE
Respond to keyboard in pause screen

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#472]
**Is your feature request related to a problem? Please describe.**

Currently, when pausing the game, one needs to click on 'Continue' or 'Quit'. Pressing 'C' or 'Q' does nothing.

**Describe the solution you'd like**

 * Allow the use to continue when he/she presses 'C'.
 * Allow the user to quit when he/she presses 'Q'

**Describe alternatives you've considered**

None

**Additional context**

None. If you think space should also allow to the player to continue the game, go ahead and do so :+1:

**Comment by Joshua260403** [comment]
Continue with escape would make sense too
