### ISSUE TITLE
Suggest: move all UX Issues to here

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#473]
**Is your feature request related to a problem? Please describe.**

Currently, the graphics department could use some help. I suggest to move all UX Issues to this project, so others can assign themselves some graphics Issues.

**Describe the solution you'd like**

I suggest to vote before doing so with the adolescent mediors: @Joshua260403, @RafayelGardishyan and @robkruger. 

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by robkruger** [comment]
That's fine by me

**Comment by richelbilderbeek** [comment]
@Joshua260403 agrees, let's do it :shipit:
