### ISSUE TITLE
Make menu screen respond to keys

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#476]
**Is your feature request related to a problem? Please describe.**

Our menu screen is awesome. To go to the other sections, one needs to click with the mouse.

![2019-03-15-162004_1722x910_scrot](https://user-images.githubusercontent.com/2098230/54442058-3ab51080-473e-11e9-83d6-dea317a5a770.png)

Pro users like me expect to be able to use the keyboard to go to other sections

**Describe the solution you'd like**

Make the menu responds to keyboard presses:

 * C: Continue
 * T: Team Octane
 * Q: Quit

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
@Rijk-van-Putten You should redo this issue because the menu screen changed
