### ISSUE TITLE
Put Steam requirements in doc

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#479]
**Is your feature request related to a problem? Please describe.**

Currently, we have an idea of how to get our game on Steam. In the comments below, useful links are added.

**Describe the solution you'd like**

Put those links in a doc, e.g. `doc/requirements.md`.

Create an Issue for each Steam requirement.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by richelbilderbeek** [comment]
Note to self, from [here](https://partner.steamgames.com/newpartner/?signup_type=1):

 * A 30-day waiting period between when you paid the app fee and when you can release your game
 * You’ll need to prepare your store page and put up a publicly-visible ‘coming soon’ page for at least two weeks.

So, deadlines will be:

 * July 4th: final presentation
 * May 31st: having paid fee
 * June 14th: having prepared store page

**Comment by richelbilderbeek** [comment]
GPL license could be a problem, but acceptable, e.g. [KeeperRL](https://github.com/miki151/keeperrl) has a [GPL-2 license](https://github.com/miki151/keeperrl/blob/master/LICENSE).

**Comment by richelbilderbeek** [comment]
Options: 

  1. keep the license under my name and make me state it's fine to have it distributed on Steam  
  2. put the license under Team Octame and make **everyone** state it's fine to have it distributed on Steam

**Comment by richelbilderbeek** [comment]
We will need someone to setup the [SteamPipe](https://partner.steamgames.com/doc/sdk/uploading)...

**Comment by richelbilderbeek** [comment]
There are [many cool features](https://partner.steamgames.com/doc/features) our team members would love to explore!

**Comment by richelbilderbeek** [comment]
The [review process](https://partner.steamgames.com/doc/store/review_process) appears easy!

**Comment by richelbilderbeek** [comment]
We need to think about an [early access](https://partner.steamgames.com/doc/store/earlyaccess) yes/no...

**Comment by richelbilderbeek** [comment]
We need to form or have a legal entity...

>  If you co-own the content with other individuals, you must form a legal entity to own and receive payments for your content.

**Comment by richelbilderbeek** [comment]
We want [the Steam Error Reporting feature](https://partner.steamgames.com/doc/features/error_reporting)!

**Comment by richelbilderbeek** [comment]
Purchased a Steam right to publish, thanks to @antonhensen81:

![we_zijn_op_steam](https://user-images.githubusercontent.com/2098230/54473163-74385b00-47d4-11e9-9e15-31e55888e240.png)

**Comment by Joshua260403** [comment]
why is the account name blurred, is the right bought to an account named anton, can we change the name to team octane or create a steam group named team octane we can publish it under

**Comment by Joshua260403** [comment]
[click here to read the documents btw](https://partner.steamgames.com/doc/store/creator_homepage) 🍀

**Comment by Joshua260403** [comment]
[found this to add devs](https://partner.steamgames.com/pub/users/) (if that is how this is gonna work)

**Comment by richelbilderbeek** [comment]
I am happy enough as this is for now.
