### ISSUE TITLE
SteamPipe: setup SteamPipe

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#484]
**Is your feature request related to a problem? Please describe.**

Steam uses a distribution system called SteamPipe. Someone needs to set it up before our release.

**Describe the solution you'd like**

Someone needs to set it up.

**Describe alternatives you've considered**

None.

**Additional context**

@RafayelGardishyan is in charge with this. This will be his Issue. He is free to help others doing it for/with him, but he'll be end responsible.

**Comment by Joshua260403** [comment]
It's not a CI, it's a distribution system

**Comment by Joshua260403** [comment]
alot of stuff to figure out here

**Comment by richelbilderbeek** [comment]
> It's not a CI, it's a distribution system

Agreed. Fixed the Issue text.

**Comment by richelbilderbeek** [comment]
I unassign Rafayel for now, as this Issue only becomes relevant when the Steam page is opened up.

**Comment by Joshua260403** [comment]
https://partner.steamgames.com/doc/sdk/uploading

**Comment by Joshua260403** [comment]
https://www.youtube.com/watch?v=SoNH-v6aU9Q
from the steam docs
