### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by same-drenth** [richelbilderbeek/djog_unos_2018#485]
**Describe the bug**
Assertion failed
In tile.cpp, line 189
expression: f_y > = 0.0 && f_y 1.0

**To Reproduce**
1. Go to tile.cpp
2. Scroll down to line 189
3. See error

**Expected behavior**
I expect this to not happen again

**Additional context**

**Comment by richelbilderbeek** [comment]
How to reproduce: start up game, happens randomly,

**Comment by richelbilderbeek** [comment]
I cannot reproduce the bug anymore. I assure it is fixed by the other devs :1st_place_medal:
