### ISSUE TITLE
Add God Mode for debugging

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#487]
**Is your feature request related to a problem? Please describe.**

Currently, our testers go Game Over while testing the game. It would be helpful if there would be a God Mode in the game. 

**Describe the solution you'd like**

Add a way to enable God Mode, for example, when `iloverichel` is typed.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by robkruger** [comment]
I also need this for profiling, but if I do this issue, the whole profiling step is also on develop. Is that ok?

**Comment by Joshua260403** [comment]
Will the profilling stuff bring confusion to the team in the way of unused
code or woerd visual stuff?
If yes, yes.
If not, no.


Op zo 17 mrt. 2019 19:14 schreef Rob Krüger <notifications@github.com>:

**Comment by robkruger** [comment]
The only thing I can think of is longer build times

**Comment by Joshua260403** [comment]
Sure thing go ahead and do this

Op zo 17 mrt. 2019 19:17 schreef Rob Krüger <notifications@github.com>:

**Comment by richelbilderbeek** [comment]
Sure, profiling should reach develop and master as well.

In the case this would take up too much time, we can setup Travis to do profiling only on Rob's branch.

**Comment by richelbilderbeek** [comment]
This :rainbow: feels :rainbow: done!
