### ISSUE TITLE
Rotation transfers agents between tiles: this is cool!

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#490]
**Is your feature request related to a problem? Please describe.**

Currently, when we rotate tiles adjacent to other ones, agents can be transferred between tiles.
For example, a tree can be transferred to arctic.

![2019-03-15-224103_1722x910_scrot](https://user-images.githubusercontent.com/2098230/54463518-a9f92780-4773-11e9-8646-deee65aa4c84.png)

We could consider it a bug or a feature. One of our informal testers, Rik Pot, really enjoy this option!

**Describe the solution you'd like**

Decide if we are going to keep this as a feature, I'd say by voting. Before I let do, @Joshua260403, do you agree we should vote on this?

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
Does this only happen when a tile glitches inside of another, because if so, that is a bug and the way this happens should change. Then still we will vote.

**Comment by Joshua260403** [comment]
![Image](https://ibb.co/4JC7BYc) vote on this to happen

**Comment by robkruger** [comment]
I also disagree with how it is now. But @Joshua260403's idea is cool.

**Comment by richelbilderbeek** [comment]
I also thing @Joshua260403 s idea to swipe agents on a rotating tile is cool. Good luck programming that one in :+1:

**Comment by richelbilderbeek** [comment]
Closing the Issue as we've found the neat mechanism @Joshua260403 suggested :rainbow:
