### ISSUE TITLE
Rob: determine big-O complexity

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#495]
**Is your feature request related to a problem? Please describe.**

Currently, we have no idea how the run-time speed scales with the number of agents: if there are x more agents, will the game go x as slow? Or will it go `x^2` times as slow?

**Describe the solution you'd like**

Determine the ![big-O complexity](https://en.wikipedia.org/wiki/Big_O_notation) be filling in this table:

Number of agents|Number of tiles|Run-time speed
---|---|---
10|80|2:49
20|80|1:40
40|80|1:26
80|80|1:35
160|80|2:16

Number of tiles|Number of agents|Run-time speed
---|---|---
10|80|2:31
20|80|2:28
40|80|1:41
80|80|1:44
160|80|1:49

Aim for the hardest measurements to take at least four minutes. Add more and higher values to go over this minimum time.

To do so, improve the use of `--profiling`, for example.`--profiling 1 2` should create a setup with 1 tile and 2 agents.

Modify the Travis script to do all these measurements in one go. Note that we do not need a function profile for each of these combinations: it will help us to pick what to profile instead!

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
My hypothesis is: t = t1 * n_agents^3 + t1 * n_agents * n_tiles
Or something like that :)

Op zo 17 mrt. 2019 12:49 schreef Richel Bilderbeek <notifications@github.com

**Comment by richelbilderbeek** [comment]
My hypothesis is:

```
O(n_tiles, n_agents) = n_agents ^ 2
```

(note that commonly we write down the biggest term only, without constants, else I'd write down:

```
O(n_tiles, n_agents) = (a * n_agents ^ 2) + (b* n_tiles) + c
```

In which a, b and c are constants)

**Comment by robkruger** [comment]
Did I cause [this](https://travis-ci.org/richelbilderbeek/djog_unos_2018/builds/507527193) error? It runs fine at my laptop with those arguments

**Comment by richelbilderbeek** [comment]
You broke the build with an earlier commit:  38bc97c95e69146d23fd87e68e5981e6b49f9b94

No problemo, I'm sure you can fix it :+1:

**Comment by robkruger** [comment]
I don't see the problem 😅

**Comment by richelbilderbeek** [comment]
Running the game is causing a freeze longer than 10 minutes. Try to decrease the time for `--short` or `--profile` :+1:

**Comment by robkruger** [comment]
I did that, but I don't think that's the problem....

**Comment by richelbilderbeek** [comment]
I interrupted the program while in debug mode. It paused in this test:

```c++
  //An agent must be removed if health is below zero
  {
    game g({tile(0, 0, 0, 100, 100, 0, tile_type::grassland)}, { agent(agent_type::cow) } );
    assert(!g.get_agents().empty());
    // Wait until cow starves
    while (!g.get_agents().empty())
    {
      g.process_events();
      while(g.get_agents().size() >= 2){
        g.get_agents().pop_back();
      }
    }
  }
```

I think that will help :+1:

**Comment by Joshua260403** [comment]
[pro tip](https://www.youtube.com/watch?v=I_izvAbhExY)

**Comment by Joshua260403** [comment]
wait no, maybe not

**Comment by robkruger** [comment]
I still don't see the problem😅, the test runs fine on my laptop and the agents get killed...

**Comment by richelbilderbeek** [comment]
Hmmm, perhaps Travis has a different random number generator: perhaps changing the `while` loop in the test to a (long) `for` helps.

Else perhaps maybe your computer is faster than Travis, then calculations based on number of ticks and number of seconds have different ratios...

Hard problem, good luck :+1:

**Comment by robkruger** [comment]
In [this](https://travis-ci.org/richelbilderbeek/djog_unos_2018/builds/507920540) build, I printed m_allow_damage, which was false on Travis, but true on my laptop. I think something is wrong there.

I'll try changing the loop.

**Comment by robkruger** [comment]
I know what was wrong... My Qt ran the release version instead of the debug version...

**Comment by richelbilderbeek** [comment]
Aha, well spotted!

**Comment by robkruger** [comment]
Which value is the Run-time speed?

**Comment by richelbilderbeek** [comment]
[It's complex](https://en.wikipedia.org/wiki/Time_(Unix)#Overview).

**Comment by richelbilderbeek** [comment]
I close this Issue, well done!
