### ISSUE TITLE
Use SFML view

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#496]
**Is your feature request related to a problem? Please describe.**

Currently, we hand-code how the camera behaves. A superior option would be to use a View, which is a part of a common Design Pattern called Model-View-Controller. Not only will this simplify code, this also opens up more avenues, e.g. rotating the camera!

**Describe the solution you'd like**

Use a view, as described in the SFML documentation: [https://www.sfml-dev.org/tutorials/2.5/graphics-view.php](https://www.sfml-dev.org/tutorials/2.5/graphics-view.php)

This is a hard Issue, with two parts:

  1. Try this out first on a simple toy SFML project you write.
  2. Put this in Nature Zen

Any junior can do step 1. Be sure to understand step 1. For the next step, plan one evening with a medior dev to get this into Nature Zen.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
We are using a view

Op zo 17 mrt. 2019 13:04 schreef Richel Bilderbeek <notifications@github.com
