### ISSUE TITLE
Use SFML classes in `sfml_` files only 

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#497]
**Is your feature request related to a problem? Please describe.**

There is a good reason to separate SFML and non-SFML classes: we follow the common Design Pattern called Model-View-Controller. The Model is the game's logic, in e.g. `game`. The View is the display of that Model. These two should definitely remain separate.

However, I find this in `game.cpp`:

```
void game::move_tiles(sf::RenderWindow& window, sfml_camera& camera)
```

**Describe the solution you'd like**

Rewrite this as such that no SFML classes are used in non-SFML units.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
sfml_camera isn't really a sfml class i believe

**Comment by Joshua260403** [comment]
nvm i made that class complicated with view stuff so now it is, i think it would be really complicated to rewrite it. Or maybe mapPixelToCoords will do but im not sure about that one

**Comment by Joshua260403** [comment]
Not sure if this issue is suitable for juniors, also for anyone doing this issue. DO NOT change anything to the camera class, the sf::renderwindow objector the sf::view object. you will most like mess up how everything looks.

**Comment by richelbilderbeek** [comment]
Perhaps you should be the one to tackle this Issue?
