### ISSUE TITLE
Actually use the SFML view

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#498]
**Is your feature request related to a problem? Please describe.**

Currently, we use an SFML view (#496). Using such a view allows us to move the camera in any direction, zoom in/out and rotate.

However, there are a lot of magic numbers in the code that code for the transformation that should be done by the view:

```
void game::spawn(agent_type type, tile t)
{
  // ...
  move_agent_to_tile(a1, t.get_x()/122, t.get_y()/122);
  // ...
}
```

**Describe the solution you'd like**

Replace the magic numbers by usage of the view.

I do not know the exact syntax, but the `122` should be something like the view's zoom factor instead.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
I believe this is also done already

Op zo 17 mrt. 2019 13:14 schreef Richel Bilderbeek <notifications@github.com

**Comment by richelbilderbeek** [comment]
Cool! In which branch are there no more magic numbers? I see in `develop` they are still around.

**Comment by Joshua260403** [comment]
Also, the 122 should not change at all ever, the 122 is the translation from the actual sfml view coordinate to tile placement coordinate

**Comment by Joshua260403** [comment]
everything is placed in sfml with mapPixelToCoords(m_window) meaning it is already mapped to the view

**Comment by Joshua260403** [comment]
will reopen if zooming does not work correctly after all

**Comment by richelbilderbeek** [comment]
Fantastic! Go team :1st_place_medal:
