### ISSUE TITLE
Remove all those GitHub Issue templates

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#499]
**Is your feature request related to a problem? Please describe.**

When creating a new Issues, I get a list of six options. Only the third one is useful in practice:

![2019-03-17-131501_1920x1056_scrot](https://user-images.githubusercontent.com/2098230/54490735-cd79ba80-48b8-11e9-9e39-325c2f1c4a20.png)

**Describe the solution you'd like**

Remove all Issue templates except 'Feature request' and 'New Type'.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
New type is used too

Op zo 17 mrt. 2019 13:30 schreef Richel Bilderbeek <notifications@github.com

**Comment by richelbilderbeek** [comment]
Thanks, updated Issues :+1:
