### ISSUE TITLE
Allow player to zoom in and out smoothly

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#501]
Depends on:

 * [x] #498 

**Is your feature request related to a problem? Please describe.**

Currently, we use an SFML view (#496) but do not take it into account of all our calculations/transformations (#498). If the latter Issue is done, it **should** be easy to allow the player to zoom in and out.
 

**Describe the solution you'd like**

Let the player zoom in and out with, say, `z` and `c` (I reserve `q` and `e` for rotation).

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
also with scrolling would be nice

**Comment by richelbilderbeek** [comment]
You mean: 'player should be able to zoom in and out fluidly'?

**Comment by Joshua260403** [comment]
kinda

**Comment by Joshua260403** [comment]
take for example how the scrolling on this very webpage works

**Comment by Joshua260403** [comment]
(in chrome, dont know about duckduckgo scrolling)

**Comment by richelbilderbeek** [comment]
Renamed Issue :+1:

**Comment by Joshua260403** [comment]
Wouldn't Z and X make more sense? Or . and ,?
Leaving the keybind up to the person who does this issue (but make sure to tell me because i document all of the keybinds)

**Comment by Joshua260403** [comment]
Do this after #502

**Comment by Joshua260403** [comment]
The sfml version on travis has to be updated first

**Comment by richelbilderbeek** [comment]
To [quote me](https://github.com/richelbilderbeek/djog_unos_2018/issues/461#issuecomment-479524807):

> Basically we are stuck with the current SFML version on Travis [1]. I use this trick: 

```c++
  #if(SFML_VERSION_MINOR > 3)
  // Newer version
  m_header.setFillColor(sf::Color::Magenta);
  m_header.setOutlineColor(sf::Color::Green);
  m_header.setOutlineThickness(5);
  #else
  // Older version
  //Only relevant for Travis
  m_header.setColor(sf::Color::Green);
  #endif
```

> On Travis, you may consider `#if`-ing out the code that uses the latest SFML stuff.
>
>  * [1] Note that it is a very commonly used version of SFML, as it is the [Long Term Stable Ubuntu distro called 'Trusty Tahr'](https://en.wikipedia.org/wiki/Ubuntu_version_history#Ubuntu_14.04_LTS_(Trusty_Tahr)).

**Comment by richelbilderbeek** [comment]
I do not since when this is available, but we could start using the new Xenial distro, according to [the Travis documentation](https://docs.travis-ci.com/user/reference/xenial/)!

**Comment by richelbilderbeek** [comment]
The status of this Issue is unclear to me. I'll just unassign everyone :smirk:
