### ISSUE TITLE
Allow player to rotate camera

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#502]
Depends on:

 * [ ] #501

**Is your feature request related to a problem? Please describe.**

When the camera can zoom in and out, it **should** be easy to allow the player to rotate the camera.

**Describe the solution you'd like**

Let the player rotate the camera left and right, say, `q` and `e` (`z` and `c` are already used for zooming in and out).

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
Why would #501 have to be done first, i think this one is easier
