### ISSUE TITLE
Game design: agents should not fall off tiles yes or no?

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#503]
**Is your feature request related to a problem? Please describe.**

Currently, agents fall off tiles, for example, this poor crocodile:

![suicide_crocodile](https://user-images.githubusercontent.com/2098230/54491399-9ad2c080-48be-11e9-8309-e7a6bfd8ced0.png)

**Describe the solution you'd like**

Actually, I think this a feature, not a bug: one needs to care for the creatures now!

@Joshua260403: what do you think: is this a feature (agents fall off), or a bug?

 * If agents should fall off tiles, this Issue can be closed
 * If agents should not fall off tiles, let us know :1st_place_medal: 

**Describe alternatives you've considered**

None.

**Additional context**

Earlier Joshua decided to let agents not fall off. But now the movement is different, so perhaps he does like the current behavior now.

**Comment by Joshua260403** [comment]
This was going to be a feature, but now i think about it it should be fixed

Op zo 17 mrt. 2019 14:13 schreef Richel Bilderbeek <notifications@github.com

**Comment by richelbilderbeek** [comment]
OK, updated Issue to say you agreed :rocket:

**Comment by richelbilderbeek** [comment]
Actually, I think this a feature, not a bug: one needs to care for the creatures now!

@Joshua260403: what do you think: is this a feature (agents fall off), or a bug?

 * If agents should fall off tiles, this Issue can be closed
 * If agents should not fall off tiles, let us know :1st_place_medal:
