### ISSUE TITLE
When agent dies, a corpse (or something similar) should be displayed temporarily

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#504]
**Is your feature request related to a problem? Please describe.**

Currently, when an agent dies, it just vanishes. In reality, a corpse (or similar) appears.

**Describe the solution you'd like**

When an agent dies, show something to indicate that it died temporarily. 

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
if you don't want to add new textures: just turn the agent upside down

**Comment by Joshua260403** [comment]
lol we could add vultures that eat the corpses

**Comment by richelbilderbeek** [comment]
An upside-down agent should be a fine start. When that's in, we'll reconsider doing something more fancy.

Worms eat corpes :-)

**Comment by robkruger** [comment]
I'll add a new texture and use that instead

**Comment by Joshua260403** [comment]
that was unexpected
