### ISSUE TITLE
When a new agent appears, stars (or something similar) should appear temporarily

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#505]
**Is your feature request related to a problem? Please describe.**

Currently, when a new agent appears, it just ... appears.

In most games, this is displayed somehow with stars that disappear after a short time.

**Describe the solution you'd like**

When a new agent spawn, display this happy fact temporarily.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
Hmm, don't know about this one. Kinda like the idea that it just spawns without any special effects or whatever:
1) Never seen a game do that
2) It's more zen without special star confetti party for every agent that spawns

**Comment by richelbilderbeek** [comment]
If you disagree, well, you are the boss :+1:

Will close this Issue :rainbow:
