### ISSUE TITLE
Acknowledge "rik pot"

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#507]
I don't know who he is, but apparently he tests nature zen.

Seeing the fact that @richelbilderbeek opened multiple issues suggested by "rik pot" we should put him in the about screen under the header "pre-release tester" or "external tester" or something like that.

**Comment by richelbilderbeek** [comment]
Agreed 'External tester' sounds fine. Of course, all other testers we give the Steam keys to before release should also be mentioned.

**Comment by richelbilderbeek** [comment]
Done, put in #514
