### ISSUE TITLE
Vote: hackathon Sunday June 9th?

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#508]
**Is your feature request related to a problem? Please describe.**

For #479 we learned that the deadline to open up our Steam page is June 13th. To tidy up the last things, I suggest we (which is only Team Octane) work on Sunday 9th (the day after it is the second day of Pinksteren) from 12:00-late at De Jonge Onderzoekers. There will be pizza. 

**Describe the solution you'd like**

Let me know if you are interested. Or suggest a better date.

**Describe alternatives you've considered**

None.

**Additional context**

I have asked Carleen of DJO, but have not gotten a reply yet.

**Comment by Joshua260403** [comment]
Yes

**Comment by robkruger** [comment]
Yes

**Comment by richelbilderbeek** [comment]
Will be moved as not all that want to be there, can be there.
