### ISSUE TITLE
Hackathon Saturday May 25th 18:00-late

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#511]
**Is your feature request related to a problem? Please describe.**

For #479 we learned that the deadline to open up our Steam page is June 13th. To tidy up the last things, I suggest we (which is only Team Octane) work on Saturday May 25th from 18:00-late at De Jonge Onderzoekers. There will be pizza :pizza:. 

**Describe the solution you'd like**

Let me know if you are interested. Or suggest a better date.

**Describe alternatives you've considered**

None.

**Additional context**

I have not asked Carleen of DJO yet, but I predict it will be fine :rainbow:

**Comment by Joshua260403** [comment]
Still, sure

Op vr 22 mrt. 2019 09:14 schreef Richel Bilderbeek <notifications@github.com

**Comment by Rijk-van-Putten** [comment]
I can't come on June 1, 2, 8 and 9

**Comment by martje127** [comment]
I try to be there ...

**Comment by richelbilderbeek** [comment]
May 25th is the new date!

**Comment by RafayelGardishyan** [comment]
I will come on 25 may

**Comment by richelbilderbeek** [comment]
Cool, May 25th 18:00 we'll see:

Name|Will be present Yes/No/Unknown
---|---
Enzo|Unknown
Isis|Unknown
Jan|Maybe
Joshua|Yes
Mart|Yes
Rafayel|Yes
Rijk|Yes
Rob|Unconfirmed
Same|Unconfirmed

**Comment by same-drenth** [comment]
Count me in
