### ISSUE TITLE
Remove agent_type::none

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#512]
**Is your feature request related to a problem? Please describe.**

I've never observed a use of a null-type `agent_type`.

Take for example this line:

```c++
  agent nearest_f(agent_type::none, INFINITY, INFINITY);
```

The line above indicates that no agent is yet found,

A superior way to indicate the same:

```c++
std::vector<agent> nearest_agent;
```

Drawback of the current approach are abominations like this:

```c++
  //An agent of type none is used when a 'null' agent is needed
  assert(type != agent_type::none || type == agent_type::none);
```

I suggest to do ourselves a favour and remove `agent_type::none`.

**Describe the solution you'd like**

Remove `agent_type::none`. When a null-agents is needed, use an empty `std::vector<agent>` instead.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
It is used in saving and loading and is an inportant part of making the
game work on incorrect save files (for when people try to mod the game)

Op vr 22 mrt. 2019 18:52 schreef Richel Bilderbeek <notifications@github.com

**Comment by Joshua260403** [comment]
Replace the usages with a cow

**Comment by richelbilderbeek** [comment]
Well done @AramPetiet, but it did break [the build due to OCLint](https://travis-ci.org/richelbilderbeek/djog_unos_2018/builds/525104680#L1761).

Address the OCLint feedback, then push again, then move this Issue in 'To be merged with develop' :+1:
