### ISSUE TITLE
Create credits

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#514]
**Is your feature request related to a problem? Please describe.**

We need to acknowledge people properly in the About screen.

Rules are:

 * Be generous with adding people
 * Do not over-attribute glory: when in doubt, don't

This is a sensitive Issue, therefore I do it.

**Describe the solution you'd like**

**Describe alternatives you've considered**

None.

**Additional context**

After this list is generally agreed upon, we'll add it to the About screen.

**Comment by richelbilderbeek** [comment]
This is a work in progress. I will consult team members **in person** . Do not reply below.

## Project manager

Richel Bilderbeek
Anton Hensen

## Developers

### Medior developers

Joshua van Waardenberg
Rafayel Gardishyan
Rob Kruger

### Junior Developers

Enzo de Haas
Isis Reinders
Jan Derk Kotlarski
Jolien Gay
Mart Prenger
Rijk van Putten
Same Drenth
Tom Stuivenga

## Test

### Lead test

Mart Prenger

### Beta testers

[none yet]

### Informal testers

Rik Pot

## Graphics

Same Drenth

## Sound

Jan Kotlarski

## Former Team Members

Annabel Belliard
Anne Hinrichs
Elles Jetten
Fauve Setrodinomo
Jana Riederer
Jorn Prenger
Giorgio Boccarella
Koen Prins

**Comment by Joshua260403** [comment]
Hey but wait a second, anton is a medior too (resulted from voting)

Op vr 22 mrt. 2019 19:43 schreef Richel Bilderbeek <notifications@github.com

**Comment by richelbilderbeek** [comment]
It's fine as it is :+1:
