### ISSUE TITLE
Declutter and refunctionalize sfml_resources.h and sfml_resources.cpp

### ISSUE THREAD

**Issue by janderkkotlarski** [richelbilderbeek/djog_unos_2018#521]
ISSUE:
sfml_resources.h and especially sfml_resources.cpp have some cluttering issues that oclint signals about.
The class could use some flexibility in order to improve the access by other classes.

WHAT TO DO:
Add some handy functions that declutter some of the clutter and that also improve the access by other classes.
Also get rid of clunky and reptitive code.

Write some handy tests in the testing area.

This issue depends on issue #525

**Comment by Joshua260403** [comment]
I don't see the problem, could you cite OClint for me.

**Comment by Joshua260403** [comment]
Depends on what?

**Comment by Joshua260403** [comment]
I looked at your 5 most recent build and all errors are something else than this, oclint exited with 0 every build i looked at (for as far as i know)
