### ISSUE TITLE
operator== on tiles should work as expected

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#523]
Depends on:

 * [ ] #522 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Joshua260403** [comment]
I assume this is wip?

Op za 23 mrt. 2019 13:46 schreef Richel Bilderbeek <notifications@github.com

**Comment by richelbilderbeek** [comment]
Yep, it even has been fixed already :+1:

**Comment by Joshua260403** [comment]
What was the problem?

**Comment by Joshua260403** [comment]
Oh you just wanted a test

**Comment by richelbilderbeek** [comment]
Tile constructor had changed, had nothing to do with #522...
