### ISSUE TITLE
.qrc resource management limits storage space for data files

### ISSUE THREAD

**Issue by janderkkotlarski** [richelbilderbeek/djog_unos_2018#525]
ISSUE:
Trying to add about 2 or more Megabytes of file data using the .qrc resource management system in QT makes the compiler complaining about having to make an executable file of over a 100 Megabytes and not building it and leaving an error message.

WHAT TO DO:
Find a different way of handling and moving data files that circumvents the .qrc resource management system and removing the unnecessary limit on the total file data size.

**Comment by richelbilderbeek** [comment]
Perhaps adding a second resource file helps?

Do add it to `djog_unos_2018.pri` in the `RESOURCES` section.

**Comment by Joshua260403** [comment]
There should be an argument in the appveyor file that you might be able to
use

Op ma 25 mrt. 2019 13:58 schreef Richel Bilderbeek <notifications@github.com

**Comment by Joshua260403** [comment]
Wait a second, i am pretty sure i added `CONFIG += resources_big` once, to solve the appveyor memory problem, but i can't find it back. That might be the reason appveyor runs out of memory every now and then.

**Comment by Joshua260403** [comment]
@janderkkotlarski Try adding CONFIG += resources big before anything else please

**Comment by richelbilderbeek** [comment]
On [Travis](https://travis-ci.org/richelbilderbeek/djog_unos_2018/builds/510946730#L1739) there is a clear error message:

```
/home/travis/build/richelbilderbeek/nature_zen/resources/Barachem_Tranquil_Canopy.ogg
djog_unos_2018: sfml_resources.cpp:403: void copy_file(const string&, const string&): Assertion `QFile::exists(base_name)' failed.
```

Is that unrelated to this Issue?

**Comment by Joshua260403** [comment]
I asked him about that on his commit too, there's some function @janderkkotlarski added that i am dubious about.

**Comment by Joshua260403** [comment]
It also might have something to do with #521, which i will still have to investigate.

**Comment by Joshua260403** [comment]
I'd like to introduce you to my new label (just for my vision, you may remove it if you don't like it and laughed at the joke)

**Comment by Joshua260403** [comment]
Seems to work perfectly fine on travis, please cite the compiler

**Comment by janderkkotlarski** [comment]
I do not know how to explain well enough what the problem is, just remove me as a collaborator, I'm done.
