### ISSUE TITLE
Monday April 8th 16:00-17:00 talk about memristive devices

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#526]
A cutting-edge and free talk at the Zernike Campus. If at least two members join, we'll go. See below

 * What: Faculty Spotlight: CogniGron: Materials and systems for cognitive computing as a quest for sustainability, by Prof. Beatriz Noheda 
 * When: April 8th 2018, 16:00
 * Where: Room 105, Bernouilliborg

Note that the dean will talk first. Most people experience this part as very boring!

## Full text

Programme April 8th | 4 p.m. | room 105, Bernouilliborg
> Introduction and latest news from the faculty board

> Speaker: Prof. Beatriz Noheda  

Information Technologies are already responsible for more than 10% of the world energy consumption, highlighting an urgent need to develop computers that are able to classify data efficiently. For that, the scientific community has looked into emulating the brain and its amazing efficiency for pattern recognition. Although neuromorphic computing concepts have been put forward half a century ago, the understanding that transistors and standard circuit elements will not allow sufficient progress in this direction, is recent.

This has spurred an increasing activity on so-called memristive devices, which can implement in a cognitive computer the functions that are currently being performed by artificial neural-network algorithms on traditional computers, and with a fraction of the energy. It is clear that the quest for low-power cognitive computing needs a holistic approach that starts with the use of materials with intrinsic plasticity.

CogniGron has been born as one of the first initiatives world-wide to bring material scientists, physicists and mathematicians to work together with computer and artificial intelligence experts in this exciting journey.

**Comment by martje127** [comment]
I will see if I will be there...

**Comment by richelbilderbeek** [comment]
We cool, with @same-drenth and @annehinrichs22
