### ISSUE TITLE
Don't use function std::stoi (fix appveyor)

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#529]
Currently all of our appveyor builds are failing, this is because appveyor doesn't know what std::stoi is. I wan't appveyor back for quick (secondary) testing, testing on windows and testing in release mode.

Find out a way to fix appveyor by for example:
- not using stoi (find replacement or make a function of your own)
- changing the appveyor cpp version (not recommended)
- not using the stoi function in release mode (not recommended)

if you are going to create you own function, i recommend taking the string, breaking it into pieces (chars) and change each char to a int with ascii values.

**Comment by robkruger** [comment]
I'm already working on the first alternative.

**Comment by Joshua260403** [comment]
mine too, this is thus fixed
