### ISSUE TITLE
Make Travis script topic-branch dependent

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#533]
**Is your feature request related to a problem? Please describe.**

Travis topic branches need to be fast. But due to its many tasks, it's getting clogged up.

For example, this is part of `.travis.yml`:

```
  # helgrind: takes too long
  # - travis_wait 50 valgrind --tool=helgrind --log-file=helgrind.log -v ./djog_unos_2018 --short 1
  # - cat helgrind.log
```

**Describe the solution you'd like**

Do some branch-specific things in the Travis script:

 * Profiling: Rob
 * Memory checking: ?

Do everything in develop and master.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by richelbilderbeek** [comment]
Easy, see [here](https://stackoverflow.com/a/37544452)!

**Comment by richelbilderbeek** [comment]
* [ ] Let this code be run on `richel`'s branch:

```
  - travis_wait 50 valgrind --tool=helgrind --log-file=helgrind.log -v ./djog_unos_2018 --short 1
  - cat helgrind.log
```

 * [ ] Let this code be run on `rob`'s branch:

```
  - qmake djog_unos_2018.pro
  - make release
  - time ./djog_unos_2018 --profiling 350 350
  - ./djog_unos_2018 --profiling 350 350
  - gprof djog_unos_2018 > gprof.log
  - head gprof.log -n 1000
```

**Comment by richelbilderbeek** [comment]
@Martje127: you can do this!

**Comment by Joshua260403** [comment]
Although you may have to read more docs

Op do 4 apr. 2019 16:24 schreef Richel Bilderbeek <notifications@github.com

**Comment by martje127** [comment]
i did it, if you find any eror's say it
