### ISSUE TITLE
20180921: using TODO to see what has to be done in the code

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#54]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to see where work is needed in the code really quickly.

**Describe the solution you'd like**
TODO enabled for everyone

**Describe alternatives you've considered**
Not enabling it

**Additional context**
In Qt: Help>About plugins -> Look for "Todo (experimental)" and enable it

To use it create a comment (by typing #) and add <TODO> behind it followed by whatever has to be done.

**Comment by richelbilderbeek** [comment]
@Joshua260403: would you volunteer to demonstrate this topic this Friday to the group at at 20:30? If yes, I will arrange a beamer.

**Comment by Joshua260403** [comment]
sure

**Comment by richelbilderbeek** [comment]
You are hereby scheduled to do so :rainbow:

**Comment by Joshua260403** [comment]
[Tutorial](https://github.com/richelbilderbeek/djog_unos_2018/blob/master/doc/to-do.md)

**Comment by richelbilderbeek** [comment]
@Joshua260403 gave a clear presentation how this works on Friday. We were unsure how this will work out (as Issues already serve a similar purpose), so we voted to try this out.
