### ISSUE TITLE
Profiling: reduce use of can_eat

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#542]
**Is your feature request related to a problem? Please describe.**

In [recent Travis CI build logs](https://travis-ci.org/richelbilderbeek/djog_unos_2018/builds/516057567#L1894) we can observe that 44% of all run-time is spent in `can_eat`.

Now we can rationally speed up the program, let's reduce the number of times it is called!

What we can see, is that when `can_eat` is called for any `agent`, `can_eat` will always return the same `std::vector`. We can store that `std::vector` internally in an `agent`. 

**Describe the solution you'd like**

 * [x] Write down the current run-time speed for the profiling setup here:

Measured|Runtime speed
---|---
Before|6:02

 * [x] Within an `agent` add to the `private` section:

```c++
/// The types of agents this agent can eat
/// Added as a result of profiling
std::vector<agent_type> m_prey;
```

 * [x] Initialize `m_prey` at the constructor of `agent`, by calling `can_eat`
 * [x] Replace all other calls to `can_eat` by using `m_prey` instead

Do not make a getter for `m_prey`! It's an implementation detail that should not be exposed.

 * [x] Measure the speed increase

Measured|Runtime speed
---|---
Before|6:02
After|2:40

   * If speed is reduced, undo all changes!
   * If speed is increased, keep the changes.

**Describe alternatives you've considered**

None.

**Additional context**

None,

**Comment by richelbilderbeek** [comment]
@robkruger: I assign you this Issue. Feel free to delegate it to others, as long as you take the responsibility to ensure the code is actually sped up!

**Comment by robkruger** [comment]
The program is sped up significantly👍

**Comment by richelbilderbeek** [comment]
I see [here](https://travis-ci.org/richelbilderbeek/djog_unos_2018/builds/524608111#L2072) the new speed is 2m12. 

Well done!
