### ISSUE TITLE
Segfaults on windows

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#545]
The code 3 i had is now occuring on almost every windows device. I managed to find out it is a segmentation fault in the eat function. We need to fix this because otherwise almost nobody can do anything!

Multiple people may assign to this, however, make sure to communicate everything you do!

**Comment by richelbilderbeek** [comment]
On which branch can I take a look? Or is this already fixed?

**Comment by Joshua260403** [comment]
My branch is furthest with solving this

Op ma 8 apr. 2019 20:32 schreef Richel Bilderbeek <notifications@github.com

**Comment by richelbilderbeek** [comment]
Will take a look tonight. Expect some extra asserts :+1:

**Comment by richelbilderbeek** [comment]
I see the build already fails on an `assert` in [this Travis log](https://travis-ci.org/richelbilderbeek/djog_unos_2018/jobs/517644081#L1741).

@Joshua260403: 
 * may it be you forgot to test this in Debug mode? If yes, I think you may want to honor to fix this yourself
 * still want me to continue to look into this? Just to be sure, I can fix this tomorrow as well :+1:

**Comment by Joshua260403** [comment]
i tried litteraly everything so no it is not possible i missed this

Op di 9 apr. 2019 17:38 schreef Richel Bilderbeek <notifications@github.com

**Comment by richelbilderbeek** [comment]
Yeah, I expected you did try everything :1st_place_medal:. 

Maybe my branch is further ahead now...

What about you fix the error on my branch (on your branch), then I'll fix Tha Bug?

**Comment by Joshua260403** [comment]
Which bug?

Op di 9 apr. 2019 17:52 schreef Richel Bilderbeek <notifications@github.com

**Comment by Joshua260403** [comment]
What is the error exactly?

**Comment by richelbilderbeek** [comment]
Current error is [a failed assert](https://travis-ci.org/richelbilderbeek/djog_unos_2018/jobs/517644081#L1741). Up for fixing that one? No == fine as well, I just prefer you getting more commits :+1:

**Comment by Joshua260403** [comment]
Sure, as soon as the segfault is fixed!

Op di 9 apr. 2019 17:56 schreef Richel Bilderbeek <notifications@github.com

**Comment by richelbilderbeek** [comment]
Okidokie, I will fix both then :rainbow:

**Comment by richelbilderbeek** [comment]
LOL:

```c++
// WARNING SEGFAULT OVER HERE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

I'm loving it :rainbow:

**Comment by richelbilderbeek** [comment]
OK, refactored, simplified, documented and const-corrected the code. Maybe the segfault is gone, but need someone to check.

@Joshua260403: could you merge my branch to yours to see if this is fixed?

 * If fixed, close the Issue
 * If not, assign me back again, will continue tomorrow

**Comment by richelbilderbeek** [comment]
Tip: use `--god`, else the game closes immediately.
