### ISSUE TITLE
remove ubsan

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#55]
# Issue:
- OS: Windows 10
- Compiler: mingw530_32
- Qt Version: 5.9.1
- SFML Version: 2.5.0

### Issue Description
cannot find -lubsan

### How to reproduce:
run the program

**Comment by Joshua260403** [comment]
ubsan is for linux only and not for mingw, the compiler every windows user is using....

**Comment by Joshua260403** [comment]
so i think well have to remove it and maybe find an alternative

**Comment by richelbilderbeek** [comment]
Also here, in the Qt Project file, one may put it between `!win{}`:

```
!win{
  LIBS += -lubsan
}
```

**Comment by Joshua260403** [comment]
but if that is done, all other uses of ubsan will cause an error

**Comment by richelbilderbeek** [comment]
I will fix it in 15 minutes.

**Comment by Joshua260403** [comment]
That will be tonight or tommorow after school

**Comment by richelbilderbeek** [comment]
WOAH! Fixed it!

**Comment by Joshua260403** [comment]
nope #60
