### ISSUE TITLE
Add angle class

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#553]
**Is your feature request related to a problem? Please describe.**

A `tile` has both a coordinate and an angle. Both are `double`s, thus easily confused.

**Describe the solution you'd like**

Make a very simple `angle` class with a `test_angle` functions.

```c++
void test_angle()
{
  const double x = 123.456;
  const angle a(x);
  assert(a.get_angle() == x);
}
``` 

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by Joshua260403** [comment]
I don't think this is necessary

Op vr 12 apr. 2019 21:17 schreef Richel Bilderbeek <notifications@github.com

**Comment by richelbilderbeek** [comment]
Just convinced @Joshua260403 of The Right Thing To Do :rainbow:

**Comment by martje127** [comment]
@richelbilderbeek thinks this is beyond the next deadline. Closing ...
