### ISSUE TITLE
Cleanup 'merge_tiles'

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#562]
**Is your feature request related to a problem? Please describe.**

Currently, we have:

```c++
void game::merge_tiles() { //!OCLINT must simplify
  for (int i = 0; i < n - 1; ++i)
  {
    for (int j = i + 1; j < n; ++j)
    {
      if (/* */) { continue; }
      //...
      return; //!OCLINT I don't know an alternative;
    }
  }
}
```

This can be cleaned up:

**Describe the solution you'd like**

 * [x] Replace `return` by `i = n; j = n;`, which causes ending all for loops. There is an error in my suggestion, find one of the multiple ways to do so. Remove the OCLint
 * [x] Remove `//!OCLINT must simplify` iff accepted by OCLint

All tests must pass.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by richelbilderbeek** [comment]
I see in the code:

```c++
      return; //!OCLINT I don't know an alternative;
      i = n; j = n;
```

OCLint will complain, as the second line is never call. I think the `return` can be safely removed...

Remember: all tests should keep passing :+1:

**Comment by Joshua260403** [comment]
nonononononono, that caused a bug remember. Make sure you don't break
anything

Op vr 3 mei 2019 17:58 schreef Richel Bilderbeek <notifications@github.com>:
