### ISSUE TITLE
Add tile move sound

### ISSUE THREAD

**Issue by janderkkotlarski** [richelbilderbeek/djog_unos_2018#564]
WHAT TO DO:
Make a tile move sound and incorporate it into the game.

ATTENTION:
When merging, the selected tile moves as well.
Make it so that then only the merge sound plays.

**Comment by Joshua260403** [comment]
the side note is a bad idea, when merging, both the movement and the
merging sounds should play

Op vr 19 apr. 2019 13:27 schreef Jan Derk Kotlarski <
notifications@github.com>:

**Comment by janderkkotlarski** [comment]
Together?
Or first the move sound and then the merge sound?

**Comment by richelbilderbeek** [comment]
@Joshua260403: cool to see you -as always- check these Issues. For now, I suggest to let @janderkkotlarski decide and get 'something' working. After that, then we can create new Issues. Could you agree with that?

**Comment by Joshua260403** [comment]
move sound as soon as it start to move, merge when it merges

Op vr 19 apr. 2019 20:07 schreef Jan Derk Kotlarski <
notifications@github.com>:

**Comment by Joshua260403** [comment]
im just suggesting something to make the game very good before the deadline
:four_leaf_clover:

Op za 20 apr. 2019 10:29 schreef Richel Bilderbeek <notifications@github.com

**Comment by richelbilderbeek** [comment]
I understand. We agree on what must be done *in the end*. I just suggest to work from big/corse to small/details first.

**Comment by richelbilderbeek** [comment]
Well done!
