### ISSUE TITLE
Move to food is incorrect

### ISSUE THREAD

**Issue by robkruger** [richelbilderbeek/djog_unos_2018#568]
**Is your feature request related to a problem? Please describe.**
In #543 I changed how the agent moves to food. The program runs faster now (probably), but the agents move incorrect.

**Describe the solution you'd like**
Fix the function so that they walk in the correct direction.

**Comment by richelbilderbeek** [comment]
I always felt the new way to move is a feature!

I suggest to leave it so and close this Issue, up until The Big Joshua disagrees :+1: 

OK?

**Comment by Joshua260403** [comment]
the agents should not run in straight zig-zag-ing lines like made cows

Op vr 3 mei 2019 18:22 schreef Richel Bilderbeek <notifications@github.com>:
