### ISSUE TITLE
Undefined references

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#57]
# Issue:
- OS: Windows 10
- Qt Version: 5.9.1
- Compiler: MinGW530_32
- SFML Version: 2.5.0

### Issue Description
[See travis log](https://travis-ci.org/richelbilderbeek/djog_unos_2018/builds/429607001)

### How to reproduce:
Run my version of djog_unos_2018.pro

**Comment by richelbilderbeek** [comment]
WOAH! Fixed it!

**Comment by Joshua260403** [comment]
@richelbilderbeek did you remove "win32{" and "}" before and after the giant LIBS section?

**Comment by richelbilderbeek** [comment]
I put your giant LIBS section in `win32{ }`, I put the original LIBS section in the `unix:!macx{ }`parts. You can see it [in this commit](https://github.com/richelbilderbeek/djog_unos_2018/commit/71c4a6cde7dc8ef6eb31019f0b7eb1323c89b7e0).
