### ISSUE TITLE
Teach Aram how to show up as a collaborator

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#570]
**Is your feature request related to a problem? Please describe.**

Although @AramPetiet already did quite some stuff, he does not show up as a [contributor](https://github.com/richelbilderbeek/djog_unos_2018/graphs/contributors). I bet he instead works on a different account name.

Someone should teach him how to get the proper credit.

**Describe the solution you'd like**

Show how to get the proper credit.

I think one needs to do two things:

 * [x] In Windows, go to 'Referentiebeheer' and delete the GitHub credentials
 * [x] (unsure about this one) run the same git commands in Git Bash as [to_richel](https://github.com/richelbilderbeek/djog_unos_2018/blob/master/scripts/to_richel)

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by AramPetiet** [comment]
Done 💯
