### ISSUE TITLE
Inform Jan about Aram

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#571]
**Is your feature request related to a problem? Please describe.**

Currently, @janderkkotlarski is lead sound/music. On April 12th however, @AramPetiet joined our team. Aram is also interested in doing this.

**Describe the solution you'd like**

 * [x] @richelbilderbeek will discuss with Jan on Thursday how to set this up
 * [x] @richelbilderbeek will discuss with Aram on Friday what came out of this

**Describe alternatives you've considered**

Exchanging their emails, but I see no clear advantage there.

**Additional context**

With some luck, they will meet at the Hackathon.

**Comment by AramPetiet** [comment]
done :D
