### ISSUE TITLE
DJO closed at May 30th and 31st

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#572]
DJO will be closed at Thursday May 30th and Friday May 31st :cry:

**Comment by Joshua260403** [comment]
what about today (thursday 25) and tomorrow?

Op wo 24 apr. 2019 16:10 schreef Richel Bilderbeek <notifications@github.com

**Comment by antonhensen81** [comment]
@Joshua260403 Business as usual. Will see you on Friday and Thursday is regular as well

**Comment by richelbilderbeek** [comment]
OK, we were open and Team Octane was there :+1:
