### ISSUE TITLE
Remove the confirm_tile_move function from the sfml_game class

### ISSUE THREAD

**Issue by janderkkotlarski** [richelbilderbeek/djog_unos_2018#574]
An issue of non-functional code, this function does nothing and eats up precious coding space.
Delete this function in the cpp and header files of sfml_class.

**Comment by richelbilderbeek** [comment]
I guess this is just confusion: indeed it has/had no code coverage.

Currently, it is tested and I confirmed (using an `assert(1==2);`) that the function is actually called.

Thanks @janderkkotlarski for checking, but I hope to have convinced you that the function must remain in, and this Issue can be closed :rainbow: 

Stay vigilant :+1:
