### ISSUE TITLE
Implement 'collect_all_game_states'

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#578]
**Is your feature request related to a problem? Please describe.**

Currently, there is no way to collect all `game_state`s. This is useful in debugging, so it must be added.

**Describe the solution you'd like**

 * [x] Implement `collect_all_game_states`. Search for `collect_all_` to peek how to do so

 * [x] Activate this test and make it pass:

```c++
  //#define FIX_ISSUE_578
  #ifdef FIX_ISSUE_578
  //Can collect all game states
  {
    const std::vector<game_state> v = collect_all_game_states();
    assert(v.empty());
  }
  #endif //FIX_ISSUE_578
```

Activate it by removing the comments from `//#define FIX_ISSUE_578`

 * [x] Remove the `#` lines

Done!

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by richelbilderbeek** [comment]
Someone needs to do the last the items of the Issue. Good luck :+1:

**Comment by AramPetiet** [comment]
Done! :100:
