### ISSUE TITLE
Profiling: why 4x as slow?

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#584]
**Is your feature request related to a problem? Please describe.**

I see in [a Travis build log](https://travis-ci.org/richelbilderbeek/djog_unos_2018/builds/527323674#L2074) that the profile takes 9 instead of 2 minutes to complete.

**Describe the solution you'd like** 

 * [x] Find out why this is the case
 * [x] Fix it, or share your thoughts with @richelbilderbeek

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by robkruger** [comment]
Sorry for the late reply, I missed this issue. The reason for this is that I increased the number of agents and tiles when profiling to get more precise results.

**Comment by richelbilderbeek** [comment]
I'll close this one, new bottleneck is in [agent::damage_own_type](https://travis-ci.org/richelbilderbeek/djog_unos_2018/builds/539333996#L2259): I'll create a new Issue for it :+1:
