### ISSUE TITLE
Disable sound effects by default

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#586]
**Is your feature request related to a problem? Please describe.**

We have our first sound effects. Cool!

However, when we work on the game, that should be in silence.

**Describe the solution you'd like**

Like the music, the sound effects should be off by default. Only if `--music` is added as a runtime argument should we hear both music and sound. 

If you think it'd be better to split sounds and music, add a `--sounds` as a flag to enable the sounds.

**Describe alternatives you've considered**

None.

**Additional context**

**Comment by Rijk-van-Putten** [comment]
Fixed travis
