### ISSUE TITLE
Not running on JOG laptop

### ISSUE THREAD

**Issue by AramPetiet** [richelbilderbeek/djog_unos_2018#592]
I have tried on 2 laptops and on both the following problem occurs:

![image](https://user-images.githubusercontent.com/49567994/57162748-8192be80-6def-11e9-9554-15ec1616a8af.png)

**Comment by AramPetiet** [comment]
I suspect it has to do with SFML, but not sure. We worked around by using my laptop instead, but should be addressed.

**Comment by AramPetiet** [comment]
We have verified it works on other machines with the same latest of development branch

**Comment by richelbilderbeek** [comment]
`std::bad_alloc` usually indicates a lack of memory ...

**Comment by richelbilderbeek** [comment]
I guess the new graphics and sound consume too much memory (for now). 

What happens when running in debug mode? 

If I am right, the exception is thrown in `sfml_resources` :grin:

**Comment by Joshua260403** [comment]
I believe appveyor had this issue too, i thought i added a CXX_FLAG for
that but last time i checked it was gone. You should try googling for
something like: resources_big qt creator

Op za 4 mei 2019 11:56 schreef Richel Bilderbeek <notifications@github.com>:

**Comment by Joshua260403** [comment]
```Add CONFIG += resources_big into the *.pro file.```
from [
https://stackoverflow.com/questions/12231266/qt-compiling-error-out-of-memory-allocating-134-mb-cc1plus-exe-not-found](https://stackoverflow.com/questions/12231266/qt-compiling-error-out-of-memory-allocating-134-mb-cc1plus-exe-not-found)

Op za 4 mei 2019 12:45 schreef Joshua van Waardenberg <
joshuavwaardenberg@gmail.com>:

**Comment by Joshua260403** [comment]
Another solution could be just to copy the resources to the CWD (executable location for the team, parent dir on travis) without using a qrc since sfml is able to use uncompiled resources.

**Comment by janderkkotlarski** [comment]
Segfault borked under Linux.

**Comment by richelbilderbeek** [comment]
I assume this fixed. @janderkkotlarski will work on this today, and create a new Issue if this still happens.
