### ISSUE TITLE
Make shop button do stuff

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#596]
When a shop button is clicked the following events should take place:
- [x] check essence amount, if lower than price: stop
- [x] create a new tile of the right type
- [x] make that tile follow the mouse
NOTE: the game should still be paused at this point, only the new tile should be able to move (with the mouse) and rotate
- [x] if the player clicks try to place the tile on the nearest valid position (in the grid)
- [x] if the placement is successful: take away correct amount of essence
- [x] go back to the shop

**Comment by martje127** [comment]
on witch issue depens it on

**Comment by Joshua260403** [comment]
on creating a shop button ofc

Op do 23 mei 2019 20:19 schreef martje127 <notifications@github.com>:
