### ISSUE TITLE
Don't include qrc_djog_unos_2018.cpp in codecov

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#599]
The qrc file is included in the code coverage. Make it so codecov excludes `qrc_*`.

**Comment by Joshua260403** [comment]
@richelbilderbeek also main.cpp is impossible to get to 100% on topic branches because of profilling

**Comment by richelbilderbeek** [comment]
Agreed.

Probably fixed now: that was easier than replying :+1:
