### ISSUE TITLE
Create a topic branch for yourself

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#6]
Make a topic branch for yourself. Keep the name short! For example, I will have `richel`.

**Comment by Joshua260403** [comment]
How does one do this?

**Comment by richelbilderbeek** [comment]
@Joshua260403 : within GitHub, go to the top left, where on selects a branch. By default, this is set to `master`. Click it and add a branch, say `joshua`.

**Comment by Joshua260403** [comment]
Done, named it `Joshua`.

**Comment by Joshua260403** [comment]
> Done, named it `Joshua`.

With a capital `J`, does this matter and if so, can it be renamed?

**Comment by richelbilderbeek** [comment]
> Does this matter?
No. You will be the only one struggling with the deviation from the naming convention.

> Can it be renamed?
No. But it can be deleted easily and recreated. At the main page, click 'Branches'. There you can delete it.

**Comment by annehinrichs22** [comment]
done

**Comment by richelbilderbeek** [comment]
AFAICS, everyone has done this. Well done team!

**Comment by richelbilderbeek** [comment]
Reopened for Mohammed and @EllyJet.

**Comment by mohammadmatr** [comment]
Done

**Comment by richelbilderbeek** [comment]
Well done @chezclaire!

**Comment by richelbilderbeek** [comment]
All team members have a branch. Go team! Closing the Issue.
