### ISSUE TITLE
Link Team Octane to Anton Hensen

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#600]
I found an option to link the name Team Octane to the application Nature Zen (and with that to the dev account).

We'll have to read a bit more about it but i think that is the right thing to do.

**Comment by Joshua260403** [comment]
https://partner.steamgames.com/creatorhome/81302 at the bottom of this page.

I filled in Team Octane in the developers section of the shop page to achieve this (don't worry about me messing it up, it can be removed)

**Comment by antonhensen81** [comment]
By the looks of it I can create a new group under my account if I wish to publish other content not related to Team Octane and Nature Zen, which at some point I intend to do since I'm working on a VR game of my own. So this seems just fine. Good job :-)

**Comment by antonhensen81** [comment]
I closed this issue since I think you are done @Joshua260403
