### ISSUE TITLE
Vote: achievements: yes/no

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#602]
Do we want there to be achievements?

If the vote ends in yes:
- [ ] Create a new class `achievement_manager`
- [ ] Find a way to save achievements forever (don't reset them when the game is closed)

If voted for steam achievements:
- [ ] Setup steam achievements

**Comment by richelbilderbeek** [comment]
For now: no.

**Comment by martje127** [comment]
for now: no

**Comment by RafayelGardishyan** [comment]
For now: YES

**Comment by robkruger** [comment]
Yes

**Comment by AramPetiet** [comment]
OI dont close
- Joshua

**Comment by AramPetiet** [comment]
For now: No

**Comment by Enzo9** [comment]
yez

**Comment by Joshua260403** [comment]
Not for now, but defo later.
