### ISSUE TITLE
Undefined reference to SFML on Windows

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#62]
# Issue:

- OS: Windows
- Version: ?
- SFML Version: ?

### Issue Description

Linking errors (continued from #60)

### How to reproduce:

Unknown

**Comment by Joshua260403** [comment]
do you think the problem has to do with the linker, since windows can't use ld.gold.exe

**Comment by Joshua260403** [comment]
Adding the line "LIBS += -LC:\SFML\bin" did the trick!

**Comment by Joshua260403** [comment]
nevermind it just said it can't read the files in that folder before the other errors would occur

**Comment by Joshua260403** [comment]
have been trying for an hour now but still no progress

**Comment by richelbilderbeek** [comment]
Yuck, I find these the shittiest kind of errors.

Do you think a dual-boot Windows/Linux laptop would be a better option?

**Comment by Joshua260403** [comment]
I will decide about dual booting linux or a vm friday

Op di 18 sep. 2018 19:13 schreef Richel Bilderbeek <notifications@github.com

**Comment by Joshua260403** [comment]
I saw some people are saying that the version of sfml you are using could cause problems. Is there a specific version of sfml i should use / does it matter if i use sfml 2.0 instead of 2.5.0

**Comment by Joshua260403** [comment]
I DID IT!!!!!!!!! I have no more issues. Followed the tutorial shared by same. SFML version 2.0
next problem.... it crashes when ran
