### ISSUE TITLE
Try to make tile::get_corner constexpr

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#628]
**Is your feature request related to a problem? Please describe.**

I see that [tile::get_corner takes up 15% of all run-time](https://travis-ci.org/richelbilderbeek/djog_unos_2018/builds/539831797#L2260). Taking a closer look at the function, it appears it can be made `constexpr`.

**Describe the solution you'd like**

 * Find out what `constexpr` is
 * If possible, make the function `constexpr`, else close the Issue with 'It can be done'.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by robkruger** [comment]
It cannot be done I think because it is variable, it changes when the tile gets rotated
