### ISSUE TITLE
Anne won't be joining on friday (cool link included though)

### ISSUE THREAD

**Issue by annehinrichs22** [richelbilderbeek/djog_unos_2018#63]
Because I will be competing in a mathematics tournament which is located in Nijmegen I won't be back in time to join unfortunately.
To compensate for the sudden loss of `cabin pressure` Anne's assistance, [here's a link](https://www.humblebundle.com/books/game-development-books?hmb_source=navbar&hmb_medium=product_tile&hmb_campaign=tile_index_3) to some books that are on sale right now and look cool. (They are about programming games in C++.) #

**Comment by richelbilderbeek** [comment]
OK, thanks for the notification! Happy to hear you are going to do something cool. Enjoy!
