### ISSUE TITLE
My branch stalls and I don't know why

### ISSUE THREAD

**Issue by robkruger** [richelbilderbeek/djog_unos_2018#634]
**Is your feature request related to a problem? Please describe.**
My branch stalls when running --god --short 600. It works fine locally. 

**Describe the solution you'd like**
I looked into it for more than an hour, but I can't find the problem. @richelbilderbeek could you look into it?

**Comment by Joshua260403** [comment]
I think rafayel did something (see master)

Also, @RafayelGardishyan, well, see master

**Comment by robkruger** [comment]
No, it stalls since [this](https://travis-ci.org/richelbilderbeek/djog_unos_2018/builds/539844681) build already.

**Comment by richelbilderbeek** [comment]
That rascal @RafayelGardishyan, breaking `master` :sunglasses: 

Will take  a look before Thursday, probably already today :+1:

**Comment by robkruger** [comment]
Found something?

**Comment by robkruger** [comment]
I deleted my branch and recreated so this can be closed
