### ISSUE TITLE
Program crashing immediately

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#66]
# Issue:
- OS: Windows 10
- Qt Version: 5.9.1
- SFML Version: 2.0

### Issue Description
The program crashes immediately when it is ran

### How to reproduce:
unknown:

**Comment by Joshua260403** [comment]
When i run it in debug it says "During startup program exited with code 0xc0000135."

**Comment by richelbilderbeek** [comment]
Hmmm, we set the program to close after a 100 frames  (approx 2 seconds). The Travis CI build passes. Maybe it just works :confused: ? Could you paste the complete program output here?

**Comment by richelbilderbeek** [comment]
There is a line that determines how long the game runs, [this one](https://github.com/richelbilderbeek/djog_unos_2018/blob/master/game.cpp#L90). Set it to something higher. Will this result in a proper and longer game run?

**Comment by Joshua260403** [comment]
The entire output is just 2 lines:
The program crashed
The program was forcefully stopped

But when run in debug it gives me a message (i believe i posted that above)

Op wo 19 sep. 2018 07:29 schreef Richel Bilderbeek <notifications@github.com

**Comment by richelbilderbeek** [comment]
> But when run in debug it gives me a message (i believe i posted that above) 

If

```
During startup program exited with code 0xc0000135.
```

is the output of the debug run, something may be deeply wrong. It may be that the libraries mismatch. It may even be that SFML is not properly installed yet at all :slightly_frowning_face:. But it can also be that the music file or part of the graphics is not supported  

To find out, the debugger may help. Else sprinkling some `std::cout` (or better: `std::clog`) messages through the code may help identify the line that causes the crash. 

Good luck!

**Comment by Joshua260403** [comment]
Sfml mismatch, as in i use 2.0 and rafayel and you use 2.5.0?

Op wo 19 sep. 2018 08:10 schreef Richel Bilderbeek <notifications@github.com

**Comment by Joshua260403** [comment]
My compiler is MinGW530_32

**Comment by richelbilderbeek** [comment]
I use g++ (7.2.0), but it is not about that. It is about using a DLL created with say MinGW530_32, where the Qt Creator Project uses a different compiler. It does not matter which compiler you use, but that you use the same all the time. Clearer?

**Comment by Joshua260403** [comment]
Never used anything else than MinGW530_32

Op wo 19 sep. 2018 08:36 schreef Richel Bilderbeek <notifications@github.com

**Comment by Joshua260403** [comment]
placed the sfml dlls in the folder with the compiler exe and it worked

**Comment by richelbilderbeek** [comment]
@Joshua260403 : I would not mind if you would document on this GitHub what you did exactly :innocent:

**Comment by richelbilderbeek** [comment]
I did it too! :tada:. Will document now!

**Comment by richelbilderbeek** [comment]
# Solution

if you get this error, this means Qt Creator cannot find the path to the SFML binaries.

To fix this, in Qt Creator, click 'Projects' (at the left vertical menu bar), go to 'Build', go to 'Build Environment', add to the `Path` variable: `C:\Qt\sfml\bin`
