### ISSUE TITLE
Do a trivial git push

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#7]
Do a trivial `git push` to this repo. That way, we know you can do this. 

Mention you did so here and unassign yourself.

**Comment by Joshua260403** [comment]
Done

**Comment by Joshua260403** [comment]
Someone did a commit directly to the master branch...

**Comment by richelbilderbeek** [comment]
Sure, that can be done. It *is* risky though and breaking the `master` will have some consequences (e.g. bringing coffee/lemonade) for as long at is broken.

**Comment by richelbilderbeek** [comment]
AFAICS everyone has done this. Go team!
