### ISSUE TITLE
program closes when ran

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#72]
windows 10
sfml 2.0

### Issue Description
The program runs but after i see the window it immediately closes again

Log says program exited with code 0

**Comment by Joshua260403** [comment]
@richelbilderbeek new issue :)

**Comment by richelbilderbeek** [comment]
No, this is actually great! It means IT WORKS :tada: ! Exit code zero denotes an OK! It ran for 100 ticks (change the 100` in the code to something bigger).

If no questions, this Issue can be closed.
