### ISSUE TITLE
Do a trivial git merge

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#8]
On your topic branch, after having done a trivial push (#7), merge your branch with `develop`. Then, merge `develop` with your branch. Post here you did so.

```
git checkout develop
git merge richel
git push
```

```
git checkout richel
git merge develop
git push
```

**Comment by Joshua260403** [comment]
Done

**Comment by richelbilderbeek** [comment]
AFAICS most of us did so. Go team!
