### ISSUE TITLE
Merge conflict

### ISSUE THREAD

**Issue by Joshua260403** [richelbilderbeek/djog_unos_2018#80]
Whoops, how do i fix this

**Comment by Joshua260403** [comment]
@richelbilderbeek

**Comment by richelbilderbeek** [comment]
I @Joshua260403: I do not see a merge conflict on your branch.

If you have it locally, do:

 * Fix the files with a merge conflict. You can recognize them by `<<<<`, `====` and `>>>>` pieces of text
 * Then `git` add, commit, push

If questions, just push the merge conflicts, and I will fix it,

**Comment by Joshua260403** [comment]
Resolved, may be some newlines left in team.md because phones
