### ISSUE TITLE
Read: what kind of game are we making?

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#83]
### Issue Description

[here](https://github.com/richelbilderbeek/djog_unos_2018/blob/master/doc/game.md) you can find the current idea of the game we are making

### Procedure

Read it. If you've read it, unassign yourself.

You are encouraged to suggest future development in #30 , #32 and #34

**Comment by Joshua260403** [comment]
Unassigning is done by click un the little gear at the assignees section in the top right and deselecting yourself

**Comment by Joshua260403** [comment]
I think you meant this
