### ISSUE TITLE
Setup AppVeyor

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#84]
**Is your feature request related to a problem? Please describe.**

Most of the team use Windows. I do not. As AppVeyor uses a Windows system, if it works there, it should work on the computers of the kids.  

**Describe the solution you'd like**

I will need to setup AppVeyor.

**Describe alternatives you've considered**

Let the team use a VM or dual-boot if they cannot set it up.

**Additional context**

None

**Comment by RafayelGardishyan** [comment]
Nice idea!

**Comment by richelbilderbeek** [comment]
As lead dev I have to: I cannot ignore the fact that most of my devs use Windows...

**Comment by Joshua260403** [comment]
Is appveyor travis for windows?

**Comment by richelbilderbeek** [comment]
It is! Would you be interesting in getting this to work?

**Comment by richelbilderbeek** [comment]
Sure I will help, the AppVeyor is there already!

**Comment by Joshua260403** [comment]
Appveyor doesn't know the command qmake

**Comment by Joshua260403** [comment]
YEET I DID IT

**Comment by Joshua260403** [comment]
The problem now is std::to_string, "to_string is not a member of std"

**Comment by richelbilderbeek** [comment]
Awesome! Well done :+1:
