### ISSUE TITLE
Test tile

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#85]
**Is your feature request related to a problem? Please describe.**

The `tile` needs to be tested.

**Describe the solution you'd like**

In `develop`, in `tile.cpp` is a function called `test_tile` that tests the tile.

Uncomment this line to start fixing:

```c++
///#define FIX_ISSUE_85_TEST_TILE
```

If all tests pass, you can close this Issue yourself. 

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by Joshua260403** [comment]
Right?

**Comment by richelbilderbeek** [comment]
Reopen, as the preprocessor directives need to be removed. Easy, let's find someone to clean this up :+1:
