### ISSUE TITLE
Select a tile by clicking left mouse button

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#86]
**Is your feature request related to a problem? Please describe.**

One cannot select a tile by clicking the left mouse button yet. Users expect to be able to do so.

**Describe the solution you'd like**

 * If a tile is clicked, it should display a different color
 * If the background is clicked, the tile(s) lose selectedness

**Describe alternatives you've considered**

None

**Additional context**

 * There will be no member variable added to `tile`: a real-world tile does now know it is selected by a user
 * Most changes will take place in `sfml_game`
 * `sfml_game` will have to store which `tile` is selected. Suggestion: `std::vector<T> m_selected`, which is empty if no tile is selected and has a type `T` to be able to conclude which `tile` 
 * `tile` will probably need a `operator==` and `operator!=`
 * You may add an ID to the `tile`: `const int m_id`

**Comment by Joshua260403** [comment]
hmm i'll see about this

**Comment by Joshua260403** [comment]
every tile has an id accessable by get_id() and set_id()

**Comment by martje127** [comment]
if you klik on the left mouse button the tiles the are selectet
