### ISSUE TITLE
Set tile speed

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#87]
**Is your feature request related to a problem? Please describe.**

The class `tile` has no way to change its position.

**Describe the solution you'd like**

In `tile`:

 * Add member variables `double m_dx` and `double m_dy` to store the horizontal and vertical speed of the `tile`
 * Add a member function `set_speed` that takes two arguments: the speed in horizontal and vertical direction.
 * Add a member function `move` that takes no arguments. It changes the `m_x` and `m_y` of `tile`
 * Pass all tests in the `test_tile` function, uncomment line:

```c++
//#define FIX_ISSUE_87_SET_TILE_SPEED
```

**Describe alternatives you've considered**

None.

**Additional context**

If the tests pass, you can close the Issue yourself

**Comment by Joshua260403** [comment]
Where is this done and why is it in done without being closed

**Comment by Joshua260403** [comment]
This wasn't even assigned to anyone

**Comment by richelbilderbeek** [comment]
I think @RafayelGardishyan assumed `Resolved #87` would close the Issue automatically. AFAIK, only `fix #87`/`fixed #87`/`Fix #87`/`Fixed #87` can achieve that.

**Comment by richelbilderbeek** [comment]
Re-open, as preprocessor statements need to be removed. Easy, but it needs to be done :+1:
