### ISSUE TITLE
Add a second tile of a second type

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#89]
**Is your feature request related to a problem? Please describe.**

We now have one tile of one type. Boring!

**Describe the solution you'd like**

 * `game` must start with two `tiles`
 * the second `tile` must have a different `tile_type`
 * the test in `test_game` must pass. Run the test by un-commenting the following line:

```c++
//#define FIX_ISSUE_89_ADD_SECOND_TILE
```

**Describe alternatives you've considered**

None.

**Additional context**

After local tests pass, move this Issue to the 'To be checked by testing' column of the Project. The testers will verify if the second tile is indeed displayed differently. Then the testers may close this Issue.

**Comment by Joshua260403** [comment]
I'll take this job.

**Comment by Joshua260403** [comment]
added 2! Ocean and mountains are now a real thing!!!!!!!

**Comment by martje127** [comment]
beautiful tiles
