### ISSUE TITLE
A game has a score

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#90]
**Is your feature request related to a problem? Please describe.**

A game should have a score

**Describe the solution you'd like**

 * Add a member variable of type int called `m_score` to `game`
 * Uncomment the following line in `test_game`

```c++
//#define FIX_ISSUE_90_GAME_MUST_HAVE_A_SCORE
```

and make the test compile and pass

**Describe alternatives you've considered**

None.

**Additional context**

 * No need to modify the score yet
 * Developer may close this Issue if and only if the test passes

**Comment by RafayelGardishyan** [comment]
Fixed!

**Comment by Joshua260403** [comment]
Done but not closed?
