### ISSUE TITLE
Architectural: move sfml_game::m_n_displayed to game::m_n_ticks

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#91]
**Is your feature request related to a problem? Please describe.**

The architecture can be improved. The number of game cycles is not part of the visualization of the game, but of the game itself. The architecture must reflect that.

**Describe the solution you'd like**

 * Remove `sfml_game::m_n_displayed`
 * Add `game::m_n_ticks`
 * `game::m_n_ticks` must be incremented whenever `game::process_events` is called.
 * In `game_test` uncomment the line below and make all tests pass:

```c++
//#define FIX_ISSUE_91_GAME_TRACKS_THE_NUMBER_OF_TICKS
```
**Describe alternatives you've considered**

None.

**Additional context**

If all tests pass, this Issue can be closed by the developer.

**Comment by richelbilderbeek** [comment]
@RafayelGardishyan: I will assign you this, as it fits your job description best :+1:

**Comment by RafayelGardishyan** [comment]
This issue is outdated because I resolved this when I separated Logic and Graphics

**Comment by RafayelGardishyan** [comment]
FIxed!

**Comment by richelbilderbeek** [comment]
Test does not pass. Perhaps something went wrong with merging. Will re-open Issue.

**Comment by richelbilderbeek** [comment]
The test `FIX_ISSUE_91` does not pass yet, so re-opened this Issue.

**Comment by Joshua260403** [comment]
Was placed at to be tested, but this is architectural.

**Comment by robkruger** [comment]
Where is it meant to be placed then?
