### ISSUE TITLE
Add agents on the tiles

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#92]
**Is your feature request related to a problem? Please describe.**

There may be an `agent` class (#88), but it must be added on the `tile`s. 

**Describe the solution you'd like**

 * Add a member variable to `tile`: `std::vector<agent> m_agents`
 * Add a `tile` const member function to get the agents by reference 
 * Uncomment the following line in `test_tile` and make the tests pass:

```c++
//#define FIX_ISSUE_92_ADD_AGENTS_ON_TILES
```

**Describe alternatives you've considered**

None.

**Additional context**

If all tests pass, this Issue can be closed by the developer.

**Comment by Joshua260403** [comment]
Did @Rijk-van-Putten do this?

**Comment by richelbilderbeek** [comment]
@Joshua260403: if you ever interested in who-did-what questions, click 'Blame' (some -like me- think it should be called 'Praise'):

![2018-10-07-203123_1920x1056_scrot](https://user-images.githubusercontent.com/2098230/46585350-2292e400-ca70-11e8-9092-3268fbb8993f.png)

There you can see who did what. Enjoy!

**Comment by richelbilderbeek** [comment]
Oops, did so myself.
