### ISSUE TITLE
Visualize agents

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#93]
**Is your feature request related to a problem? Please describe.**

After #92 ('Add agents to tiles') there may be agents on the tiles, but these are not displayed yet.

**Describe the solution you'd like**

 * Give each `tile` one `agent` that is exactly in the middle of it
 * Let `sfml_game` display the agents.

**Describe alternatives you've considered**

None.

**Additional context**

 * If done, move this Issue in the 'To be checked by testing' column. If the testers observe the agents, they may close this Issue.
 * If done, Issue #33 ('agents must have some intelligence') can be done. That Issue will then be set to 'Medium priority'

**Comment by richelbilderbeek** [comment]
Hi @RafayelGardishyan, I unassign you as there may be others that want to do this. I see you are not in the 'In Progress' Project columns, so I assume you are not working on it. Please try to assign yourself one task as a rule. The exception will be when I assign you an additional second/third Issue, for reasons there specified.

**Comment by Joshua260403** [comment]
@EllyJet do want to do this issue, and did she unassign because she is not actively working on it? Or did you unassign because you want to do something else?

**Comment by richelbilderbeek** [comment]
The first agent will be a cow, see #140. Do that one first.

**Comment by richelbilderbeek** [comment]
Will close this Issue, as there are cows visible.
