### ISSUE TITLE
Visualize score

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#94]
**Is your feature request related to a problem? Please describe.**

The game may have a score (#90, 'A game has a score') but it is not displayed anywhere.

**Describe the solution you'd like**

 * Within `sfml_game`, display the score somehow and somewhere

**Describe alternatives you've considered**

None.

**Additional context**

After the score is visualized, move this Issue to the 'To be checked by testing' to let the testers verify this. The testers can close this Issue if the score is indeed observed.

**Comment by Joshua260403** [comment]
If no one else wants this you can assign me, but as i already assigned myself a moment ago i'll let someone else choose this if they want.

**Comment by richelbilderbeek** [comment]
@Joshua260403 this job can only be done after #90 ('A `game` has a score'), so I'd suggest to one day do that one first :rainbow:

**Comment by richelbilderbeek** [comment]
Unsure if this is done. Will unassign and more to 'To do'.

**Comment by Joshua260403** [comment]
There is a zero in the top right of the screen, is this issue done?

**Comment by richelbilderbeek** [comment]
Indeed, thanks to @martje127. Sloppy me, should have paid better attention to the process...
