### ISSUE TITLE
Keep this music or change it

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/djog_unos_2018#96]
**Is your feature request related to a problem? Please describe.**

Thanks to @RafayelGardishyan the game has some music, but it is unknown if @same-drenth agrees. 

**Describe the solution you'd like**

If @same-drenth:

 * approves, he can close this Issue
 * disagrees, he can select some other music and add it. He can ask @RafayelGardishyan for questions how to do so.

The music should be selected and downloaded in one's spare time. The music should be free (as in speech). Adding that free music to the project can be done at DJO. 

**Describe alternatives you've considered**

None.

**Additional context**

If and only if there is strong disagreement about music choice, there will be a vote on that subject.

**Comment by richelbilderbeek** [comment]
I assign @same-drenth on this, as this is his responsibility :+1:

**Comment by Joshua260403** [comment]
or make music selectable in menu (later addition)

**Comment by richelbilderbeek** [comment]
Agree, also that it is something for later :-)

**Comment by same-drenth** [comment]
I agree with that there should be multiple songs in the game. Possibly selectable or for different levels. 
We also need a simple menu tune when the menu screen is made.

**Comment by richelbilderbeek** [comment]
I assume this Issue can be closed, as I think @same-drenth agrees with the music enough for now :grin:
